### ISSUE TITLE
making the <that> tag work

### ISSUE THREAD

**Issue by chrispool** [keiffster/program-y#1]
I'm trying to create a chatbot using program-y but can't seem to get the <that> tag working. Do you have an example of a working <that> tag? 

The aiml I used is:

```
<?xml

 version="1.0" encoding="ISO-8859-1"?>
<aiml version="2.0">


<category>
<pattern>I LIKE COFFEE</pattern>
<template>Do you take cream or sugar in your coffee?</template>
</category>

<category>
<pattern>YES</pattern>
<that>DO YOU TAKE CREAM OR SUGAR IN YOUR COFFEE</that>
<template>I do too.</template>
</category>

<category>
<pattern>NO</pattern>
<that>DO YOU TAKE CREAM OR SUGAR IN YOUR COFFEE</that>
<template>Really? I have a hard time drinking black coffee.</template>
</category>
</aiml>```

**Comment by keiffster** [comment]
Almost certainly I'm not stripping out the ?. Have tried it with the ? left in the <that> tag

I'll have a look later this morning and add your aims to the test cases to prove it works ( or prove its fixed )

**Comment by keiffster** [comment]
Fixed in 0.2.0, and your aiml has been added to the test_aimls folder
Currently it does include the ? as part of the that, but I am looking to see if its worth stripping punctation out in a future release

Hope it find it useful

keith

**Comment by chrispool** [comment]
Thanks for the quick reply, but the tag doesn't appear to work. I also tried the other that in the test folder. This is the output i get:

```
>>>: i like coffee
Do you take cream or sugar in your coffee?
>>>: no
Sorry, I don't have an answer for that!
>>>: hello
Hi there
>>>: hello again
Hello without that
```

I initiate a BotClient() instead of using the ConsoleBotClient() but that should not make a difference looking at the code?

**Comment by keiffster** [comment]
Not sure if we have overlapped, new version 0.2.0 is published and fixed the issue

**Comment by keiffster** [comment]
If we didn't overlap and you are using 0.2 then I'll build a grammar and check it this evening

**Comment by keiffster** [comment]
Ok, I've found the problem, its to do with upper and lower case mismatch in the that processing. I do all the testing in upper case, but I see your grammar is mixed. I'll work on a fix and get back to you

**Comment by chrispool** [comment]
I pulled v0.2.  Tried several templates/patterns but didn't get it to work. Thanks for your help!

**Comment by keiffster** [comment]
Fixed, 0.2.1 just uploaded, check out the tutorial bot, where i have your coffee.aiml file loaded
Ran it and got the following

Loading, please wait...
No bot root argument set, defaulting to [/Users/keithsterling/Documents/Development/Python/Projects/AIML/program-y/bots/tutorial]
KeiffBot 1.0 version 0.0.1, initiated September 9th, 2016
Hi, how can i help you today?
>>> i like coffee
Do you take cream or sugar in your coffee?
>>> yes
I do too.
>>> i like coffee
Do you take cream or sugar in your coffee?
>>> no
Really? i have a hard time drinking black coffee.
>>>

**Comment by keiffster** [comment]
Also worth noting that as per the original AIML processors, all AIML text should be in a upper case. Its convert to upper case when the parse tree is built, and then any input you type in is also converted, this makes all matching only  needed in upper case which makes it easier.

In terms of output, its converted from upper case to sentence text by the post processor, leaving it to the very last minute before doing so, again for ease of use

Sorry about the multiple attempts to fix it. I do all the unit testing in upper case and so missed the upper/lower case issue

**Comment by chrispool** [comment]
Thanks, it works! I am planning to use this project for a project of mine, can i send you a private message? I have some other questions, and maybe in return I can help you write some documentation/tutorials etc

**Comment by keiffster** [comment]
Hi Chris
Glad you like it, still early days but it's been a passion of mine for a few years.

Email me on keiffster@gmail.com

K
