### ISSUE TITLE
Expand on the YDEFAULTRESPONSE pattern?

### ISSUE THREAD

**Issue by flamablecharlie** [keiffster/program-y#105]
Not quite a bug, but it seems to be the easiest way to contact you...

I know it's possible to edit the entry in core/default_response.aiml so that instead of saying "Sorry, I don't have an answer for that!," we execute a system script instead. 

But how can I pass along what the user said to the script for further processing?

**Comment by keiffster** [comment]
The tag you are looking for is `<request />` which returns the text the user entered, so as part of YEMPTY processing you could include

```
<category>
<pattern>YEMPTY</pattern>
<template>
       I am not sure what "<request />" means, could you be a little more specific?
</template>
</category>
```

**Comment by flamablecharlie** [comment]
Thank you! That works!
