### ISSUE TITLE
<topic> Breaks Up in Sanic Client

### ISSUE THREAD

**Issue by abcortes** [keiffster/program-y#106]
* Detailed Description

It looks like \<topic\> is breaking up in sanic client, in particular using rest production script.

My AIML works in console and flask. What could be a quick work-around?

Behaviour is intermittent. It is like as if multiple channels are listening. When you do a ps you will see multiple forks of the script sanicrest.py. I am still looking for the proper way to fix. I remember that this was working before.

* Testing
$ curl -s "http://localhost:5000/api/v1.0/ask?question=buy%20flowers&sessionid=acortes@ZjuPE45PaYGaaJ58pypTfSyuojcjymnz2h"

* Response
{"question":"buy flowers","sessionid":"acortes@ZjuPE45PaYGaaJ58pypTfSyuojcjymnz2h","answer":"Sorry, I don't understand. Please rephrase your message."}

* Environment
    Version of Y-Bot: program-y 1.2.0
    Version of Python: Python 3.5.2
    Operating System: Ubuntu 16

**Comment by keiffster** [comment]
Just run some tests on my own version and not seeing the problem, can you either send me the grammar that is causing the issue or try and boil it down to the just the categories which fail

**Comment by keiffster** [comment]
If you set the number of workers=1 it will work for now in sanicrest.py, lines 88-92
        APP.run(host=REST_CLIENT.configuration.client_configuration.host,
                port=REST_CLIENT.configuration.client_configuration.port,
                debug=REST_CLIENT.configuration.client_configuration.debug,
                workers=1)
                #workers=REST_CLIENT.configuration.client_configuration.workers)

**Comment by abcortes** [comment]
Thanks! That is what I am looking for, in the configuration. I'll take that one as a temporary fix. But I am sure that will affect sanic as being a fast service.

**Comment by abcortes** [comment]
I am closing this issue for now. Let's just have a todo or take the multiple worker for sanic as a different issue.

**Comment by keiffster** [comment]
A quick fix has been uploaded to master for the sanic work thread issue. You can now run with multiple workers again. 

A more robust fix is coming in the following days
