### ISSUE TITLE
get issue

### ISSUE THREAD

**Issue by kkhzz1004** [keiffster/program-y#107]
```
<?xml version="1.0" encoding="UTF-8"?>
<aiml version="2.0">
  
   <category>
      <pattern>I am *</pattern>
      <template>
         Hello <set name = "username"> <star/>! </set>
      </template>  
   </category>  
   
   <category>
      <pattern>Good Night</pattern>
      <template>
         Hi <get name = "username"/> Thanks for the conversation!
      </template>  
   </category>  

</aiml>
```
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

i am kim

botwill 9:49 AM
Hello kim!

william Admin 9:49 AM
Good night

botwill 9:49 AM
Hi kim! Thanks for the conversation!

william Admin 9:49 AM
i am lee

botwill 9:49 AM
Hello lee!

william Admin 9:49 AM
good night

botwill 9:49 AM
Hi kim! Thanks for the conversation!

william Admin 9:49 AM
good night

botwill 9:49 AM
Hi kim! Thanks for the conversation!

william Admin 9:49 AM
good night

botwill 9:49 AM
Hi lee! Thanks for the conversation!
////////////////////////////////////////////////////////////////////////////////////////////////////////////////

it seem like delayed? please check this :)

**Comment by kkhzz1004** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<aiml version="2.0">
  
   <category>
      <pattern>I am *</pattern>
      <template>
         Hello <set name = "username"> <star/>! </set>
      </template>  
   </category>  
   
   <category>
      <pattern>Good Night</pattern>
      <template>
         Hi <get name = "username"/> Thanks for the conversation!
      </template>  
   </category>  

</aiml>

**Comment by keiffster** [comment]
Which client are you using ?

**Comment by kkhzz1004** [comment]
oh i just solve the problem by editing config file -> workers: 1

**Comment by keiffster** [comment]
Known issue with sanic client, will be addressed shortly with the introduction of redis cache

K

**Comment by keiffster** [comment]
A quick fix has been uploaded to master for the sanic work thread issue. You can now run with multiple workers again. 

A more robust fix is coming in the following days
