### ISSUE TITLE
Y-Bot console error

### ISSUE THREAD

**Issue by zahassanyum** [keiffster/program-y#109]
The console gives the following error.

![image](https://user-images.githubusercontent.com/17967430/33881276-25180d82-df56-11e7-87ee-4d7951b251cd.png)

**Comment by keiffster** [comment]
Looks like I’m not writing the Braintree xml file as Unicode

Just seen I’m missing an encoding flag on the open statement

Fix coming shortly

**Comment by keiffster** [comment]
Just pushed an update to master, xml braintree file now opened in utf-8 format. 

However, I was unable to replicate the problem, but assumed it was unicode issue. Please let me know if this fixes the issue

**Comment by zahassanyum** [comment]
No, the error remains (I'm on Windows).

**Comment by keiffster** [comment]
Added the utf-8 flag in the wrong place, now added correctly and tested on window just pushed to master
