### ISSUE TITLE
Disable wiki and pannous services

### ISSUE THREAD

**Issue by ipapaioannou83** [keiffster/program-y#11]
Hi,

First of all I want to thank you for the wonderful work you've been doing on this project.
I was wondering if there is a way to completely disable the pannous and/or the wikipedia services on the bots, since whenever someone says an utterance consisting of only one Noun word, it gives a huge description of this word. From what I gathered from the logs it's one of these services that get the information. 
I tried to find the documentation on how to do that but could not find anything.

Thank you very much in advance.

**Comment by JustArchi** [comment]
Isn't it entirely controlled by the AIML? Program-Y is just a parser, you don't have to call ```<sraix>``` on wikipedia.

**Comment by keiffster** [comment]
Which grammar are you using, this typically means that the default response is missing and so a pannous and wiki are getting interpreted

**Comment by ipapaioannou83** [comment]
I removed the calls from `<sraix>` and from the service config file, so that "fixed" it for now. Thank you @JustArchi
