### ISSUE TITLE
Some fixes in the Y-Bot Grammar

### ISSUE THREAD

**Issue by zahassanyum** [keiffster/program-y#110]
**Sample inputs/responses:**

> Do you know einstein?
_I don't know what einstein is **for**._

> What do u know?
_They do their own thing._

While the following inputs doesn't have a response:

Terrific!
Ready?
Hahah! / Ahaha!
joke / tell me a joke
Man made alcohol!

Will keep testing and posting here. 

Great job on the updated grammar. Y-Bot is gradually becoming an all-rounder! :)

**Comment by keiffster** [comment]
New grammar addded

Do you know einstein
      New grammar added DO YOU KNOW <set name="famous"/>
      New set added famous.txt

Whats do u know
     New normalisation added t convert u into you

Terrific - Added
Ready - Added
Hahah - Added
Ahaha - Added
Joke - Enabled ( was disabled by default )
Man made alcohol - Added
