### ISSUE TITLE
Line break tags

### ISSUE THREAD

**Issue by Vishal-7** [keiffster/program-y#111]
Why doesn't the linebreak tag not work when i host my bot on the net. It works properly when i run the bot through the y-bot console. What can i do to make the bot break the line while hosting on the web?
Thank you in advance

**Comment by ideasean** [comment]
Take a look at the consoleformat.py postprocessor (specified in _botdir_/config/postprocessors.config). It wraps automatically at 80 chars. You can comment it out if you just want long strings in the output.

For us we want more control of line breaks, so we use '||' in AIML to specify manual line breaks. We then wrote a basic postprocessor that detects the || and replaces it with <br/> and a line break. We use HTML for production (in Skype For Business) and console for testing, and could live with <br/> in console output. 

It gets interesting if you want to start using proper <p> tags, <span> tags and css styling/formatting in your HTML for better output formatting. You also have to watch out that some clients may fall back to text only (like Skype for Business for iPhone / Mac), hence why we still rely on both the <br/> and line break. 

There's probably a way now to detect the client being used and handle both... we just haven't got to it yet :-)

**Comment by Vishal-7** [comment]
Thanks alot!!
