### ISSUE TITLE
Hosting the Bot

### ISSUE THREAD

**Issue by Vishal-7** [keiffster/program-y#112]
Can someone give me a step by step guide on how to host the y-bot onto a server. I am actually not quite familiar with the process. Thanking you in advance

**Comment by keiffster** [comment]
I have a version running on AWS lightsail instance. I’ll publish the steps for this shortly

**Comment by keiffster** [comment]
Check out the wiki page

https://github.com/keiffster/program-y/wiki/Install_Linux_AWS

**Comment by Vishal-7** [comment]
Will i be able to host it using Google drive?

**Comment by keiffster** [comment]
As far as I am aware google drive is a file storage system, not a full Linux server so not sure that is possible

You need a web server and Python 3 install as a bare minimum

I know some one was looking at using google app engine

**Comment by Vishal-7** [comment]
Even if i did host the bot, What files would i have to transfer to the web server? Just the Y-bot folder or the entire program-y folder?

**Comment by keiffster** [comment]
Whatever you do, program-y needs to run as a full Python app on your server. 

You can the decide to either run it as a REST server and call it’s api from your own JavaScript/Ajax client or run it as web server using flask and use the inbuilt ( but very basic ) chat client.

Either way you need a full server running Python

**Comment by Vishal-7** [comment]
Can you give me the procedure to run it as a web server using FLASK and the inbuilt Chat-Client?

**Comment by Vishal-7** [comment]
Can you give me the procedure to run it as a web server using FLASK and the inbuilt Chat-Client?

**Comment by keiffster** [comment]
OK, which operating system are you intending to run the client on ?

Basic instructions are available available in [Installation](https://github.com/keiffster/program-y/wiki/Installation)

Can you let me know what you have tried and what problems you are stuck on ?

**Comment by Vishal-7** [comment]
I want to run the client on my windows system. I have installed all the required resources ,given in the instruction installation in the wiki. I did some research on FLASK,But i'm unsure how to proceed.

**Comment by keiffster** [comment]
Have you run y-bot-webchat.cmd ?

That will start a bot configured as a Flask based web client

**Comment by Vishal-7** [comment]
Yes..I have done that. What do i do after that

**Comment by keiffster** [comment]
Do you see something like ?

Loading, please wait...
No bot root argument set, defaulting to [.]
Initiating Webchat Client...
WebChat Client running on 0.0.0.0:8080

If you do, open a browser and enter the url http://localhost:8080

**Comment by Vishal-7** [comment]
that works perfectly. I as of now, use ngrok to make it available for everyone on the web to use it.

**Comment by keiffster** [comment]
Thats great news, I'd love to see it in action

**Comment by Vishal-7** [comment]
https://a60aa3af.ngrok.io/ This is the link to the Bot... But once i turn off the webchat.cmd, the bot stops working. Is there a way to make that batch file work forever?

**Comment by keiffster** [comment]
Hey, it looks great, looking forward to seeing it develop

To make it persist once you close the console, you need to install the app as a Windows service. It's not something I am familiar with as I work on Mac and Linux machines which have well-documented support for running daemons

I'll have a look at and see what I can work out

**Comment by Vishal-7** [comment]
Thanks for having a lot at it... Really appreciate  it :)

**Comment by ideasean** [comment]
Short of running as a full Windows service, or some other wrapper thats not native script, one approach is - 

- Schedule a cmd or vbs file to run under Windows task scheduler that checks for the presence of the main bot cmd file (eg webchat.cmd). Schedule to run at startup. 
- Mark the job to run in background, ie "run whether the user is logged in or not"
- If webchat.cmd not found, start it. If restarted several times in past x period, send an email to admin.
- Ensure the account used to run the job is set up properly to run the bot. Suggest don't use your personal account. Instead set up another user-level account with least privilege. Use RUNAS to launch a cmd window with the specified account and ensure it is setup with Python paths, environment vars etc to run the bot properly. 

There are other variants, eg to put a loop in webchat.cmd and schedule that with task scheduler. This monitor script approach works perhaps better if you have several scripts to track, or if scripts need to be started or restarted in a particular order. You could also include some other health checks, eg to ensure the bot is responding (via xmlhttp to specified port) and if not, kill and restart.

With the right setup it can be relatively bullet-proof. Maybe it won't run forever but it should theoretically run to just before the heat death of the universe assuming everything else remains stable...

**Comment by keiffster** [comment]
1.9 or 1.9.1 will contain cmd scripts and documentation on how to run Program-Y as a windows service
1.9 going through final testing now so probably in the next week or so for the service work

**Comment by KINGK3N** [comment]
Hi keiffster,
after running ./y-bot.sh in raspbian i get the error below. 

File "/home/pi/Documents/basicai/src/programy/services/wikipediaservice.py", line 18, in <module>
    import wikipedia
ImportError: No module named 'wikipedia'

i tried with the other bots like alice2 and i get the same error at the end.

**Comment by keiffster** [comment]
Have you run pip install -r requirements.txt

Alternatively pip install wikipedia

K

Keith Sterling
E: keith@keithsterling.com
M: +44 (0) 7771 597 630

**Comment by KINGK3N** [comment]
It's working now thanks for this great code! I'm just starting python 😊

Sent from my Windows 10 phone

**Comment by keiffster** [comment]
Thanks and glad you got sorted, let me know how you get on and if you need more help

Keith Sterling
E: keith@keithsterling.com
M: +44 (0) 7771 597 630
