### ISSUE TITLE
AIML file not being recognized by program-y

### ISSUE THREAD

**Issue by pranavlal** [keiffster/program-y#113]
Issue tracker is **ONLY** used for reporting bugs. NO NEW FEATURE ACCEPTED! Use [stackoverflow](https://stackoverflow.com) for supporting issues.

When I run the attached AIML file in my created bot, its entries are not loaded into the bot. I ask the bot a question to which I know the AIML file has an answer. I am told that the bot does not know.

## Expected Behavior

When I ask a question like what is cyber security, the bot to give the answer defined in the AIML file.
## Current Behavior

The boit says "I don't know" which is what I have configured it to say when it does not know an answer. I have configured this in config.yaml
## Possible Solution

I wish I knew what is happening.
## Steps to Reproduce

1. Copy the attached AIML file to your bot's AIML folder.
2. Copy the attached set files to the sets folder of your bot.
[botsynonims.txt](https://github.com/keiffster/program-y/files/1608905/botsynonims.txt)
[defendsynonyms.txt](https://github.com/keiffster/program-y/files/1608906/defendsynonyms.txt)
[how.txt](https://github.com/keiffster/program-y/files/1608907/how.txt)
[infosecvocabulary.txt](https://github.com/keiffster/program-y/files/1608908/infosecvocabulary.txt)
[malwaresynonims.txt](https://github.com/keiffster/program-y/files/1608909/malwaresynonims.txt)
[questionwords.txt](https://github.com/keiffster/program-y/files/1608910/questionwords.txt)
[README.txt](https://github.com/keiffster/program-y/files/1608911/README.txt)
[securitysynonyms.txt](https://github.com/keiffster/program-y/files/1608912/securitysynonyms.txt)
[botsynonims.txt](https://github.com/keiffster/program-y/files/1608913/botsynonims.txt)
3. Ask a question like  what is cyber security

4.

## Context (Environment)

I am on a digital ocean cloud instance. I am building a bot that will answer basic questions on information security.
* Version of Y-Bot:
Y-Bot, App: v1.4.2 
* Version of Python: 
3.5.5
* Operating System ( inc Version ): 
Ubuntu 16.04

## Possible Implementation

[ciso.txt](https://github.com/keiffster/program-y/files/1608903/ciso.txt)
[botsynonims.txt](https://github.com/keiffster/program-y/files/1608915/botsynonims.txt)
[defendsynonyms.txt](https://github.com/keiffster/program-y/files/1608916/defendsynonyms.txt)
[how.txt](https://github.com/keiffster/program-y/files/1608917/how.txt)
[malwaresynonims.txt](https://github.com/keiffster/program-y/files/1608918/malwaresynonims.txt)
[securitysynonyms.txt](https://github.com/keiffster/program-y/files/1608919/securitysynonyms.txt)

**Comment by keiffster** [comment]
Your AIML files have a .txt extension but by default program-y uses the .aiml extension. Unless you have changed this extension in the config file they will not get loaded.

**Comment by pranavlal** [comment]
Hi,

 

I had to change the extension of the AIML file for uploading it on to github. The file is called ciso.aiml in the bot,.

**Comment by pranavlal** [comment]
Hi all,

I have solved the problem. 
#I had not closed the <set> tag.
#There was an attribute error where I had missed a closing quotation in the name attribute.
 
I solved the above issues by validating my ciso.aiml file using xmllint
