### ISSUE TITLE
How do I customize the greeting of the bot when using the web chat client

### ISSUE THREAD

**Issue by pranavlal** [keiffster/program-y#114]
Issue tracker is **ONLY** used for reporting bugs. NO NEW FEATURE ACCEPTED! Use [stackoverflow](https://stackoverflow.com) for supporting issues.

I am running the web chat client. How do I customize its greeting? 
## Expected Behavior

I should be able to add my own greeting or the initial greeting in config.yaml should be honoured by the web chat client.
## Current Behavior

The greeting in config.yaml is not being displayed when I run the web chat client.
## Possible Solution

Alter the code of the bot to use the initial greeting in config.yaml or provide a custom greeting for the web chat client
## Steps to Reproduce

1. Create your own bot.
2. Launch the web chat client
3. Look at the initial screen.
4. You will see the greeting of y-bot come up.

## Context (Environment)

* Version of Y-Bot:
* Version of Python: 
* Operating System ( inc Version ):

**Comment by keiffster** [comment]
That is currently held in y-bot.js
