### ISSUE TITLE
How to config bot initiative a dialog with user? 

### ISSUE THREAD

**Issue by HCIS2020** [keiffster/program-y#118]
I mean when bot got no answer, bot initiative a dialog with user rather than give default response.

thanks a lot

Issue tracker is **ONLY** used for reporting bugs. NO NEW FEATURE ACCEPTED! Use [stackoverflow](https://stackoverflow.com) for supporting issues.

## Steps to Reproduce

1.
2.
3.
4.

## Context (Environment)

* Version of Y-Bot:
* Version of Python: 
* Operating System ( inc Version ):

**Comment by keiffster** [comment]
Hi there,

Not sure what you mean by initial a dialog. The default answer can be configured either in config.yaml, or by using either the YDEFAULTRESPONSE or YEXITRESPONSE grammars

You could change these to ask a question rather than give a default response, for example

Change
default_response: Sorry, I don't have an answer for that!
To
default_response: Sorry, could you ask that differently please?

K

**Comment by HCIS2020** [comment]
Thanks for your reply. I mean we config default_response: Sorry, could you ask that differently please?
  in config.yaml. we always get one fixed response.

I have following content in aiml: 
<category>
<pattern>ASK USER A QUESTION</pattern>
<template>
<condition>
<li>你多大了?</li>
<li name="job" value="">你的职业是?</li> 
<li name="favmovie" value="">你最喜欢的电影是?</li> 
<li name="location" value="">你住哪呢?</li>
<li name="eyecolor" value="">What color are your eyes?</li>
<li name="haircolor" value="">What color is your hair?</li>
<li>你最喜欢什么颜色?</li>
</condition>
</template>
</category>

how could I config default_response_srai as ASK USER A QUESTION

**Comment by keiffster** [comment]
Fairly simple way to do this is to use the following config option

default_response_srai: YDEFAULTRESPONSE

In Program-Y Y-Bot this maps to the following grammar in unknown.aiml

```xml
    <category>
        <pattern>YDEFAULTRESPONSE</pattern>
        <template>
            <random>
                <li>
                    Sorry, I don't have an answer for that!
                </li>
                <li>
                    Sorry, no idea!
                </li>
            </random>
        </template>
    </category>
```
You think you are getting the same response, but really the random selection is probably just picking the same response 2 or 3 times in a row

Just replace this with

```xml
    <category>
        <pattern>YDEFAULTRESPONSE</pattern>
        <template>
            <li>你多大了?</li>
            <li>你的职业是?</li>
            <li>你最喜欢的电影是?</li>
            <li>你住哪呢?</li>
            <li>What color are your eyes?</li>
            <li>What color is your hair?</li>
            <li>你最喜欢什么颜色?</li>
       </template>
    </category>
```

And now when there is no valid match it will be one of the above

K

**Comment by ohoachuck** [comment]
I guess <random> tag was forgotten :
```xml
<category>
    <pattern>YDEFAULTRESPONSE</pattern>
    <template>
        </random>
            <li>你多大了?</li>
            <li>你的职业是?</li>
            <li>你最喜欢的电影是?</li>
            <li>你住哪呢?</li>
            <li>What color are your eyes?</li>
            <li>What color is your hair?</li>
            <li>你最喜欢什么颜色?</li>
        </random>
    </template>
</category>
```

**Comment by keiffster** [comment]
Yes, sorry, I typed the aiml in directly to Github console, apologies but looks like you got the right xml in the end

**Comment by keiffster** [comment]
New version pushed to master which now does what you need automatically

Webchat on start up will initially ask the question YINITIALQUESTION, if it has a grammar it will display the response, otherwise it will use the default initial question stored in config.yaml

No changes should be required, as long as you have one or both of the following defined in config.yaml

```yaml
bot:
    initial_question: Hi, how can I help you today?
    initial_question_srai: YINITIALQUESTION
```
