### ISSUE TITLE
Issue in calling python code

### ISSUE THREAD

**Issue by newdev7** [keiffster/program-y#12]
I'm calling the external API using the extension tag in the aiml file. I have created a new python file and pasted in the src/test/parser/template/graph folder. In that file, I created different classes and different functions inside that classes.

I am able to call the execute function present in one class in that python file using the extension tag in aiml. But not able to call other functions inside that class or other classes. Also it takes only one parameter. But I need to send two or more parameters from aiml to python.

For example.

```
class TestExtension(object):

    def execute(self, data):
        print(data)
        return "executed"

    def save(self, name):
        print(name)
        return "saved"

class SaveObject(object):

    def execute(self, name):
        print(name)
        return "saved"

```

To call this TestExtension class, I'm using the following code in aiml file.
```
<extension path="test.parser.template.graph.test_extension.TestExtension">
			<star/>
</extension>
```
If I call TestExtension class, it always call the execute function present inside the TestExtension class. But if I call SaveObject class, it doesn't return anything.

Could you please tell me how to call the other classes and other functions in aiml using that extension tag. Also tell how to send two or more parameters in the extension tag.

Thanks

**Comment by keiffster** [comment]
The way this is designed is that the execute() method is really a definition of an interface that a class should implement and as such it is the only method that the extension tag calls.

The extension tag doesn't seem to match the code. the extension would be looking for a python file located in src/test/parser/template/graph/test_parseSave and the file would be called SaveDetailsInParse.py

In this file, you would have a class defined as

class SaveDetailsInParse(object):
    def execute(self, name):
        print(name)
        return "saved"

You also need to ensure that you have a __init__.py file in the same directory as the parser is looking for a module and it will only find it if __init__.py is there

Hope this helps

**Comment by newdev7** [comment]
@keiffster There is no issues in calling the execute() method in the class. I thought of calling another method inside the class. Since the extension tag calls only the execute() method, we can't call any other method. Thanks for your reply.
