### ISSUE TITLE
when Dialog Generator tool would release ?

### ISSUE THREAD

**Issue by HCIS2020** [keiffster/program-y#121]
Issue tracker is **ONLY** used for reporting bugs. NO NEW FEATURE ACCEPTED! Use [stackoverflow](https://stackoverflow.com) for supporting issues.

## Steps to Reproduce

1.
2.
3.
4.

## Context (Environment)

* Version of Y-Bot:
* Version of Python: 
* Operating System ( inc Version ):

**Comment by keiffster** [comment]
I can release it now in a beta stage, it has everything for single flow conversations. Only thing missing is conditional flow which is a week or so away

**Comment by HCIS2020** [comment]
Could you send me a copy, I could test it for my conversation dialog.

**Comment by keiffster** [comment]
Pushed to master, I'll add documentation to the wiki over the next couple of days

There is a script in src/utils/botlfow that runs the current flight booking dialog

**Comment by keiffster** [comment]
Released as v1.8.0
