### ISSUE TITLE
Where do I place my py file for a dynamic set

### ISSUE THREAD

**Issue by pranavlal** [keiffster/program-y#124]
Hi,
I have created a dynamic set. Where do I place the *.py file? I have currently placed it in the following path.
/chatbot/cisomaster/src/cisomaster/dynamic/sets/*.*

**Comment by keiffster** [comment]
You own python files can go anywhere you like as long as they are on the PYTHONPATH

If they are not within the programy module path. Then just add your own source directory to the PYTHONPATH in the shell script

**Comment by pranavlal** [comment]
Hi,
Thanks. so, if I put the script in
/chatbot/cisomaster/src/cisomaster/dynamic/sets
should the entry in config.yaml be
            question: /chatbot.cisomaster.src.cisomaster.dynamic.sets.IsQuestion.isQuestion

Sorry if I am being dense

**Comment by keiffster** [comment]
Yes under dynamics: sets: section config add a new line with name and full module path

**Comment by pranavlal** [comment]
Got it thanks.
