### ISSUE TITLE
Extension not triggering

### ISSUE THREAD

**Issue by pranavlal** [keiffster/program-y#125]
Issue tracker is **ONLY** used for reporting bugs. NO NEW FEATURE ACCEPTED! Use [stackoverflow](https://stackoverflow.com) for supporting issues.

I have written an extension to determine if user input is a question or not. This extension is not triggering.  The <template> tag which I am using to trigger the extension is being called. I can see this using the <logging> tag on the console.
 Expected Behavior

If the user's input is a question, then the bot should go to wikipedia and try to find the answer. If it finds the answer, it should display that answer to the user. If it does not find the answer, then it should send an appropriate message. I have written this bit.
## Current Behavior

The bot does not validate the question. It jumps to the category which triggers if no user input matches.
## Possible Solution

I have written an extension to detect if user input is a question. It needs to work. 
## Steps to Reproduce

See the snippet of my AIML file. This is the section to handle input that the bot does not about.
<category>
<pattern>*</pattern>
<template>
<think><set name="topic">unknownq</set></think>
<srai>ASKQ <star></star></srai>

</template>
</category>
<topic name="unknownq">
<category>
<pattern>ASKQ *</pattern>
<template>
<logging>unknown input detected</logging>
        <srai>
            <extension path="programy.extensions.questiondetect.CheckIsQuestion.CheckIsQuestion">
                <star />
            </extension>
        </srai>
</template>
</category>
<category>
<pattern>question detected *</pattern>
<template>
<srai>ASKWIKIPEDIA <star></star></srai>  
</template>
</category>
<category>
    <pattern>ASKWIKIPEDIA *</pattern>
    <template>
        <srai>YASKWIKIPEDIA <star></star></srai>
    </template>
</category>

        <category>
            <pattern>YASKWIKIPEDIA *</pattern>
            <template>
        <sraix service="WIKIPEDIA"><star /></sraix>
            </template>
        </category>
        <category>
            <pattern>YEMPTY</pattern>
            <template>
<think><set name="topic"></set></think>
I do not know but will think about it
            </template>
        </category>
<category>
<pattern>*</pattern>
<template>
Please ask me a direct question about information security
<think><set name="topic"></set></think>

</template>
</category>
</topic>

I will append the extension I wrote.
## Context (Environment)

I am trying to detect if unknown user input is a statement or a question. If the user has entered a question, the bot should look up the answer on wikipedia. I may add other services such as duckdckgo in the future to this.

* Version of Y-Bot: Not applicable because I have created my own bot
* Version of Python: 3.5.2 
* Operating System ( inc Version ): Ubuntu 16.04 

## Possible Implementation

Here is the python code of the extension.
import logging
from programy.extensions.base import Extension
import nltk
import difflib
from nltk.tag import pos_tag, map_tag

class CheckIsQuestion(Extension):
    def isQuestion(self,q):
        text = nltk.word_tokenize(q)
        posTagged = pos_tag(text)
        simplifiedTags = [(word, map_tag('en-ptb', 'universal', tag)) for         word, tag in posTagged]
        onlytags=[]
        for lc in range(0,len(simplifiedTags)):
            onlytags.append(simplifiedTags[lc][1])
            logging.debug("computing done")
        sqp=[["adv","verb"],["pron","verb"],["verb","noun"]]
        qm=difflib.SequenceMatcher(None, str(onlytags)[1:].lower(), str(sqp).lower())
        r=qm.real_quick_ratio()*100
        if r>72:
            return True
        else:
            return False 

    def execute(self, bot, clientid, data):
        if logging.getLogger().isEnabledFor(logging.DEBUG):
            logging.debug("question detected")
        qs=self.isQuestion(data)
        result=""
        if qs==True:
            result="question found"
        else:
        result="question not found"

        return result

**Comment by keiffster** [comment]
What is the grammar you are trying to use the extension from ?

**Comment by pranavlal** [comment]
Hi Keith,

 

If by grammar you mean the AIML snippet where I am calling the extension, then here it is.

<category>

<pattern>ASKQ *</pattern>

<template>

<logging>unknown input detected</logging>

        <srai>

            <extension path="programy.extensions.questiondetect.CheckIsQuestion.CheckIsQuestion">

                <star />

            </extension>

        </srai>

</template>

</category>

**Comment by keiffster** [comment]
That’s good news, the log files are full of lots of useful info. You should also have a tail -f running when you are writing your bot.

Also worth looking at writing a unit test for each extension or dynamic so you know it works under all test conditions before calling it from your aiml files
