### ISSUE TITLE
BUG feedback for botflow.py

### ISSUE THREAD

**Issue by HCIS2020** [keiffster/program-y#128]
LINE 237:

should be 

        aiml_file.write('\t\t\t\t<srai>EXIT %s</srai>\n' % topic_name)

instead of 

        aiml_file.write('\t\t\t\t<srai>EXIT FLIGHTBOOK</srai>\n')

Please fix it.

**Comment by keiffster** [comment]
Thanks, fixed it and will push shortly,

**Comment by HCIS2020** [comment]
Another problem is: when you write AIML file, it should be encoding="utf-8".
But when program read content from CVS file, the content of CVS file could be another encoding, such gbk or else.
So when program read content from CVS, it should convert content encoding to utf-8, and write AIML file with encoding="utf-8"

**Comment by keiffster** [comment]
Both issues resolved and will be released in 1.9 which is going through final testing now

**Comment by keiffster** [comment]
Release in 1.9
