### ISSUE TITLE
Improve performance through enhance regular expression handling

### ISSUE THREAD

**Issue by tomliau33** [keiffster/program-y#129]
Hi,
Since I found that my computer is a little slow to execute program-y, so I modify the code to improve performance to process messages.
My modification is as below:

https://github.com/tomliau33/program-y/pull/1

I'll be happy if it can be merged to program-y.
Thank you!

**Comment by keiffster** [comment]
Please please create a pull request and I'll check and merge. I am just finishing the testing on 1.9 release and this should go in

Alternatively, I can pull from your repo

**Comment by keiffster** [comment]
BTW 1.9 contains your Tokenizer, I've modified it slightly so that there is only a single instance which is now a configurable property of the Brain. This reduced the duplication of specifying the tokenizer twice for brain and bot, but also removed the dependency on a global variable

**Comment by tomliau33** [comment]
I had create a pull request - https://github.com/keiffster/program-y/pull/131
Please help to check it.
Thank you!

**Comment by keiffster** [comment]
This has been merged and unit tests fixed ;-)
Now going through final testing of the entire 1.9 release but have seen some great speed increases, thanks very much

**Comment by keiffster** [comment]
Release in 1.9
