### ISSUE TITLE
<denormalize> tag is not working

### ISSUE THREAD

**Issue by newdev7** [keiffster/program-y#13]
If the user gives 'say abc.com', this aiml is replying 'Abc dot com'. I tried to use the denormalize tag. 

I checked in the config folder. The denormal.txt file is available and inside that file `" dot com ",".com"` is also there.
I'm using the denormalize tag like this.

```
<category><pattern>SAY *</pattern>
<template><denormalize><star/></denormalize></template>
</category>
```
Still it is replying 'Abc dot com' only. How to use the denormalize tag in this aiml?
Thanks.

**Comment by keiffster** [comment]
Thanks, let me check and get back to you

**Comment by newdev7** [comment]
Hey @keiffster I think I found where the issue is. While we sending the message to bot, it is converting all the characters to uppercase. So in the denormal.txt file, if we add uppercase also like " DOT COM ",".com" then it returns correctly as 'Abc.com'

**Comment by keiffster** [comment]
The normalise and demormalise code use a regex expression, I can probably make it case independent by use a better regex. I can see exactly where the problem is. The code auto generates a view variants of the regex to map various combinations, I just need better code generation in this area

**Comment by newdev7** [comment]
Let me know when you fix this issue. I'll try to test add inform you if I find any other issue. Thanks

**Comment by keiffster** [comment]
Check out the new release 0.5.0 which has a rewritten pattern matching parser a few fixes which I think might fix your denormalise issue

**Comment by keiffster** [comment]
There is a new test in code base for 0.5.0 which fixes this

program-y/src/test/aiml_tests/denormalize_tests/test_denormalize_aiml.py

Check out the test and associate aiml for your reference
