### ISSUE TITLE
Redis conversation cache performance and conflict avoidance

### ISSUE THREAD

**Issue by creatorrr** [keiffster/program-y#135]
Some thoughts on the new redis backend implementation for caching conversations:
 - Should use a prefix for storing keys like `program_y:sessions:{client_id}`, helps avoid collisions and you could then delete all keys using a `scan_iter("program_y:sessions:*)` call
 - Might also be a good idea to use a `set` to keep track of `client_id`s. That way deleting all keys can be a single `del` call which would be significantly faster for larger hashes.

Happy to make a PR if you like these ideas.

**Comment by keiffster** [comment]
Please feel free to submit pr. always happy to have contributions
