### ISSUE TITLE
bug in flask rest client

### ISSUE THREAD

**Issue by sherryt400** [keiffster/program-y#138]
Flask REST Client stops responding after sometime. I am experiencing this issue on windows as well as on ubuntu 16 server.
Thanks

**Comment by keiffster** [comment]
Anything reported in the log files

I have program-y running on flask fronted by nginx on servus.ai

It’s been up for 6 weeks with no problems

If you can provide anything jn the logs I can debug from there

K

**Comment by keiffster** [comment]
Did you manage to see anything in your log files ?

**Comment by sherryt400** [comment]
Sorry @keiffster i was busy with my job. Its working fine so far. I think it was memory problem. I didn't find anything in logs. It happened once before on my Laptop so when i checked it was consuming a lot of memory.
