### ISSUE TITLE
ProgramY Version 2.0

### ISSUE THREAD

**Issue by keiffster** [keiffster/program-y#139]
Over the next 2-3 weeks, I intend to start the release process of v2.0 of Program-Y. This has been a number of weeks in development, mainly around refactoring for future requirements. The biggest change is the support for each client can have multiple bots and each bot can have multiple brains.

Multiple Bots would allow AIML and Non AIML grammars to exist side by side, or even AIML and Machine Learning engines like Rasa Core to interface with each other

Multiple brains would allow the breaking up of grammars into discrete elements, useful for multi langauge and also extensions and services.

There are a number of minor breaking changes, but I'll document these ahead of the release

K

**Comment by ideasean** [comment]
Looking forward to it!

**Comment by fenixchen** [comment]
fantastic, looking forward.

**Comment by ohoachuck** [comment]
Indeed plan for release v2 is just fantastic !
The project is fantastic!

O.

**Comment by keiffster** [comment]
Thanks guys, just an update on the future. I am currently in the process of taking up the position as Chair of AIML Specification group of the AIML Foundation, this is a not for profit org that we are creating to help define and standardise AIML and then start publishing new features

Contributors include Dr Richard Wallace the inventor of AIML, Steve Worswick, the creator of Mitsuki, Laura Kunze CEO of Pandora bots and other ( soon to be announced ) key figures in AIML development.

Lots of very exciting news to come

**Comment by abcortes** [comment]
That is an exciting news to everyone. Congratulations!

**Comment by creatorrr** [comment]
Congrats!

**Comment by idrismunir** [comment]
Congratulations

**Comment by ohoachuck** [comment]
I have missed this info/news 12 days ago!
Congratulations an good move. AIML is already so powerful. From far it's look old fashioned, but it's power could be so surprising. I believe It just need an eco-system around it to leverage it's potential. Program-y is great foundation to build this eco-system. U being pro-active for AIML specification is even better.
I'm happy to be aware of this at it's early stage of development as I believe in great future for this project. Really!

O.
