### ISSUE TITLE
oob issue

### ISSUE THREAD

**Issue by fenixchen** [keiffster/program-y#142]
Thanks for the impressive AIML engine, I try to put it in my favorite project for interest and get more pleasure.

I just find a oob limitation, which is result of oob can only use for response. I cannot use it for condition or pattern matching. here is my example:

I implement a  InfoOutOfBandProcessor class from OutOfBandProcessor, it should return correct surname if input is correct, otherwise it will return 'INVALID'. I want to use this result for condition, and it seems it cannot work. The result is always show "input correct".

Could you give a hand please? Thanks a lot.

class InfoOutOfBandProcessor(OutOfBandProcessor):

    def __init__(self):
        OutOfBandProcessor.__init__(self)
        self._result = "INVALID"
		
    
    def parse_oob_xml(self, oob: ET.Element):
        if oob.text is not None:
            if 'type' not in oob.attrib:
                return False

            type = oob.attrib['type']
            if type == "SURNAME":
				if len(oob.text) < 2:					
					self._result = 'INVALID'
				else:
					self._result = oob.text.split(' ')[1]
                return True
        return False

    def execute_oob_command(self, bot, clientid):
        return self._result

<?xml version="1.0" encoding="UTF-8" ?>
<aiml>
	<category>
		<pattern>INIT</pattern>
		<template>
			<srai>ASK SURNAME</srai>
		</template>
	</category>	

	<category>
		<pattern>ASK SURNAME</pattern>
		<template>
			Your surname?
		</template>
	</category>

	<category>
		<pattern>*</pattern>
		<that>Your surname?</that>
		<template>
			<think>
				<set name="SURNAME">
					<oob>
						<info type="GET_SURNAME">
							<star/>
						</info>
					</oob>
				</set>		
			</think>
			<condition>
				<li name="SURNAME" value="INVALID">Input wrong</li>
				<li>Input correct<get name="SURNAME"/>
				</li>
			</condition>
		</template>
	</category>

</aiml>

Issue tracker is **ONLY** used for reporting bugs. NO NEW FEATURE ACCEPTED! Use [stackoverflow](https://stackoverflow.com) for supporting issues.

## Steps to Reproduce

1.
2.
3.
4.

## Context (Environment)

* Version of Y-Bot:
* Version of Python: 
* Operating System ( inc Version ):

**Comment by keiffster** [comment]
There are couple of issues to look at first

1) You have code as follows

> type = oob.attrib['type']
>        if type == "SURNAME":
But your AIML is

> <info type="GET_SURNAME">

2) I’d like to understand a little more why you are using a OOB processor to parse the surname. OOB are processed right at the end of the template execution chain and not as part of the parsing of the AIML

I would look at using an Extension instead, so your <think> element would be more

>                <think>
>                        <set name="SURNAME">
>                               <extension path=“mymodules.extension.ParseSurname”><star /></extension
>               </set>
>                </think>

And you extension would be

class ParseSurname(object):

   def execute(self, context, data):
       if len(data) < 2:


                              self._result = 'INVALID'

                      else:

                              self._result = data..split(' ')[1]




Keith Sterling
E: keith@keithsterling.com
M: +44 (0) 7771 597 630

**Comment by fenixchen** [comment]
Thanks for your reply, Extension can work for my purpose.
