### ISSUE TITLE
Restful client Documentation might not be updated

### ISSUE THREAD

**Issue by ohoachuck** [keiffster/program-y#143]
Documentation might not be updated for [Restful client](https://github.com/keiffster/program-y/wiki/REST-Client).

## Expected Behavior
Succesfuly use REST API on : 
```http://0.0.0.0:8989/api/v1.0/ask?question=my+question&sessionid=123456789```

## Current Behavior
Error 404

## Possible Solution
Document might be updated as source code show default called url might  rather be :
```http://0.0.0.0:8989/api/rest/v1.0/ask?question=my+question&sessionid=123456789```

In addition, looking at the logs, I see the following error:
``` ERROR   - [flask] - 'userid' missing from request```

I guess params might be _question_ and _userid_ (and not _sessionid_ anymore) ?

O.

**Comment by keiffster** [comment]
sessionid has changed to userid iin v2.0, documentation will be updated over the course of the next few days

URL is now /api/rest/v1.0/ask as part of aligning all REST client urls, e.g

/api/rest/v1.0/ask
/api/facebook/v1.0/ask
/api/kik/v1.0/ask
/api/line/v1.0/ask
/api/twilio/v1.0/ask

**Comment by ohoachuck** [comment]
ok, cool.

**Comment by keiffster** [comment]
Documentation now updated on Wiki
