### ISSUE TITLE
how can i build my own chatbot?

### ISSUE THREAD

**Issue by shisi2015** [keiffster/program-y#146]
Issue tracker is **ONLY** used for reporting bugs. NO NEW FEATURE ACCEPTED! Use [stackoverflow](https://stackoverflow.com) for supporting issues.

## Steps to Reproduce

1.
2.
3.
4.

## Context (Environment)

* Version of Y-Bot:
* Version of Python: 
* Operating System ( inc Version ):

**Comment by keiffster** [comment]
Could you be a little more specific ? Have you read the instructions on the wiki ? What is it you want to build ?
