### ISSUE TITLE
AttributeError: 'Brain' object has no attribute 'clientid'

### ISSUE THREAD

**Issue by maxjread** [keiffster/program-y#149]
If I run bots\y-bot\y-bot.cmd, the code bombs out:
  File "D:\python\program-y-master\program-y-master\src\programy\brain.py", line 260, in dump_brain_tree
    self.clientid,
AttributeError: 'Brain' object has no attribute 'clientid'

I can run rosie.cmd if I comment out line 260 in brain.py ( self.clientid,) but then I can't run y-bot.
Keep up the good work, BTW!

**Comment by keiffster** [comment]
Fixed and pushed to master
Apologies, it was a minor mistake in the new refactoring that I forgot to test the edge case. 
Anyway it made me refactor that area to  make it more efficient and also move dumping a brain to xml to an admin extension which feels cleaner
