### ISSUE TITLE
Error after try 'python -m programy.chatbot'

### ISSUE THREAD

**Issue by greecehalf** [keiffster/program-y#152]
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files (x86)\Python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\programy\chatbot.py", line 3, in <module>
    from programy.clients.events.console.client import ConsoleBotClient
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\programy\clients\events\console\client.py", line 18, in <module>
    from programy.utils.logging.ylogger import YLogger
ModuleNotFoundError: No module named 'programy.utils.logging'

**Comment by keiffster** [comment]
New version pushed to PyPi, looks like the install script didnt like my versioning, 2.0.1 has been uploaded and tested within a virutal environment

**Comment by greecehalf** [comment]
Hello Keith,

Could you tell me where I can download the source code to realise the amazing new functions of AIML 2.0 in Python. Because I want to learn how these functions implement by using Python. Besides, due to Chinese is a totally different language from English, I think I may make some changes to the source code. I let you know if I do so. Thank you very much!
Looking forward to your reply.



Sincerely,
Tianren Wang

发件人: Keith Sterling [mailto:notifications@github.com]
发送时间: 2018年4月20日 15:26
收件人: keiffster/program-y <program-y@noreply.github.com>
抄送: #WANG <WANG1122@e.ntu.edu.sg>; Author <author@noreply.github.com>
主题: Re: [keiffster/program-y] Error after try 'python -m programy.chatbot' (#152)


New version pushed to PyPi, looks like the install script didnt like my versioning, 2.0.1 has been uploaded and tested within a virutal environment

**Comment by keiffster** [comment]
Just clone or download the code from the main GitHub page for program-y

https://github.com/keiffster/program-y

On the the website you’ll see a button in the right hand side to clone the repo

K

**Comment by greecehalf** [comment]
Dear Keith Sterling,

Thank you for your help. But here I meet another question. Could you tell me which .py file whose function is splitting the Chinese character. I made some change to splitchinese.py but when I was testing nothing different happened. I want to separate Chinses corpus based on the keywords I set. Because now I have to input Chinese like this ”租金 多少钱”, if the pattern is “租金 ^”(租金 is the keyword). I really want the programs can pre-separate the keywords in the sentences I input before which are used to match the patterns.

Looking forward to your reply.

Sincerely,
Tianren Wang


发件人: Keith Sterling [mailto:notifications@github.com]
发送时间: 2018年4月23日 13:31
收件人: keiffster/program-y <program-y@noreply.github.com>
抄送: #WANG <WANG1122@e.ntu.edu.sg>; Author <author@noreply.github.com>
主题: Re: [keiffster/program-y] Error after try 'python -m programy.chatbot' (#152)


Just clone or download the code from the main GitHub page for program-y

https://github.com/keiffster/program-y

On the the website you’ll see a button in the right hand side to clone the repo

K

**Comment by keiffster** [comment]
The code for splitting the Chinese text is in  

You need to configure a different tokenizer through config in the brain section

```yaml
brain:
    tokenizer:
        classname: programy.utils.language.chinese.ChineseLanguage
```

**Comment by greecehalf** [comment]
Thank you, Keith. Your reply is really helpful.
