### ISSUE TITLE
Allow other env variables in config.yaml

### ISSUE THREAD

**Issue by creatorrr** [keiffster/program-y#156]
It might be useful to allow env vars other than BOT_ROOT like PORT, REDIS_URL etc in config.yaml

**Comment by ideasean** [comment]
Just a few thoughts - 

We use config.yaml for non-environment specific configuration, since this file is kept in a git repo and pushed without modification between dev, test, preprod and prod environments. 

We use license.keys (renamed to bot.keys) to store any environment specific configuration. This includes:

- URLS for interfacing REST APIs and systems since these vary between test and prod environments
- account names (but not passwords - these are in a credential manager)
- flags to indicate if this environment is TEST or PROD
- email addresses as relevant for TEST vs PROD

The *.keys filespec is in .gitignore, and so stays unchanged by git pulls in each environment. 

This allows us to quite quick migrations of changes between environments. 

I am sure this could be refined with more engineering thought :-)

Cheers

Sean

**Comment by keiffster** [comment]
Hi all, definitely something I have thought about but could lead to a very long command line. 

I could look at having a env.yaml file which is loaded ahead of config.yaml and would contain all environment specific substitutions. Would this work ?

I’m in the process of separation out all bots into their own GitHub repos to provide better support for pypi and cut down the size of pip install. Following that the industry specific extensions will follow. Both for pypi support and also to stop conflicting grammars. “What is my balance” means different things for banking, energy and telcos

I’ll take a look once this has all settled down

**Comment by ideasean** [comment]
Sounds good. One of the things that works for us with license.keys is that new parameters can be added without having to add the additional class code needed in config.yaml. That does however result in long flat list of vars without any structure/grouping.

Perhaps if there was a way to add "extra vars" to yaml configuration which could be referenced by config("extravar") in code?

**Comment by creatorrr** [comment]
@ideasean I was thinking of something very similar as well. Maybe we can have a section in the config.yaml file called *vars* which declares the environment variables and their default values being used in the file. What do you think?

**Comment by ideasean** [comment]
For "true" environment vars in the shell, this is probably better left outside the Program-Y yaml. For bot configurations that vary by environment, then either what you suggest or Keith suggests could work. In any case, its good if Keith provides a basic mechanism for managing environment specific config but for more complex CI/CD workflows we should probably use more dedicated tools to manage such configurations.  Its more important to ensure that relevant config is exposed for configuration where needed.

**Comment by keiffster** [comment]
So just started to take a look at this, currently, the only real environment variable is $BOT_ROOT which is defined by the command line arg --bot_root, 

I was thinking adding an optional command line arg --env_args which would point to a config file which you could then include as many env vars as you wanted and they would be replaced inline in the associated config file as follows

```bash
python3 -m programy.clients.events.console.client --env_vars ./env_vars.txt --config ./config.yaml --cformat yaml --logging ./logging.yaml
```
Contents of env_vars.txt
```ini
$BOT_ROOT=.
$PROD_URL=http://123.123.45.67
$PROD_PORT=9080
$LICENSE_KEYS=./prod/license.keys
```
Then in config.yaml
```yaml
console:
  bot:  bot
  prompt: ">>>"
  license_keys: $LICENSE_KEYS

brain:
    services:
        REST:
            classname: programy.services.rest.GenericRESTService
            method: GET
            host: $PROD_HOST
            port: $PROD_PORT
```

**Comment by ideasean** [comment]
On the one hand I like yaml as it gives more structure, but then I know some CI/CD tools are not natively yaml aware. So this gives best of both worlds I think.

It would also allow us to also store environment config info for all environments in individual text files in git and just vary the command line based on machine_name--envt_name.txt for example.

Works for me.

**Comment by keiffster** [comment]
Add to 3.x backlog
