### ISSUE TITLE
Errors when running alice2 chatbot

### ISSUE THREAD

**Issue by GoldenSimba97** [keiffster/program-y#158]
Hi, 
When trying to run the alice2.sh file I suddenly get 26 errors, while last week and even today it still worked just fine. 

The errors I received are the following:
WARNING:26 errors detected
['2018-04-23 18:58:54', '<id> node should not contains child text, use <id /> or <id></id> only', './aiml/contactfunctions.aiml', '38', '40']
['2018-04-23 18:58:54', '<id> node should not contains child text, use <id /> or <id></id> only', './aiml/contactfunctions.aiml', '47', '49']
['2018-04-23 18:58:55', 'Name not found in map', './aiml/oob.aiml', '79', '81']
['2018-04-23 18:58:55', 'Name not found in map', './aiml/oob.aiml', '82', '84']
['2018-04-23 18:58:55', 'Name not found in map', './aiml/oob.aiml', '85', '87']
['2018-04-23 18:58:55', 'Name not found in map', './aiml/oob.aiml', '88', '90']
['2018-04-23 18:58:55', 'Name not found in map', './aiml/oob.aiml', '91', '93']
['2018-04-23 18:58:55', 'Name not found in map', './aiml/oob.aiml', '94', '96']
['2018-04-23 18:58:55', 'Name not found in map', './aiml/oob.aiml', '97', '99']
['2018-04-23 18:58:55', 'Name not found in map', './aiml/oob.aiml', '100', '102']
['2018-04-23 18:58:55', 'Name not found in map', './aiml/oob.aiml', '103', '105']
['2018-04-23 18:58:55', 'Name not found in map', './aiml/oob.aiml', '106', '108']
['2018-04-23 18:58:55', 'Name not found in map', './aiml/oob.aiml', '115', '117']
['2018-04-23 18:58:55', 'Name not found in map', './aiml/oob.aiml', '145', '147']
['2018-04-23 18:58:55', 'Unsupported random child tag: search', './aiml/personality.aiml', '1673', '1677']
['2018-04-23 18:58:56', 'SRAIX node, service attribute missing !', './aiml/sraix.aiml', '1821', '1823']
['2018-04-23 18:58:56', 'SRAIX node, service attribute missing !', './aiml/sraix_combine.aiml', '19', '21']
['2018-04-23 18:58:56', 'SRAIX node, service attribute missing !', './aiml/sraix_combine.aiml', '22', '24']
['2018-04-23 18:58:56', 'SRAIX node, service attribute missing !', './aiml/sraix_combine.aiml', '25', '27']
['2018-04-23 18:58:56', 'SRAIX node, service attribute missing !', './aiml/sraix_combine.aiml', '28', '30']
['2018-04-23 18:58:56', 'SRAIX node, service attribute missing !', './aiml/sraix_combine.aiml', '31', '38']
['2018-04-23 18:58:56', 'Unsupported random child tag: eval', './aiml/train.aiml', '280', '290']
['2018-04-23 18:58:56', '<addtriple> node missing object attribue/element', './aiml/triple.aiml', '434', '462']
['2018-04-23 18:58:56', 'SRAIX node, service attribute missing !', './aiml/triple.aiml', '3057', '3137']
['2018-04-23 18:58:56', 'SRAIX node, service attribute missing !', './aiml/utilities.aiml', '33', '46']
['2018-04-23 18:58:56', 'Unsupported random child tag: eval', './aiml/utilities.aiml', '181', '202']
WARNING: 12 duplicated grammars detected
['2018-04-23 18:58:55', 'Dupicate grammar tree found [TRANSCRIPT]', './aiml/oob.aiml', '19', '23']
['2018-04-23 18:58:56', 'Dupicate grammar tree found [*]', './aiml/star.aiml', '1803', '1816']
['2018-04-23 18:58:56', 'Dupicate grammar tree found [* IS MY *]', './aiml/star.aiml', '3832', '3864']
['2018-04-23 18:58:56', 'Dupicate grammar tree found [*]', './aiml/that.aiml', '59', '61']
['2018-04-23 18:58:56', 'Dupicate grammar tree found [*]', './aiml/that.aiml', '65', '67']
['2018-04-23 18:58:56', 'Dupicate grammar tree found [*]', './aiml/that.aiml', '83', '85']
['2018-04-23 18:58:56', 'Dupicate grammar tree found [*]', './aiml/that.aiml', '98', '100']
['2018-04-23 18:58:56', 'Dupicate grammar tree found [* IS AN *]', './aiml/train.aiml', '994', '1017']
['2018-04-23 18:58:56', 'Dupicate grammar tree found [* IS A *]', './aiml/train.aiml', '1035', '1058']
['2018-04-23 18:58:56', 'Dupicate grammar tree found [* IS THE *]', './aiml/train.aiml', '1059', '1082']
['2018-04-23 18:58:56', 'Dupicate grammar tree found [* IS NOT *]', './aiml/train.aiml', '1191', '1214']
['2018-04-23 18:58:56', 'Dupicate grammar tree found [*]', './aiml/udc.aiml', '19', '31']

I have looked at the files that would seem to have errors, but I don't find anything to really be amiss. 

I also pulled the latest code from the Github repository, because I first thought that maybe I had changed something in the Python code to cause the errors, but even after pulling the latest code from MASTER I still have these errors. 

I have absolutely no idea what could cause these errors, so I hope someone can help me. The Alice2 chatbot still seems to work, even with these errors, but I would still like to know what caused them, so I can fix it.

Thanks!

**Comment by keiffster** [comment]
I'm taking a look now, seems to be caused by the refactoring to its own repo. Good news is that I can reproduce it so shouldn't take long to understand the issue

**Comment by GoldenSimba97** [comment]
Thank you very much for your quick reply. I have commented out those 2 lines and it works like a charm again. I will check out the Alice 2 repo.
