### ISSUE TITLE
sanic.exceptions.NotFound: Requested URL /api/v1.0/ask not found

### ISSUE THREAD

**Issue by creatorrr** [keiffster/program-y#159]
REST service returns 404 on `GET /api/v1.0/ask`. The [documentation](https://github.com/keiffster/program-y/blob/master/src/programy/clients/restful/sanic/client.py#L19) and the [implementation](https://github.com/keiffster/program-y/blob/master/src/programy/clients/restful/sanic/client.py#L107) don't seem to match. Happy to open a PR / wiki update request. :)

**Comment by keiffster** [comment]
Yes, during the refactoring it changed to 

http://localhost:8989/api/rest/v1.0/ask?question=hello+world&userid=1234567890

I'll update the documentation shortly

**Comment by impulsecorp** [comment]
I don't think you ever updated this. I spent many hours trying to get sanic to work until I found this page.
