### ISSUE TITLE
<that> not working 

### ISSUE THREAD

**Issue by newdev7** [keiffster/program-y#16]
Hi,

I'm trying to use `<that>` tag  for my project and it doesn't seem to work other than in the coffee.aiml in the tutorial.sh .

Can you please guide me with the proper procedure to use `<that></that>`

**Comment by newdev7** [comment]
Hey, 

I tried the code for `<that>` tag. After checking the python code and aiml code for `<that>`, I fixed some of the issues related to this one.

1. In the `<template>` tag, the message is given in the lowercase. But in the `<that>` tag, the same messages are given in uppercase. So while sending for parsing, I changed the messages to uppercase.
2. Some of the questions in the `<template>` tag ends with '?'. But in the `<that>`, the '?' is missing for those messages. I added '?' in `<that>` tag.

After changing this two, I'm able to get answer for some `<that>` tags.

But one more issue is there.
In the that.aiml file, we are using '* YEARS' for one question. Also in other aiml file, there is one category with `<pattern>` as '* YEARS'. Here the conflict occurs. It has to return the message present in the that.aiml but it returned the answer in the other aiml file pattern.

 Like this if any of the messages with * is available both in the `<that>` tag and other `<category>` tag, then it returns the answer in the other `<category>` tag instead of `<that>` tag.

Can you please tell me how to fix this issue.

**Comment by keiffster** [comment]
Just back from an overseas biz trip, let me write some tests and see what is happening

**Comment by newdev7** [comment]
@keiffster welcome back mate. A little change in the issue. There is no issue if the same pattern available in `<that>` tag and other `<category>` tag. It returned the message from `<that>` tag only. The issue is different here.

In the that.aiml file, we are using `'* YEARS'` for one question. In another aiml file, there is one category with `<pattern>` as `'3 *'`. Here the issue occurs. If I send '3 years', it responded with the `<template>` present in the `'3 *' <pattern>` instead of `'* YEARS'`.

**Comment by keiffster** [comment]
Check out the new release 0.5.0 which has a rewritten pattern matching parser which is much better at topic and that handling

**Comment by newdev7** [comment]
Hi @keiffster I tested the latest version. Still you didn't add '?' symbol at the end for some of the <that> tag. So it is returning the wrong answer only. 

For my issue, I tested with the same message. Now it is returning the message from that tag. But when I checked the aiml files it seems like you removed the other category in the aiml file. 

Can't we use both the categories and get the answer from that tag?

**Comment by keiffster** [comment]
Hey

I’ve reverted the test code back to your original, I left it commented out by mistake while I was testing, and wanted to try a couple of combinations to see what is happening, so yes you can use both variants

I’ve corrected it and check in the reverted version

I’m not sure what you mean by the ?, can you give me an example

K

**Comment by newdev7** [comment]
Hey @keiffster check the following flow
```
Hi, how can i help you today?
>>> I'm married
How long have you been married ?
>>> 3 years
Just three?
>>> 
```

In the that.aiml, we have one category with pattern `* YEARS` for `<that>` tag `How long have you been married ?`. It has the template `Congratulations!`. So if the user gives 3 years for the previous question like in the sample, it has to return `Congratulations!`. But it is returning `Just three?`. Because in other aiml file, we have one category with pattern `3 *` and it has the template `Just three?`. Instead of returning `Congratulations!`, it is returning `Just three?`. I have tested in the latest version also. It is returning like this only.

And the second one is about ? symbol at the end of the text. Check the following example.
```
Hi, how can i help you today?
>>> zzz
Are you tired?
>>> yes
Hmmmm.
>>> 
```

In the category for pattern `zzz`, it has the template `Are you tired?`. But in the that.aiml file, in the category with pattern `yes` for `<that>` tag `Are you tired`, it has template `Maybe you should get some rest. I will still be here later.`. But it is returning different answer. Because ? is missing in the `<that>` tag. If you add ? at the end in `<that>` tag, then it is returning correct message.

**Comment by keiffster** [comment]
In the first instance I think its all down to precedence, * is always treat as lower priority than actual word. For AIML 2 the priority is

$   -  Does an exact word match
#   -  Zero or more
_       -  1 or more
word  -  Any word, set or bot
^      -  Zero or more
*   -  1 or more

So you see that * is the last thing that gets matched, change the pattern to _ YEARS and it will match first, and then leave 3 * to match anything else

In the second instance could you send me an example grammar you are using and I will look at it in detail

K

**Comment by keiffster** [comment]
Just re-read your email and I think I understand, the parser doesn’t remove any punctuation, and I think it probably does

I’ve just check old documentation for AIML 1 parsers written years ago and all of them remove all punctuation marks like ? and !

I’ll work out a way of adding a basic punctuation remover into he processing, and write some tests before releasing. Probably take a couple of days

K

**Comment by keiffster** [comment]
Ok, so I have worked out the issue with ? at the end of <that>, the fix is more generic, in that I remove all punctuation from <that> which makes the handling much cleaner

New release just gone to git hub

K

**Comment by newdev7** [comment]
Hi @keiffster 

In the AIML 2.0 specification, they mentioned that the removal of punctuation is not required. If you remove the punctuation. then you have to remove it in `<that>` tag also. So we have to remove all punctuations like `'.'`, `','`, `'?'`, `'!'`, etc., in `<that>` tag.
