### ISSUE TITLE
Version 2.3 Prerelease Info

### ISSUE THREAD

**Issue by keiffster** [keiffster/program-y#161]
Version 2.3 is well underway and comes with 3 major updates
* Alexa Client
* Web Socket Client
* New Storage Engine
  * BY unifying all I/O, we are able to provide support for a wide variety of storage options including
    * SQL (MySQL, Aurora, Postgres, SQL Server etc )
    * NoSQL (Redis, Mongo)
    * File System
    * Logger

**Comment by Olagsfark** [comment]
You're doing such a great Job Sir! 
Watching closely, cant wait to have I/O in sqlite.

**Comment by keiffster** [comment]
Anything is possible within my capability of Python :-)

Do you have any ideas that you would like to see

I’m in the middle of adding a much richer storage engine which ultimately leads to cloud enabling Programy for platforms such as AWS. Probably a couple more weeks and then finished but could fit in a couple of small enhancements to flowbot in that time

**Comment by ohoachuck** [comment]
Hey Keith,
Every time I check program-y I see you going really fast and almost ONLY by yourself. This is impressive. Really. In addition, this seems to be done with good Python programming patterns. I hope (for us not for you :) ) that you'll not get stollen from the OpenSource community for a big money company. You work already worth so much you probably would not imagine ...
Thank you again for this continuous quality effort.

**Comment by keiffster** [comment]
Thanks for your comments, Program-Y definitely takes up a lot of my spare time, but I would not change that, it's far too much fun so I doubt anything will change my involvement.

Once I get the storage engine completed I am going to take some time away for the mainstream development for a few weeks. I'll continue to support the platform and answer questions but will not be doing any major features.

**Comment by harmydiano** [comment]
sincerely, am highly amazed with what am seeing in the modifications of the aiml sets and what you've done so far, it's great.. keep up the good work

**Comment by keiffster** [comment]
Superceded by work on 3.0
