### ISSUE TITLE
That clause matching wildcard issue

### ISSUE THREAD

**Issue by fenixchen** [keiffster/program-y#162]
Issue tracker is **ONLY** used for reporting bugs. NO NEW FEATURE ACCEPTED! Use [stackoverflow](https://stackoverflow.com) for supporting issues.

That clause cannot match wildcard following by only one word, two words case is OK.

## Expected Behavior

That clause should be matched
## Current Behavior

that clause cannot be matched
## Possible Solution

I think the consume function may have some issue about the case
## Steps to Reproduce

Make a aiml file like this and run program-y

`<aiml>
    <category>
        <pattern>WELCOME</pattern>
        <template>aaa bbb ccc ddd</template>
    </category>
    <category>
        <pattern>*</pattern>
        <that>^ ddd</that>
        <template>matched</template>
    </category>
</aiml>`
Input any words cannot be matched.

If we add one word 'eee', it will be ok
`
<aiml>
    <category>
        <pattern>WELCOME</pattern>
        <template>aaa bbb ccc ddd eee</template>
    </category>
    <category>
        <pattern>*</pattern>
        <that>^ ddd eee</that>
        <template>matched</template>
    </category>
</aiml>
`
Two words is ok

## Context (Environment)

* Version of Y-Bot: 2.1.1
* Version of Python:  3.6
* Operating System ( inc Version ):  Windows 10

**Comment by keiffster** [comment]
Thanks for reporting the issue, I'll take a look shortly and get back to you

**Comment by keiffster** [comment]
I believe to be fixed now, just pushed an update to Master which fixes an issue in the THAT processing with wildcards

**Comment by fenixchen** [comment]
thanks for your response:-)

**Comment by keiffster** [comment]
Fixed
