### ISSUE TITLE
self-defined template tag might affect the content returned in console mode

### ISSUE THREAD

**Issue by utuxmt** [keiffster/program-y#164]
I ran a aiml file with script provided in y-bot.sh. The aiml file is as followed
![aiml](https://user-images.githubusercontent.com/39450395/43816503-b2f58536-9b07-11e8-9121-afe6a375f6e4.PNG)
The aiml file contains 2 self-defined template tags: 'myTag1' and 'myTag2'.
Then I test the aiml file with 3 patterns: 
`command1`, `command2`, and `command3`

## Expected Behavior
With the given pattern, the expected behavior is to return the whole block content in template tag respectively.

## Current Behavior
Only part of the block content is returned with the pattern `command1`,
However, with `command2` and `command3`, the whole block content is received. The result is as followed
![result](https://user-images.githubusercontent.com/39450395/43816818-41198334-9b09-11e8-9b58-d30db0031f04.PNG)

Looks like the relative position of the self-defined tag in aiml file might affect the content returned.

## Context (Environment)
Version of Y-Bot: just cloned from y-bot repo.
Version of Python: Python 3.6.5
OS: Ubuntu 18.04

Edited:
Things go normal if I run the aiml file with y-bot-sanic-rest.sh.

**Comment by keiffster** [comment]
This is now fixed in v3 and will ship shortly
