### ISSUE TITLE
Django2 integration

### ISSUE THREAD

**Issue by elcolie** [keiffster/program-y#166]
Do you have any plan to integrate your `program-y` to Django?
Since it has rich packages and default support on ORM like [chatterbot](https://github.com/gunthercox/ChatterBot/blob/a2ef197ef7138a9db6a2b247cf8b83668fe82c76/docs/index.rst)

**Comment by keiffster** [comment]
What integration did you have in mind. I typically use frameworks like flask and sanic for their rest capabilities, and could potentially add a third django client type but you could just as easily call out using rest to existing client


Keith

Keith Sterling
E: keith@keithsterling.com
M: +44 (0) 7771 597 630

**Comment by elcolie** [comment]
My integration in my mind is
I just `pip install programy`
And then I add `programy` to `INSTALLED_APPS` in the Django `settings.py`
After that I am ready to make the `template` and `training set` right away with `Django-admin`

**Comment by keiffster** [comment]
From what you are describing this should work, what errors are you getting

Pip install programy, installs the latest from PyPi, then its just a question of access from DJango, there is no additional support required in Programy. 

However I am guessing you want to call the client loop from your Django App, if this is the case then take a look at the console client which shows how to load AIML and enter a Q&A loop
