### ISSUE TITLE
kik 1.5.0 has requirement six==1.10.0, but you'll have six 1.11.0 which is incompatible.

### ISSUE THREAD

**Issue by elcolie** [keiffster/program-y#167]
During the installation `pip install programy`
Python 3.7.0
pip 18.0

```bash
kik 1.5.0 has requirement six==1.10.0, but you'll have six 1.11.0 which is incompatible.
```

Will it be a problem in the future?

**Comment by keiffster** [comment]
I don’t currently support python 3.7. That does not mean it won’t work I’ve just not got round to installing it and testing

Feel free to bump the version of kik in requirements.txt as I assume it will work as the new version of kik is just bug fixes

**Comment by elcolie** [comment]
Looking forward to seeing your release. I will leave this open and let you close when you are done.
During this time I will follow your reply by bumping up the version.

Thank you very much for your answer.

**Comment by keiffster** [comment]
Ver 3.x will support Python 3.7 and will have all dependency libraries raised to the latest versions

**Comment by elcolie** [comment]
Have you ever tried `pip-tools`?
It will manage your dependencies and let them up to date every time you generate a package.
