### ISSUE TITLE
Update on Version 3.0

### ISSUE THREAD

**Issue by keiffster** [keiffster/program-y#168]
I’ve spent the summer working on v3.0 release which is now close for a dev branch release.

Along with full support for Alexa ( and the. Google home in 3.1 soon afterwards ) the biggest update is a fundamental change to storage. You can continue to use files for all data but in 3.0 you can now store all you data in SQL databases and also MongoDb. I am seeing a 10x loading speed when using MariaDB and approx 4x loading speed with mongo

Hoping to enlist a few people to test as many sql databases :-)

**Comment by ohoachuck** [comment]
👍
O.

Envoyé de mon iPhone

**Comment by torrtuga** [comment]
Please tell me how to use this to write my own AIML chatbot. Earlier I used pip to install aiml but that was not having many functionalities.
So, how can I use this and install and run. As there is no information given about that in the Readme section.
I really need help on that.

**Comment by keiffster** [comment]
https://github.com/keiffster/program-y/wiki

**Comment by torrtuga** [comment]
@keiffster Thanks for the reply.
I went through the wiki, and what I can infer is that program y is the framework which does the AIML interpretations.

But I could not understand how I can use this after cloning the repo. As earlier I used pip install and I was able to write programs which understood AIML code.
But how can I install and make it working with my python I am not able to understand.

I am sorry for asking a silly question but I am not pro in python and am not able to figure it out .

**Comment by keiffster** [comment]
The v2.0 version ships with a very limitied version of the bot if you install from Pip, however if you follow the following link of the wiki you can choose a bot to install

https://github.com/keiffster/program-y/wiki/Bot-Installation

**Comment by torrtuga** [comment]
Hi sir,
Any suggestions on how I can solve the problem?

**Comment by keiffster** [comment]
You need to set PYTHONPATH=<your folder>\programy\src

**Comment by keiffster** [comment]
Dev ( e.g Alpha ) Version of 3.0 will be published to the Development branch this week

Documentation and more testing/fixing to follow

**Comment by keiffster** [comment]
Version 3 has been released to its own branch v3 and can be viewed/downloaded at

https://github.com/keiffster/program-y/tree/v3

However please be aware this is very much pre-release and full testing across all data sources and clients is just starting

**Comment by elcolie** [comment]
Do you plan to support `Postgres`?

**Comment by keiffster** [comment]
It’s supported in that the python library sqlalchemy supports it and I’ll be spinning up a docker image shortly with Postgres for testing, so in short yes

**Comment by elcolie** [comment]
I found that question and answer can be a cyclic graph. Have you ever plan for `Neo4j` graph database?
