### ISSUE TITLE
Failed to run `pip install -r requirements.txt`.

### ISSUE THREAD

**Issue by ororog** [keiffster/program-y#174]
## Expected Behavior
I can run `pip install -r requirements.txt` without errors.

## Current Behavior
It stops with errors below:
```
...
Collecting Flask-Ask==0.9.8 (from -r requirements.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/6a/f5/d4709ae94584a0b1541e9b52b2d25a8a1bdb6e2da9d6870f23fdd0523a30/Flask-Ask-0.9.8.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/46/xk08njxn7sd54dc3pf_kfp000000gn/T/pip-install-zso7iqtb/Flask-Ask/setup.py", line 8, in <module>
        from pip.req import parse_requirements
    ModuleNotFoundError: No module named 'pip.req'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/46/xk08njxn7sd54dc3pf_kfp000000gn/T/pip-install-zso7iqtb/Flask-Ask/
```

## Steps to Reproduce

1. create and move the working directory.
2. `python3 -m venv venv`
3. `source venv/bin/activate`
4. `git clone https://github.com/keiffster/program-y.git`
5. `cd program-y`
6. `pip install -r requirements.txt`

## Context (Environment)

* Version of Y-Bot: 6dc1929
* Version of Python: Python 3.7.0
* Operating System ( inc Version ): MacOS 10.13.6

**Comment by keiffster** [comment]
I’ve noticed a couple of errors running pip install on Ubuntu, just comment Flask-Ask out and it will work fine

It is only required for the Alexa client, and thats not fully published yet, so you loose nothing commenting it out

K

**Comment by keiffster** [comment]
Commented out Flask-Ask from requirements and push to master and 3.0.1 to PyPi
