### ISSUE TITLE
How to search RDF with the same subject and object to get mutliple results ?

### ISSUE THREAD

**Issue by chungyilinxrspace** [keiffster/program-y#175]
How to search RDF with the same subject and object to get mutliple results ?
## Expected Behavior

In my AIML , using the following query to search "ACTOR isa ?x"

```
<set var='result'>
    <select>
        <vars>?x</vars>
        <q>
             <subj>ACTOR</subj>
             <pred>isa</pred>
             <obj>?x</obj></q>
    </select>
</set>
<get var='result'/>
```
expect the results are :
```
[[["?x", "ISA"], ["?y", "Person"]], [["?x", "ISA"], ["?y", "Man"]]]
```

## Current Behavior

but  return 
```
[[["?x", "ISA"], ["?y", "Person"]]]
```
Thank you very much ~!

**Comment by keiffster** [comment]
RDF spec is none too clear, I had to reverse engineer the entire thing from scratch

What you have reported seems sensible and would probably be required, I'll work on a fix over the next few days and published asap

**Comment by chungyilinxrspace** [comment]
Thank you very much !
Have a nice day ~!

Keith Sterling <notifications@github.com> 於 2018年10月30日 週二 上午3:57寫道：

**Comment by keiffster** [comment]
This has now been fixed and all tests now passing. I've just pushed the fix to master. Enjoy !
