### ISSUE TITLE
 Version 3.1

### ISSUE THREAD

**Issue by keiffster** [keiffster/program-y#176]
I have some exciting news to announce regarding 3.1, it’s getting close to release and comes with 3 exciting features

1) Translation. You can now speak to it in any language supported by google translate and also have the answers in any language. This means you can keep your rules in English bur open your bot to a variety of language users

2) Sentiment. Each question asked has a sentiment score attached to it and the bot also keeps a running score for the whole conversation. Both values are available through runtime variables to be used to adjust your responses

3) Client account linking. You can now link accounts across all clients and therefore continue conversations. For example start on the web client, link Facebook and continue there and then link twitter and continue there then swap between all 3 at will preserving the entire conversation. This works across all 11 supported clients

Btw love to hear how you are using program-y. Looking to build some use cases to showcase where people are making it work

**Comment by ohoachuck** [comment]
This is impressive !

O.
Envoyé de mon iPhone

**Comment by keiffster** [comment]
Quick update. 

Translation is going well and now integration with google translate is complete just finishing off the AIML grammars. If you have an internet connection program-y will allow you to speak and by spoken to automatically in over 28 different languages.

Sentiment is done including grammar and examples for accessing sentence and conversation positivity and subjectivity scores

Account linking needs either an sql or mongo database so I am being up the documentation on how to use these instead of text files

Hopefully release to dev branch in the next week

**Comment by keiffster** [comment]
Correction, that would be 108 languages as defined in the following list https://cloud.google.com/translate/docs/languages

**Comment by ohoachuck** [comment]
👍

**Comment by keiffster** [comment]
I’m closing this one down, it’s out there in the wild and now focusing towards v4.0 which is more of a stabilisation release focusing on fully updated documentation, especially of the new features and unit test coverage which has dropped slightly. 4.x onwards will the focus on 2 things; integration of ML intent processing through tools such as rasa hq and the creation of a world class bit using all available programy features
