### ISSUE TITLE
Eval star not working in pattern without additional text

### ISSUE THREAD

**Issue by jljob** [keiffster/program-y#177]
Example file A (not working as expected):
`<?xml version="1.0" encoding="UTF-8"?>`
`<aiml version="2.0">`
`  <category>`
`    <pattern>WHEN I SAY * YOU SAY *</pattern>`
`    <template>`
`      Okay.  When you say <star index="1"/>, I will say <star index="2"/>`
`      <learn>`
`        <category>`
`          <pattern><eval><star index="1"/></eval></pattern>`
`          <template><eval><star index="2"/></eval></template>`
`        </category>`
`      </learn>`
`    </template>`
`  </category>`
`</aiml>`

Example file B (working as expected):
`<?xml version="1.0" encoding="UTF-8"?>`
`<aiml version="2.0">`
`  <category>`
`    <pattern>WHEN I SAY * YOU SAY *</pattern>`
`    <template>`
`      Okay.  When you say <star index="1"/>, I will say <star index="2"/>`
`      <learn>`
`        <category>`
`          <pattern>I SAID <eval><star index="1"/></eval></pattern>`
`          <template><eval><star index="2"/></eval></template>`
`        </category>`
`      </learn>`
`    </template>`
`  </category>`
`</aiml>`

## Expected Behavior
When using example A, one should be able to enter "When I say jump you say how high"
When the user subsequently enters "Jump"
The bot should reply "How high?"

## Current Behavior
When using example A, one is able to enter "When I say jump you say how high"
When the user subsequently enters "Jump"
The bot replies "Sorry, I don't have an answer for that!"

## Steps to Reproduce
1.  Create bot that uses example file A
2.  Enter "When I say jump you say how high"
3.  Enter "Jump"
4.  Bot replies "Sorry, I don't have an answer for that!"
5.  Create bot that uses example file B
6.  Enter "When I say jump you say how high"
7.  Enter "I said Jump"
8.  Bot replies "How high."

## Context (Environment)
I'm trying to use AIML 2.0 features to teach the bot new tricks while I chat.

* Version of Y-Bot: 3.03
* Version of Python: 3.6.6
* Operating System ( inc Version ): Linux Fedora 27 4.17.19-100.fc27.x86_64

The attribute tags aren't able to handle an `<eval><star/></eval>` without additional text.

## Detailed Description

I believe that attribute tags should be allowed to have a lone `<eval><star/></eval>` in them.  It seems that the parser has not yet taken this use case into account.  Once this is corrected, a test should be added to make sure the issue doesn't reappear.

**Comment by keiffster** [comment]
Thanks for the bug report, looks like there is a minor issue in the learn parsing logic, should get a fix to you in the next few days

**Comment by keiffster** [comment]
I am unable to replicate this in the current branch. I even added your example to the core y-bot grammar and it still worked

Are you able to send me a copy of you log file showing the grammar being processed ?

**Comment by jljob** [comment]
I have attached my log file.

**Comment by keiffster** [comment]
This is now working in current master. I have added your aiml and logic to extra tests in programytest/aiml_tests/learn_tests/jijob_eval.py. These tests now pass using the code you provided
