### ISSUE TITLE
Dollar Sign is not working properly

### ISSUE THREAD

**Issue by mao995** [keiffster/program-y#178]
## Detailed Description
Dollar sign is not working properly. For example let's take the following basic example

`<category>`
`  <pattern>HELLO ^ </pattern>`
`  <template>Hello there!</template>`
`</category>`

`<category>`
`  <pattern>HELLO $FRIEND</pattern>`
`  <template>Hello my friend!</template>`
`</category>`

## Expected Behavior
In order to call the max priority pattern, this example should have worked with every possible case variant of the word FRIEND like friend, FrIeNd, fRiEnD, since AIML is non case-sensitive.

## Current Behavior
The problem is that if i try using that, it only works with the case variant that i specified in the pattern, in the example before the user must write the word FRIEND fully capitalized, if the user writes friend, Friend, or any other case variant, the interpreter is not able to process it as max priority, but just returns the generic hello pattern. 

## Possible Solution
I strongly believe that the problem is in the interpreter, but i can't figure where the problem is.

## Steps to Reproduce
1. Initialize a new bot
2. Write an .aiml file containing the previous example
3. Execute the bot and try to write different case variants from FRIEND
4. The bot returns the generic response "Hello there!" instead of "Hello my friend!"

## Context (Environment)
* Version of Program-Y: 3.0 (latest release)
* Version of Python: 3.6.6
* Operating System ( inc Version ): Ubuntu 18.04

**Comment by keiffster** [comment]
Ok interresting, might be a case comparator issue or how the grammar is converted, should be an issue fix

**Comment by keiffster** [comment]
As expected I was not checking for case insensitivity in priority nodes, fixed and just pushed to master
