### ISSUE TITLE
How to configure different response - Set Matched, Not in Set

### ISSUE THREAD

**Issue by Koushik0890** [keiffster/program-y#179]
While set file can be used to point to a required response based on pattern, is there a way that we can configure a negation of the set files?

Say:
Matching with Set File - Yes
Not Matching with Set file - No
Other unmatched - Different response

I am using Alice Bot - Program Y Version 2.0 . Please let me know for any more details required.

**Comment by keiffster** [comment]
It’s a question of priorities l. Just as $ is evaluated first so sets are ahead of wild card and word matches. You can therefore have multiple patterns which are almost identical and allow priority pattern matching take care of it

E.g


I like $chips
I like <set name=“fast food”>
I like *

Will march in that order. So even if your set contains the word chips, the first pattern will match. Then anything in the set will match the second pattern and anything else matches the 3rd pattern

In terms of your question not matching the set file is the same as other unmatched. It’s a bit like set theory it either matches or it doesn’t 

Regards 

Keith
keith@keithsterling.com
07771 597630

**Comment by Koushik0890** [comment]
@Keith - Thank you. I have understood the priority and sets. And I have already implemented it.  What was my intention is that chips cannot suite in all the contexts. So for some well known contexts that it doesnt fit, I am thinking to use the same set file and unmatch the context.

Eg. Can we eat chips
<category><pattern><set>chips</set><pattern>
<template>You can eat chips</template>
</category>
Eg. Can we drink chips
<category><pattern>""Unmatch chips set""</pattern>
<template>No you cannot drink chips</template>
</category>

I think, we can do it in a complex way implementing topics, object attributes, etc.
Is there a direct way to unmatch the sets?
==============
This is a different query
Can you also help me understand how to mark priority on a <set> file?
Eg.
<category><pattern>$<set>places</set></pattern>
<template>xyz</template>
</category>

**Comment by keiffster** [comment]
The easiest way in this example is to have a set of all the things you can eat and all the things you can drink and then 2 patterns with * for everything else

Can we eat set=“fast food”
Can we eat *

Can we drink set=“beverages”
Can we drink *

There really is no other way to ask for “not in a set”

Regarding your second question can you explain what you mean by priority on a file. Do you mean the order in which it is loaded ? 

Regards 

Keith
keith@keithsterling.com
07771 597630

**Comment by keiffster** [comment]
That’s just something you cannot do in aiml, $ only works on single words


Regards 

Keith
keith@keithsterling.com
07771 597630

**Comment by Koushik0890** [comment]
Thanks for clarifying Keith.

Regards,
Koushik
