### ISSUE TITLE
<star/> issues

### ISSUE THREAD

**Issue by JustArchi** [keiffster/program-y#18]
This is a really weird behaviour.

`rosie_fixed` uses `* OR *` pattern with a random choice that outputs `<star/>` or `<star index="2"/>`.

Previously (commit e514b029f499ebcd29550fc228004d772c0c9422) it worked like this:

![image](https://cloud.githubusercontent.com/assets/1069029/23877753/1b74ebd6-0844-11e7-9c2e-bba92184b872.png)

As you can see, `<star/>` was broken but `<star index="2"/>` worked just fine.

Then with current release it looks like that:

![image](https://cloud.githubusercontent.com/assets/1069029/23877555/1f29313e-0843-11e7-9128-fce83c9b3fd8.png)

Normally I'd say "okay, so now star with index is broken while star without index works", but that's not the case either, as we use pattern like this:

```
	<category>
		<pattern>FAKUBALL KICK * OR *</pattern>
		<template>
			<random>
				<li>Faku: Kick <denormalize><sentence><star index="1" /></sentence></denormalize> :3</li>
				<li>Faku: Kick <denormalize><sentence><star index="2" /></sentence></denormalize> :3</li>
				<li>Faku: Time to kick <denormalize><sentence><star index="1" /></sentence></denormalize> :3</li>
				<li>Faku: Time to kick <denormalize><sentence><star index="2" /></sentence></denormalize> :3</li>
				<li>Faku: Why not both? :3</li>
			</random>
		</template>
	</category>	
```

You could guess that it'd be entirely broken since we use star with index only, but it works properly:

```
23:24 - ArchiBoT: Faku: Why not both? :3
23:25 - ArchiBoT: Faku: Kick Aaa :3
23:25 - ArchiBoT: Faku: Time to kick Aaa :3
23:25 - ArchiBoT: Faku: Kick Bbb? :3
```

I'm so confused by this, but in any case, please take a look at `rosie_fixed` with "aaa or bbb" outputs, as it doesn't work for some reason. I tried to guess why it doesn't work by analyzing our own AIML files but I couldn't find any logical explanation apart from the fact that if `<star/>` is used anywhere then weird things are happening with `<star index="2" />`.

It's not like it worked in the first place, but now it definitely works worse 😆 

Thank you a lot for the update and continuous support! ❤️

**Comment by Thielak** [comment]
For your convenience, the problematic pattern is at https://github.com/keiffster/program-y/blob/master/bots/rosie_fixed/aiml/default.aiml#L24054-L24098 
I found that giving that pattern any kind of priority (like in https://github.com/JustArchi/program-y/pull/12/commits/262df1c9dfeef7aac98669a762fe057cc612e843) fixes the issue.

**Comment by keiffster** [comment]
Ok, let me take a look today and get back to you,

**Comment by keiffster** [comment]
Train delayed so got some extra time, found an issue in the TOPIC and THAT processing which is compounded by the element of the term, which made testing little tougher ;-)

0.5.1 should fix your issue.

Enjoy

**Comment by JustArchi** [comment]
And it's indeed fixed, thanks a lot! 👍
