### ISSUE TITLE
How to mute logging?

### ISSUE THREAD

**Issue by jiaeyan** [keiffster/program-y#180]
Hi Keifftser,

Currently I'm using program-y 2.2, and I am wondering is there any efficient way to mute all logging actions without touching the source code? For some reason I don't need them to either write to file or print to console. Thank you very much.

**Comment by keiffster** [comment]
program-y uses python logging. You therefore have a couple of option either

A) change the logging level to ERROR or even 0 and this will stop all output.

B) redirect logging output to a file

C) redirect logging output to /dev/null

All of these are done by changing logging.yaml.

For more info on the content of this file see Python logging documentation


Regards 

Keith
keith@keithsterling.com
07771 597630

**Comment by jiaeyan** [comment]
Hi Keith,
Thank you very much for you detailed reply, and I will try as soon as possible.
Best

**Comment by keiffster** [comment]
I’m also updating the documentation over the next couple of days so will add a section to the logging page on how to mute with the various options

Regards 

Keith
keith@keithsterling.com
07771 597630
