### ISSUE TITLE
Exclude from Sentance Splitting

### ISSUE THREAD

**Issue by poovarasanvasudevan** [keiffster/program-y#184]
Issue tracker is **ONLY** used for reporting bugs. NO NEW FEATURE ACCEPTED! Use [stackoverflow](https://stackoverflow.com) for supporting issues.

I have a scenario of Making user to Enter their user name what has dot( . )

## Expected Behavior
Should Work in Single Value ( user.name)

## Current Behavior

Splitting Sentances (user  , name)

## Steps to Reproduce
1. With this simple AIML

```
<?xml version="1.0" encoding="UTF-8" ?>
<aiml version="2.0">

    <category>
        <pattern>* RESET PASSWORD</pattern>
        <template>
            <srai>* RESET MY PASSWORD</srai>
        </template>
    </category>

    <category>
        <pattern>* RESET * PASSWORD</pattern>
        <template>
            <srai>PASSWORDTYPE</srai>
        </template>
    </category>

    <category>
        <pattern>PASSWORDREM</pattern>
        <template>
            <think>
                <set name="tcontext">PASSWORDREM</set>
            </think>
            Please Enter your network Login
        </template>
    </category>

    <category>
        <pattern>SECRETID</pattern>
        <template>
            <think>
                <set name="tcontext">SECRETID</set>
            </think>
            Enter your secret ID
        </template>
    </category>

    <category>
        <pattern>PASSWORDTYPE</pattern>
        <template>
            <think>
                <set name="tcontext">PASSWORDTYPE</set>
            </think>
            Sure what kind of password ^AD ^Remedy ^Peoplesoft
        </template>
    </category>

    <category>
        <pattern>*</pattern>
        <template>
            <condition name="tcontext">
                <li value="PASSWORDREM">
                    <think>
                        <set name="networklogin">
                            <denormalize><star/></denormalize>
                        </set>
                    </think>
                    <srai>SECRETID</srai>
                </li>

                <li value="PASSWORDTYPE">
                    <think>
                        <set name="passwordtype">
                            <star/>
                        </set>
                    </think>
                    <srai>PASSWORDREM</srai>
                </li>

                <li value="SECRETID">
                    <think>
                        <set name="secretid">
                            <denormalize><star/></denormalize>
                        </set>
                    </think>
                    <srai>RESETPASSWORD <get name="networklogin"/></srai>
                </li>
                <li>
                    How can i Help You
                </li>
            </condition>

        </template>
    </category>


    <category>
        <pattern>RESETPASSWORD *</pattern>
        <template>
            <think>
                <set name="tcontext" />
            </think>
            Your password <star/> reset Success
        </template>
    </category>

</aiml>

```

2. Test Made

User >>> Can you reset my Password
BOT >>> Sure what kind of password
User >>> AD
BOT >> Please enter your network login
User >> user.name
BOT >>  Enter your secret ID Your password user reset Success

3 . Test (without ( . ) in username )

User >>> Can you reset my Password
BOT >>> Sure what kind of password
User >>> AD
BOT >>>  Please enter your network login
User >>>  username
BOT >>> Enter your secret ID
User >>> username
BOT >>>  Your password username reset Success

## Context (Environment)
* Version of Y-Bot: LATEST
* Version of Python:  3.6
* Operating System ( inc Version ):  Windows 10 1809

## Detailed Description

When i entering username with . it splits, without . it works normally

**Comment by keiffster** [comment]
Sorry, could you provide a little more detail ?

**Comment by keiffster** [comment]
You have a couple of options, if you are sure that your users will never use more than one sentence then you could remove the fullstop from the sentence splitter. This would be the easiest solution.

Alternatively you could make it part of the entry for them to use the word 'dot'

BOT >> Please enter your network login
User >> user dot name

Not a good solution, but would also work as the bot we normalise dot back to . and conjunct the 2 words automatically for you

Option 3 is a big of a longer piece of work but something that I have thought about. For things such as sentence splitting, spelling etc, I could implement a system property that you could control to switch on and off

So AIML would look something like

```
    <category>
        <pattern>PASSWORDREM</pattern>
        <template>
            <think>
                <set name="tcontext">PASSWORDREM</set>
                <set name="splitter">Off</set
            </think>
            Please Enter your network Login
        </template>
    </category>

Then switch it back on after the * pattern captures the input
```

By the way there is a more elegant solution for what you are using topics rather than setting contexts

K

**Comment by poovarasanvasudevan** [comment]
May be, I may suggest some way,

Creating a custom Tag like this

```
  <ignore-preprocessing><star /></ignore-preprocessing>
```
This will bypass preprocessing and make it available directly to bot

**Comment by keiffster** [comment]
Unfortunately that would not work as by the time you are processing the 'star' the pre parser has already split the sentence.

I have a working model which I will release in a couple of days which works through setting variables, as described above it would work similar to 

```
    <category>
        <pattern>PASSWORDREM</pattern>
        <template>
            <think>
                <set name="tcontext">PASSWORDREM</set>
                <set name="sentence-splitter">off</set
            </think>
            Please Enter your network Login
        </template>
    </category>

    <category>
        <pattern>*</pattern>
        <template>
            <set name="sentence-splitter">on</set
            <condition name="tcontext">
     :
     :
```

BTW you can replace your context variable with the use of topic as follows

```
    <category>
        <pattern>PASSWORDREM</pattern>
        <template>
            <think>
                <set name="topc">PASSWORDREM</set>
                <set name="sentence-splitter">off</set
            </think>
            Please Enter your network Login
        </template>
    </category>
   
    <topic name="PASSWORDREM">
    <category>
        <pattern>*</pattern>
        <template>
               Logic for handling password
        </template>
    </category>
    </topic>

    <topic name="PASSWORDTYPE">
    <category>
        <pattern>*</pattern>
        <template>
               Logic for handling password type
        </template>
    </category>
    </topic>
```

In this instance it removes the need for a nested condition for handling the context and compartmentalises the logic for handle each condition into its own category

**Comment by gianfrasoft** [comment]
Is there a way to move configuration param:
`<set name="sentence-splitter">off</set>`
inside the configuration file?

**Comment by keiffster** [comment]
Hi there, 

Not sure what you are trying to do, the parameter is designed to allow you to switch off sentence splitting in flight.

By moving it into configuration file do you want to switch off sentence splitting altogether, or have a default value at start up ?

K

**Comment by gianfrasoft** [comment]
My problem is about email addresses: i need Program-Y to processes info@website.com as one word. Always.

**Comment by keiffster** [comment]
Ok, that’s not the sentence splitter, that’s the normaliser which turns info@website.com <mailto:info@website.com> into info at website dot com so that it can be processed as AIML

K

**Comment by gianfrasoft** [comment]
Is there a page in the wiki wher I can find more info about?

**Comment by keiffster** [comment]
Thanks for highlighting that I don’t have page for normalise and dernomalise 

Basically if you look at denormalise.txt file you will see the substitutions that take place on pre processing. This process replaces symbols with text which make it easier for aiml to process

K

**Comment by keiffster** [comment]
Added a new page on the wiki to cover pre and post normalisation


https://github.com/keiffster/program-y/wiki/Normalization

Regards 

Keith
keith@keithsterling.com
07771 597630
