### ISSUE TITLE
Program-y 3.5 Release

### ISSUE THREAD

**Issue by keiffster** [keiffster/program-y#186]
There have been a few recent releases of Program, but 3.4 and now 3.5 are the ones I am especially excited about. As well as support for the full AIML 2.1 including all Rich Media tags,  it ships with a huge range of clients to connect your AIML bot to.

The full list being

- Amazo Alexa
- Cisco Spark (via Google DialogFlow)
- Text Console
- DialogFlow Phone Gateway
- Embeddable
- Facebook
- Google DialogFlow
- Kik
- LINE
- Microsoft Cortana (via Google DialogFlow)
- REST
- Slack
- TCP Socket
- Skype (via Google DialogFlow)
- Telegram
- Twilio IP (via Google DialogFlow)
- Twilio SMS
- Twitter
- Viber
- Web Client
- XMPP

By integrating with DialogFlow, you can leverage their extension client additions, or use the custom-built libraries provided by Program-y.

With this list, you can use Alexa, DialogFlow and Cortana to build your specialist skills, but then use a Program-Y AIML implementation to add personality and general knowledge to your bot.

Enjoy.

**Comment by ohoachuck** [comment]
👍
