### ISSUE TITLE
Program-y 3.7 (Preview)

### ISSUE THREAD

**Issue by keiffster** [keiffster/program-y#188]
v3.7 will introduce the concept of triggers, the ability to action a piece of code at pre determined 
points in the code

For example when a question is asked, or when a conversation starts.

Triggers cannot affect the question asked or the answer given but can be used to call out to externals systems or data sources

Their first use is in my own bit to send me an email whenever a new conversation starts so that I can interject if I want to

**Comment by johnlito123** [comment]
Hey there - First of, fantastic codebase and im really learning from this.

Second - Im checking out this section:
```    def load_config_section(self, configuration_file, configuration, bot_root, subs: Substitutions = None):
        tokenizer = configuration_file.get_section(self._section_name, configuration)
        if tokenizer is not None:
            self._classname = configuration_file.get_option(tokenizer, "classname", missing_value="programy.parser.tokenizer.Tokenizer", subs=subs)
            self._split_chars = configuration_file.get_option(tokenizer, "split_chars", missing_value=" ", subs=subs)
        else:
            YLogger.warning(self, "'tokenizer' section missing from bot config, using defaults") 
```

Particularly the `programy.parser.tokenizer.Tokenizer` section but looking into your programy code base, I cant seem to find this file or a template of this file. 

Is this something which you are working on?

**Comment by keiffster** [comment]
The code for loading tokenizer config is in 
    src/programy/config/brain/tokenizer.py
and the code on Github is viewable at
    https://github.com/keiffster/program-y/blob/master/src/programy/config/brain/tokenizer.py

The code for tokenization is  
    /src/programy/dialog/tokenizer/tokenizer.py, 
again you can see the code in GitHub at
    https://github.com/keiffster/program-y/blob/master/src/programy/dialog/tokenizer/tokenizer.py

Are you looking for an example of a Tokenizer other than the default tokenizer.py that handles English and cjk.py that handles chinese ?

K

**Comment by johnlito123** [comment]
Perfect thanks, Right now no - Maybe in the future, Im trying to manipulate the current Telegram code base so that this AI can work within Discord but just having trouble so im reading all documents. 

Have you though about or planned to implement a Discord capabilites for this codebase?

**Comment by keiffster** [comment]
Just had a look at the discover documentation, looks pretty straight forward using the Webhook. Probably take less than a week of my normal capacity ( i.e evenings ). I could add it to the backlog for after 3.7 which is due sometime next few days,

**Comment by johnlito123** [comment]
Ok nice - will keep an eye out - recently started diving deep into learning python and using this as my first hand experience to develop something - thanks

**Comment by keiffster** [comment]
Now released to master and pypi
