### ISSUE TITLE
<learn> issue

### ISSUE THREAD

**Issue by BattleCisco** [keiffster/program-y#19]
Hello,
First of all, I want to say that you have created something awesome, and also i want to apologize if the code i'll add here might be disturbing (I'm coding on windows).

So, before i show code,  i just want to say that i wanted to add a class that i could implement in my other code, without relying on shell commands. Im not a pro on python, so my code might be very unprofessional, but anyway.

The problem i am getting is with learn and learnf.

When i try to use the learn command, more than once, the second category's template is overriden by the first one.

> You> LEARN THE SUN IS HOT
> Bot> OK I'LL LEARN THAT THE SUN IS HOT.
> You> WHAT IS THE SUN
> Bot> HOT
> You> LEARN AIML IS AWESOME
> Bot> OK I'LL LEARN THAT AIML IS AWESOME.
> You> WHAT IS AIML
> Bot> HOT

Changing the learn statement to learnf, so it writes a file, i can see the pattern for aiml has hot as template.
Of course, this post would be useless if i didnt provide the code (and aiml files) i used.

[TheBot.zip](https://github.com/keiffster/program-y/files/844849/TheBot.zip)

The aiml script is long, but how it works is showed in the example at http://alicebot.wikidot.com/learn-aiml
> Human: Gateau is a type of cake
> Bot: OK, I will add that fact about gateau to my database.
> Human: What is gateau
> Bot: A type of cake.

Alternatively, you can use this aiml file, it has the same idea, only that its shorter (It gets the same problem).

[learn.txt](https://github.com/keiffster/program-y/files/844881/learn.txt)

(rename to .aiml, Github didnt like aiml files)

**Comment by keiffster** [comment]
Thanks, I can replicate it, I'll look into it and get a fix published

**Comment by keiffster** [comment]
Check 0.5.2 which fixes an issue with lazy evaluation of learn and learnf

New tests added to /program-y/src/test/aiml_tests/learn_tests/test_learn_aiml.py which cover your exact issue

Enjoy 

K

**Comment by BattleCisco** [comment]
Hello again,

Just want to say it works flawlessy, Thank you alot.

//Best Regards

**Comment by keiffster** [comment]
Your welcome, I'll close the issue if thats ok
