### ISSUE TITLE
Program-y 3.8 (Preview) On-Prem PandoraBots/Live!zilla and Discord support

### ISSUE THREAD

**Issue by keiffster** [keiffster/program-y#191]
As 3.7 nears release in the next couple of days, its time to share what is being planned with v3.8

* As more and more customers ask about a on-premises alternative to Pandorabots and given Program-Y is fully AIML 2.1 compliant we will be added the ability to use your existing PB configuration files for things like sets, maps, substitutions and splitters, rather than having to convert PB xml files to PY text format. This should make it easier to take your existing PB bot and run it with little or no modification on PY. 

* Support for Live!zilla. Following an integration for a client, we will be adding the rather simple configuration required to call PY from your LZ app and therefore use PY as your source of chatbot knowledge

* Support Discord. One of the next clients to add to the huge list of clients we already support

**Comment by keiffster** [comment]
New features added to 3.7 include

* Healthcheck (ping) service for all clients, providing, health of service data 
* Microsoft Bot Framework Client

**Comment by kdand** [comment]
How do we update above mentioned features? currently running 3.7 version.

**Comment by keiffster** [comment]
When 3.8 ships you wil just need to run pip3 install —upgrade programy

**Comment by kdand** [comment]
Thank you.

I want to build a IT knowledge base for general issues. What would be the best way to build it?

**Comment by keiffster** [comment]
Start with the series of questions you want to answer and create the basic grammars that respond to these, e.g

```
<category>
    <pattern>CHANGE PASSWORD</pattern>
    <template>
       You can change your password by logging into your account, going to the security section and clicking 'Change Password'
    </template>
</category>
```

Do this for each question, keeping the pattern short, you can then test all your answers.

Next stage is to introduce the reductions that will lead to these answers

```
<category>
    <pattern>HOW * CHANGE PASSWORD</pattern>
    <template>
            <srai>CHANGE PASSWORD</srai>
   </template>
</category

<category>
    <pattern>WHERE * CHANGE PASSWORD</pattern>
    <template>
            <srai>CHANGE PASSWORD</srai>
   </template>
</category
```

Just keep adding responses and srais as you build your grammar

**Comment by keiffster** [comment]
3.8 released to the wild, pypi updated in next 24 hours
