### ISSUE TITLE
GET MY Regex and iset values

### ISSUE THREAD

**Issue by poovarasanvasudevan** [keiffster/program-y#192]
Issue tracker is **ONLY** used for reporting bugs. NO NEW FEATURE ACCEPTED! Use [stackoverflow](https://stackoverflow.com) for supporting issues.

How can i get the value matching regex or iset value entered

## Expected Behavior

```
       <category>
            <pattern>^ <regex template="date" /> ^</pattern>
            <that>Please Enter your Date of birth (mm/dd/yyyy)</that>
            <template>
                <think>
                    <set name="dob"></set>
                </think>
            </template>
        </category>

```

here i allowing the user to enter date
It matching regex but how can i get the value that entered in  <regex template="date" />

## Steps to Reproduce
USER : 11/07/1992

## Context (Environment)

* Version of Y-Bot: latest
* Version of Python:  3.6
* Operating System ( inc Version ):  Windows 7

**Comment by keiffster** [comment]
Use the `<star />` tag, just like you would use it for normal * pattern matching

```
      <category>
            <pattern>^ <regex template="date" /> ^</pattern>
            <that>Please Enter your Date of birth (mm/dd/yyyy)</that>
            <template>
                <think>
                    <set name="dob"><star /></set>
                </think>
            </template>
        </category>
```

**Comment by poovarasanvasudevan** [comment]
Thanks for this, working Perfect...
