### ISSUE TITLE
Set Get value from Services

### ISSUE THREAD

**Issue by poovarasanvasudevan** [keiffster/program-y#194]
Can I set Get value from my custom service

I have created a service called employee verification, i collected from information like
Emp No: xxxx
Secret Code: xxxx
Fullname; xxxx
....

with <sraix> i can able to call service, passing huge parameters using splitting ( | ) characters that breaks logics ( in secret code user can enter any character on their own)

## Expected Behavior

to get client get/set using client_context

**Comment by keiffster** [comment]
You have a number of options, 

1) Set variables directly. In you service method ask_question(self, client_context, question), the parameter client_context provides direct access to the variables as follows
```
conversation = client_context.bot.get_conversation(client_context)
conversation.set_property(name, value)
```

2) Parse the result of the call to the service with an outer srai call

```
<category>
    <pattern>CALL MY SERVICE</pattern>
    <template>
            <srai>SERVICE RESULT <sraix service="myservice">VAL1 VAL2 VAL3</sraix></srai>
    </template>
</category>

<category>
    <pattern>SERVICE RESULT * * *</pattern>
    <template>
            <think>
                   <set name="val1"><star index="1"></set>
                   <set name="val2"><star index="2"></set>
                   <set name="val3"><star index="3"></set>
            </think>
            .... Do something with these values.....
    </template>
</category>
```
In this way you can use standard pattern matching of a category to parse our the values you return.

**Comment by poovarasanvasudevan** [comment]
Great, That's working fine,
