### ISSUE TITLE
Another behaviour with wildcard "_"

### ISSUE THREAD

**Issue by gianfrasoft** [keiffster/program-y#196]
We are trying to make this code work:
```
    <category>
        <pattern>_ STOPWORD</pattern>
        <template><star index="1"></star> SEPARATOR1</template>
    </category>

    <category>
        <pattern># STOPWORD _</pattern>
        <template><star index="1"></star> SEPARATOR2 <star index="2"></star></template>
    </category>
```

but when we send the input **hello STOPWORD** the response is: **Hello STOPWORD SEPARATOR1**
I think it should be: **Hello SEPARATOR1**

* Version of Python: 3
* Operating System ( inc Version ): Ubuntu 16
* Sanic

**Comment by keiffster** [comment]
Hi there, yes that looks like an issue in the matcher

I’ll review tonight and see what’s happening

K

**Comment by keiffster** [comment]
Found the problem. How urgent is fix as I could get a release by Monday or just roll it into the next release in a week or so

**Comment by gianfrasoft** [comment]
By next week it would be great for me, but... No problem!

Anyway, thanks for your time!!!

**Comment by keiffster** [comment]
New version pushed to master with single fix for this issue. Let me know how you get on

Just pull the file from master

**Comment by gianfrasoft** [comment]
Great! Thank you.
