### ISSUE TITLE
Install tries to build its own copy of OpenSSL and fails.

### ISSUE THREAD

**Issue by John-Nagle** [keiffster/program-y#197]
Issue tracker is **ONLY** used for reporting bugs. NO NEW FEATURE ACCEPTED! Use [stackoverflow](https://stackoverflow.com) for supporting issues.

## Expected Behavior

Install completes.

## Current Behavior

Install fails while running the build process for wheel "cryptography".

```
    building '_openssl' extension
    creating build/temp.linux-x86_64-3.5/build
    creating build/temp.linux-x86_64-3.5/build/temp.linux-x86_64-3.5
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.5m -c build/temp.linux-x86_64-3.5/_openssl.c -o build/temp.linux-x86_64-3.5/build/temp.linux-x86_64-3.5/_openssl.o -Wconversion -Wno-error=sign-conversion
    build/temp.linux-x86_64-3.5/_openssl.c:498:30: fatal error: openssl/opensslv.h: No such file or directory
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```
Looks like it has an unsatisfied dependency. 

Why is a chatterbot trying to build its own version of OpenSSL, anyway?

## Steps to Reproduce

1. Get Current Ubuntu 16.04 LTS.
2. Do prerequisites per https://github.com/keiffster/program-y/wiki/Install_Linux_PreReqs
3. pip3 install programy

## Context (Environment)

* Version of Y-Bot: Whatever above installer installs.
* Version of Python: 3.5.2
* Operating System ( inc Version ): Ubuntu 16.04LTS x86-64

**Comment by keiffster** [comment]
That’s weird, it could be pulled down because the web client and all the rest based clients now use Https

I’ve not seen that before on an Ubuntu install which I use on multiple AWS installs. 

I’ll run a clean install using your version and see what gives

**Comment by John-Nagle** [comment]
Thanks. It looks like it might want the dev version of SSL installed, with more headers. I don't have that installed. But why is it recompiling _openssl.c anyway?

**Comment by keiffster** [comment]
Build a VM with 16.04 from scratch and Program-Y installed fully with no issues around ssl headers

Can you send me the pip3 output so that I can see what is happening ?

**Comment by John-Nagle** [comment]
I updated Ubuntu 16.04 LTS to its latest version and tried

pip3 install programy

which succeeded. It still builds "cryptography" as a wheel, but I'm not seeing C compiles.

[buildprogramy.txt](https://github.com/keiffster/program-y/files/3100936/buildprogramy.txt)

So now it works.
