### ISSUE TITLE
Trying to match pattern with french accents

### ISSUE THREAD

**Issue by ohoachuck** [keiffster/program-y#198]
Trying to match french syntax with accents
## Expected Behavior

I'm trying to match the following french term "été" with:
```
<category>
  <pattern>été</pattern>
  <template>This is summer in french</template>
</category>
```

## Current Behavior

A random pickup line is returned

## Possible Solution

Can I find a way while playing with normal/denormal ?
## Steps to Reproduce

1. test with above category pattern

## Context (Environment)

* I'm currently at version v 3.0.0 Beta 1 and my grammar is v 1.6.0.
* Version of Python: 3.6
* Operating System ( inc Version ): mac OS / CentOS

## Detailed Description

Is there something obvious I'm missing here ?

**Comment by keiffster** [comment]
Is it appropriate to exclaim ‘sacre bleu’ Or are we getting a little too Monty Python

I’ll take a look this weekend, as a stop gap you could use normal.txt to convey the accented e to a normal e and then match against ete. But that is not a long term solution. I’ll get it sorted shortly

**Comment by ohoachuck** [comment]
Sacrebleu ! 
Thanx ! ;)
I’ll try the normal.txt approach for now.

O.

Envoyé de mon iPhone

**Comment by ohoachuck** [comment]
hum... normal.txt's trick does not work.
I'm afraid this might be more complicated than expected.

O.

**Comment by ohoachuck** [comment]
Sorry, I just found that the issue have nothing to do with Program-y, but with my (froggy french) webchat client! :)
Sorry for the overhead.
In the mean time, I was indeed surprised that such basic thing wasn't supported.
It was anyway a good opportunity for me to recall usage or normal.txt and denormal.txt.
Thanks for your always quick support Keith.

O.
