### ISSUE TITLE
Even another behaviour about wildcards

### ISSUE THREAD

**Issue by gianfrasoft** [keiffster/program-y#199]
It seems that a **word** pattern has a lower priority compared to an **asterirk** pattern:

```
    <category>
        <pattern>firstword</pattern>
        <template>FOUND1</template>
    </category>

    <category>
        <pattern>*</pattern>
        <template>NOTHING FOUND</template>
    </category>

```

When I send the input **firstword** the response is: **NOTHING FOUND**
I think it should be: **FOUND1**

It seems this problem is affecting the latest version of ProgramY.

* Version of Python: 3
* Operating System ( inc Version ): Ubuntu 16
* Sanic

**Comment by keiffster** [comment]
I'm not seeing in in the current or previous versions that I have tested.

Created the following file 
```

<aiml>

	<category>
        <pattern>FIRSTWORD</pattern>
        <template>FOUND1</template>
    </category>

    <category>
        <pattern>*</pattern>
        <template>NOTHING FOUND</template>
    </category>

</aiml>
```

And ran tests over it and everyone came back with FOUND1.

There are over 1500 aiml unit tests run against the parser, such a significant fault would have shown during pre-releases tests

Could you empty your log file and run you bot up again and only ask this question then send me the log file and I can see from the match trace what is happening

**Comment by keiffster** [comment]
Just an after thought have you checked your errors log file

When you get something weird like this it can be that the xml for the ‘first word’ element is broken

The parser is quite sympathetic to xml, it throws out individual category errors rather than fail the whole file

K

**Comment by gianfrasoft** [comment]
Sorry, my **mistake**!

There was an **error** in one AIML file and part of it wasn't been processed.

It seems to be a bit difficult for me to read ProgramY's log files: there was an ERROR and I didn't check it.

Thanks for your support!

**Comment by keiffster** [comment]
Keep an eye on the first 4 likes of console output when you run your bot. If there are any errors or duplicates in you AIML files, you will see them reported as the last 2 lines below
```
Initiating Console Client...
No bot root argument set, defaulting to [../../config/xnix]
Found a total of 1 errors in your grammars, check your errors store
Found a total of 6 duplicates in your grammars, check your duplicates store
```
This shows there was 1 AIML error and 6 duplicates found when loading

Alternatively, you can lower the logging, by reducing it from DEBUG to ERROR in logging.yaml

**Comment by gianfrasoft** [comment]
Thank you for the suggestion. Using sanic I see the output only via log so I have to check it anyway.

There are a lot of informations. Can I reduce the amount of them?

**Comment by keiffster** [comment]
Check out the wiki page on how loggin works

https://github.com/keiffster/program-y/wiki/Config_Logging

**Comment by gianfrasoft** [comment]
Ok, I'll take a better look! 
: )

**Comment by gianfrasoft** [comment]
About wildcards priority, is this ok for you?

```
    <category>
        <pattern>^ SEPARATOR ^</pattern>
        <template>FOUND1</template>
    </category>

    <category>
        <pattern>^ DEBUG1 ^ DEBUG2 ^</pattern>
        <template>FOUND2</template>
    </category>

```
If I ask: _DEBUG SEPARATOR DEBUG2_
or if I ask: _TEST DEBUG SEPARATOR DEBUG2 TEST_
in both cases bot returns **FOUND1**.

It seems that the numerosity of the **^** wildcard doesn't affect the category's priority.

**Comment by gianfrasoft** [comment]
About wildcards priority, is this ok for you?

```
    <category>
        <pattern>^ SEPARATOR ^</pattern>
        <template>FOUND1</template>
    </category>

    <category>
        <pattern>^ DEBUG1 ^ DEBUG2 ^</pattern>
        <template>FOUND2</template>
    </category>

```
If I ask: _DEBUG1 SEPARATOR DEBUG2_
in both cases bot returns **FOUND1**.

It seems that the numerosity of the **^** wildcard doesn't affect the category's priority.

**Comment by gianfrasoft** [comment]
About wildcards priority, is this ok for you?

```
    <category>
        <pattern>^ SEPARATOR ^</pattern>
        <template>FOUND1</template>
    </category>

    <category>
        <pattern>^ DEBUG1 ^ DEBUG2 ^</pattern>
        <template>FOUND2</template>
    </category>

```
If I ask: _SEPARATOR DEBUG1 DEBUG2_
in this case bot returns **FOUND1**.

It seems that the numerosity of the **^** wildcard doesn't affect the category's priority.

**Comment by keiffster** [comment]
This may be an interpretation of the spec for pattern matching

The first category matches the ^ to debug1 and then separator to separator and then the second ^ to debug2

In my mind this is correct

However I will try to see how then ordering of such a complex set of categories affects the parser. Have you tried switching them round

I’ll also try and see what program-ab does as that is the reference when there is little or no documentation as is the case with the zero or more tag

**Comment by gianfrasoft** [comment]
I switched categories and result is the same.

According to this content: https://github.com/keiffster/program-y/wiki/AIML-Pattern-Matching

matching "word" should have an higher priority then "^" char. Now I'm almost sure this is the problem. Infact even if I use "priority words results remail the same.

Look:
```
    <category>
        <pattern>^ $DEBUG1 ^ $DEBUG2 ^</pattern>
        <template>FOUND2</template>
    </category>

    <category>
        <pattern>^ SEPARATOR ^</pattern>
        <template>FOUND1</template>
    </category>
```
even in this example, if I ask: _SEPARATOR DEBUG1 DEBUG2_
bot returns **FOUND1**.

**Comment by gianfrasoft** [comment]
> 
> 
> I switched categories and result is the same.
> 
> According to this content: https://github.com/keiffster/program-y/wiki/AIML-Pattern-Matching
> 
> matching "word" should have an higher priority then "^" char. Now I'm almost sure this is the problem. Infact even if I use "priority words results remail the same.
> 
> Look:
> 
> ```
>     <category>
>         <pattern>^ $DEBUG1 ^ $DEBUG2 ^</pattern>
>         <template>FOUND2</template>
>     </category>
> 
>     <category>
>         <pattern>^ SEPARATOR ^</pattern>
>         <template>FOUND1</template>
>     </category>
> ```
> 
> even in this example, if I ask: _SEPARATOR DEBUG1 DEBUG2_
> bot returns **FOUND1**.

Do you think I should create another issue for this?

**Comment by keiffster** [comment]
Re-opened

**Comment by keiffster** [comment]
Spent some time looking at this problem, seems to be a problem with priority '$' marker being ignored when the parser encounters a zero or more wild card '^' or '#'.  When the priority marker is not present, then the matcher returns the right element. I've started looking into a fix and should have a response shortly

**Comment by keiffster** [comment]
Found the issue, I'd done something pretty stupid in the design which meant $ words were ignored. I now have the fix ( nothing more than 10 lines of code ) in place and going through final testing. All AIML tests are passing, so no adverse effects. 

I've merged into 3.8 as this is the next release due over the next few days. 

Thanks for your patience

**Comment by ohoachuck** [comment]
👍

Envoyé de mon iPhone

**Comment by keiffster** [comment]
3.8 released to master, includes this fix, pypi updated within next 24 hours

**Comment by ohoachuck** [comment]
I'm always impressed for the massive work being done here.
Great Respect man !

O.

**Comment by ohoachuck** [comment]
Hello,
Locale seems to work well. 
You might have forgotten to update version.txt file.

O.

**Comment by keiffster** [comment]
It gets updated automatically via the pypi deploy scripts which will run today

**Comment by ohoachuck** [comment]
Ok, cool.
Also the healthchecker link in root Readme.md lead to a 404.
If I believe right relative path should be ../../wiki/HealthChecker

Note: I have never realised cloning a repo do not take the wiki. The dark side of having relative link is that cloned repo will not have the page linked.
I wanted to setup my environment to suggest a pull request but for some reasons I was having problem with a git merge upstream/master and was too tired to find why it did not work (I have some custom services I don’t want to remove).
Git topics (together with encodings) are animals that I’m afraid of :). Every time I meet them I get confused.
I know I cannot help with the core code as my python is not clean enough and you don’t want to mess with your hard work (you shouldn’t). But I have seen lots of typo I could help with from time to time. I’ll try to do it.

O.

Envoyé de mon iPhone

**Comment by ohoachuck** [comment]
sorry for my Last confusing email base on a wrong old issue thread.
And sorry for spamming you again :)
O.

**Comment by keiffster** [comment]
It’s ok, it’s probably a good call and I should include full paths in readme’s for this reason

The wiki is kept as a separate project which I edit locally and then push on release of next version
