### ISSUE TITLE
Missing module?

### ISSUE THREAD

**Issue by JustArchi** [keiffster/program-y#20]
Change introduced in one of last 3 commits:

```
Traceback (most recent call last):
  File "../../src/programy/clients/rest.py", line 19, in <module>
    from programy.clients.clients import BotClient
  File "/home/steam/ArchiBoT/program-y/src/programy/clients/clients.py", line 24, in <module>
    from programy.config.file.factory import ConfigurationFactory
  File "/home/steam/ArchiBoT/program-y/src/programy/config/file/factory.py", line 20, in <module>
    from config.file.json import JSONConfigurationFile
ImportError: No module named 'config'
```

It worked fine before.

I installed all modules listed in **[`requirements.txt`](https://github.com/keiffster/program-y/blob/master/requirements.txt)**, what am I missing? It might be also worthy to add it to `requirements.txt` if it's not issue specific to my machine or python (3.5.3).

Thanks in advance!

**Comment by keiffster** [comment]
Wierd, its not a new module just a typo when I refactor all the config code, its missing programy from the begining, the line should be

from programy.config.file.json import JSONConfigurationFile

and not

from config.file.json import JSONConfigurationFile

My IDEA was not picking this up and so allowed it to get committed

New push to master with the changes just gone up
