### ISSUE TITLE
locale="fr_FR" for date format

### ISSUE THREAD

**Issue by ohoachuck** [keiffster/program-y#200]
I'm trying to set locale for displaying date and time in French format. I couldn't find much info on the doc nor on the web but by setting "locale" key in date tag. I'm not really sure if this is suppose to work ?
So I'm trying it like that:
```XML
<category>
        <pattern>TESTDATE</pattern>
        <template>Nous sommes le
            <sentence><date locale="fr_FR" format="%d %B %Y" jformat="dd MMMMMMMMM yyyy"/></sentence>
        </template>
</category>
```
## Expected Behavior

I would have expected to say : "Nous somme le 17 Avril 2019"
## Current Behavior

It says "Nous somme le 17 **April** 2019"
## Possible Solution

is "locale" key expected to work ?
## Steps to Reproduce
Try with this ?
```XML
<category>
        <pattern>TESTDATE</pattern>
        <template>Nous sommes le
            <sentence><date locale="fr_FR" format="%d %B %Y" jformat="dd MMMMMMMMM yyyy"/></sentence>
        </template>
</category>
```

## Context (Environment)

* Version of Y-Bot: 3.0.0 Beta 1
* Grammar: 1.6.0
* Version of Python: Python 3.6
* Operating System ( inc Version ): mac or linux

**Comment by keiffster** [comment]
`locale` is an extension that pandorabot added ( along with timezone ), these are something I missed when I was writing Program-y

I have added local and its working as per your requirements. I'll add timezone later and then release a patch with these additions

**Comment by ohoachuck** [comment]
Hello Keith,
many thanx !

O.


Envoyé de mon iPhone

**Comment by keiffster** [comment]
This fix is now scheduled for release in 3.8 shortly

**Comment by ohoachuck** [comment]
Cool 👍
O.

**Comment by keiffster** [comment]
3.8 released to master, pypi updated in next 24 hours
