### ISSUE TITLE
No matching user found with Facebook 

### ISSUE THREAD

**Issue by Algeneralo** [keiffster/program-y#201]
Whenever a request(message) is sent to the facebook page i.e the program-y bot, the bot handles the message and gives a correct reply however it also returns another result besides the first correct response, which gives an error.
## Expected Behavior

Return the message to an existing user
## Current Behavior

The bot returns the same message to itself 
## Possible Solution

Removing the second response
## Context (Environment)

* Version of Y-Bot: latest version
* Version of Python: 3.6.5
* Operating System ( inc Version ): deepin (Ubuntu)

## Detailed Description

When the user sends a message to the facebook page, the bot returns 2 responses, the first one is the one that we need and it is a success,but the second one fails and we don't need it.

Example:
`Handling text...
Payload: {
  "recipient": {
    "id": "976418212548910"
  },
  "message": {
    "text": "Sorry, I don't have an answer for that!"
  }
}
Result: {
  "error": {
    "message": "(#100) No matching user found",
    "type": "OAuthException",
    "code": 100,
    "error_subcode": 2018001,
    "fbtrace_id": "AnbGX4LqUSq"
  }
}
`
976418212548910 this is the bot id, however it should be the user's id and not the bot.

**Comment by keiffster** [comment]
Sorry for the delay, just returned from vacantion.

Are you using the native client, or one of the channels via Alexa or Google clients ?

**Comment by Algeneralo** [comment]
It's ok no problem, I'm using the native client

**Comment by keiffster** [comment]
Thanks, I've started looking into the problem. I see the Facebook documentation has changed on how to create a chatbot, so will be including any required fix int 3.8 along with updated documentation

**Comment by Algeneralo** [comment]
Thank you very much for the quick reply, your time is most appreciated. I was just wondering when will 3.8 be available?

**Comment by keiffster** [comment]
As soon as I've fixed this issue, which is just the rendered printing too much info. I've remove the code so this is now fixed and I'll be pushing 3.8 into end to end testing now, so hopefully release in the next coupe of days

**Comment by keiffster** [comment]
Fix has been pushed to master, pypi updated in the next 24 hours
