### ISSUE TITLE
How to use programy lib in python to make bots. 

### ISSUE THREAD

**Issue by sakshi74** [keiffster/program-y#209]
I installed and imported the lib. But I don't know how to use it, please help me.

**Comment by keiffster** [comment]
Have you read the installation instructions at

https://github.com/keiffster/program-y/wiki/Install

And used the AdminTool to download and install a bot ?

**Comment by sakshi74** [comment]
Yes, I am able to install it. Don't know how and where to make modification to male the bot reply according to my need. 

![error](https://user-images.githubusercontent.com/35483396/57295598-7d64ea80-70e8-11e9-9c93-06be395cedeb.PNG)

**Comment by keiffster** [comment]
Look at '\storage' folder, here is where all the data files are stored. To start adding AIML, add them to '\storage\categories'

Remember to restart anytime you change anything in the storage folder

If you are new to AIML and bots, try downloading y-bot via the admin tool, this is a fully functional bot with over 18,000 AIML categories which will load automatically

**Comment by sakshi74** [comment]
Thanks for replying my questions. Yes I am new to AIML, I will surely take a look on y-bot for better understanding of AIML. 

I used pip to install AIML on my Windows 10 machine.
![image](https://user-images.githubusercontent.com/35483396/57296868-acc92680-70eb-11e9-8a43-9a831c847ca7.png)

These are the file I got after installation. I don't see any '\storage' folder here. 

So I went to the site packages of the python I got storage file there. But not sure if I should be creating '\categories' folder there or need to create the folder? 

![image](https://user-images.githubusercontent.com/35483396/57297037-2a8d3200-70ec-11e9-8315-d58fb0f459c1.png)

Also, how can I use imported "programy" in python program. Can you provide some documentation for its usage.

**Comment by keiffster** [comment]
You are looking in the code directory. You need to be looking in the storage folder of template-y or y-bot. Which ever you have downloaded. 

You will see folders called \storage, \scripts, \config

In \storage folder you will see a folder called \categories

You aiml goes in there

**Comment by sakshi74** [comment]
Thanks. I downloaded template-y and was able to make modification and make bot reply as per my requirement. Appreciate your help.
