### ISSUE TITLE
code break when use "again" two times simultaneously in y-bot

### ISSUE THREAD

**Issue by 00archer0** [keiffster/program-y#213]

**Comment by keiffster** [comment]
I’m reworking the again code, should have a new release in next few days

**Comment by 00archer0** [comment]
okay, thank you buddy, you are really working hard. 👍

**Comment by keiffster** [comment]
I've updated Y-Bot to support a better implementation of again, this requires an upgrade to 3.8.4 which has just been updated to master and pushed to pypi

**Comment by 00archer0** [comment]
yes, its working now.
