### ISSUE TITLE
duplicate answers

### ISSUE THREAD

**Issue by PtolemyRE** [keiffster/program-y#214]
Hello. I'm having an issue where multiple sentences in a request can return the same response. 

I.E.: "Hey. Hey".
Returns: "Hello. Hello."

Is there any configuration or post processor to remove duplicate responses? I've looked around the documentation and haven't been able to find anything like that. Any help would be much appreciated.

**Comment by keiffster** [comment]
Unfortunately that’s expected not behaviour, if you ask it 2 sentences if gives 2 answers, if they are the same questions then you will get the same answers 

You could write a post processor that removes duplicates,  but the sentence splitter is a core part of bot behaviour and personality construction

Regards 

Keith
keith@keithsterling.com
07771 597630

**Comment by PtolemyRE** [comment]
Ok. That's understandable. I was planning on writing my own de-duper but just wanted to check before I started building things around the project. Thanks for the timely response and this amazing system.
