### ISSUE TITLE
<extension> tag not working

### ISSUE THREAD

**Issue by newdev7** [keiffster/program-y#22]
I have downloaded the latest version and tested. As you told there is no need of adding any punctuations in the `<that>` tag. I tested that and it is working.

But the `<extension>` tag is not working in the latest version. I tested with previous versions. There it is working but not in the latest version.

Can you please check and fix that issue.

Thanks.

**Comment by keiffster** [comment]
What seems to be the problem.

I added about 6 extensions to y-bot in the latest release and they all have unit tests which execute them via the AIML so I know it's working.

Are you getting a stack trace, or is the extension not firing and no output being produced

K

**Comment by newdev7** [comment]
Sorry @keiffster the issue is in my side. I was trying to import the ClientConfiguration from programy.config. But you removed that config.py file and created another folder and added that configuration in another file. I fixed that by importing it from correct file.
