### ISSUE TITLE
Again on wildcard "_"

### ISSUE THREAD

**Issue by gianfrasoft** [keiffster/program-y#220]
This code works perfectly:
```
    <category>
        <pattern>_ [STOP]</pattern>
        <template><star index="1"></star></template>
    </category>
```
Input: **Hello World [STOP]**
Output: **Hello World**

But this code doesn't work:
```
    <category>
        <pattern>_ _STOP_</pattern>
        <template><star index="1"></star></template>
    </category>
```
Input: **Hello World \_STOP\_**
Output: **Hello World \_STOP\_**

Is seems character "_" as part of a word sends parser into confusion.

* Version of Python: 3
* Operating System ( inc Version ): Ubuntu 16
* Sanic

**Comment by keiffster** [comment]
I'm not seeing that in the latests build, I have added the grammar
```
    <category>
        <pattern>_ _STOP_</pattern>
        <template><star index="1"></star></template>
    </category>
```
And when I ask it the question 'PLEASE DO _STOP_'
I get the response 'PLEASE DO'

The AIML spec does not support wild card _ as part of the word, instead, it treats the _ as part of the word and so matches _STOP_

**Comment by gianfrasoft** [comment]
Ok, thank you.

I think I have to update my install to the latest build.

Thank you!
