### ISSUE TITLE
Is Program-Y becoming too large

### ISSUE THREAD

**Issue by keiffster** [keiffster/program-y#221]
Program-y has grown, boy has it grown over the years. The introduction of TextBlob added a lot of features around sentiment and intent processing but came with a lot of additional steps to install.

As each client is added, it very often comes with its own libraries that not everyone wants. We now support over 15 clients, including Amazon, Google, Facebook, Telegram, Slack etc etc

I have been troubled by this for a while and over the weekend started looking at how to split up Program-y creating an eco system rather than a framework

The first part is to split program-y into core system and addons. The core elements would create the foundation of all addons and any developments anyone else would like to do. Ive already done this with extensions for Teleco, Banking, etc, so there is a model to support this

Addons would then be various categories, the biggest being clients. I would create a seperate git repo for each client, with only the neccassary libraries for that client in the requirements.txt file, ( along with programy obviously ). Programy would then only ship with console and webchat clients 

You could then install program-y, install addons such as TextBlob, and then pick the clients you would like

A lot to do, and likely to be V4.0 onwards and from the end of the year into 2020

Love to hear your thoughts ?

**Comment by ohoachuck** [comment]
I think it’s a very good idea.
O.

**Comment by Dagimtsegaye** [comment]
how can i use AIML 2.0 for python?
  pleas help. tnx

**Comment by keiffster** [comment]
Have you read the wiki ?

**Comment by keiffster** [comment]
Plans in place to restructure code based post 3.10 release
