### ISSUE TITLE
preprocessors

### ISSUE THREAD

**Issue by Algeneralo** [keiffster/program-y#222]
How can I add custom preprocessors?
Thanks

**Comment by keiffster** [comment]
It’s on the wiki


https://github.com/keiffster/program-y/wiki/Processors

Regards 

Keith
keith@keithsterling.com
07771 597630

**Comment by Algeneralo** [comment]
Where should I place my custom processor file?
And how can I integrate it with my existing program-y.
Thanks

**Comment by keiffster** [comment]
It needs to be in your PYTHONPATH so that it is loaded dynamically at startup.

You then place it in preprocessors.conf or postprocessors.conf file

Each processor is executed in the order it appears in the file, first to last



Regards 

Keith
07771 597630
