### ISSUE TITLE
Can anyone suggest how to capture specific entities asked by bot as required entity ?

### ISSUE THREAD

**Issue by Deep-09** [keiffster/program-y#224]
Issue tracker is **ONLY** used for reporting bugs. NO NEW FEATURE ACCEPTED! Use [stackoverflow](https://stackoverflow.com) for supporting issues.

 I couldn't find in documents to do so other than using wild cards 
## Expected Behavior

For example
User: book my flight?
Bot: sure.. where you want to go?
User: Singapore
Bot: from where you want to travel>
User: India
## Steps to Reproduce

1.
2.
3.
4.

## Context (Environment)

* Version of Y-Bot:
* Version of Python: 
* Operating System ( inc Version ): 

## Detailed Description

In this example I want to set two entities as 'from' and 'to'  bud could do so as wild cards are assigning  both user inputs to the same entity...
Help

**Comment by Deep-09** [comment]
For example
User: book my flight?
Bot: sure.. where you want to go?
User: Singapore
Bot: from where you want to travel>
User: India

In this example I want to set two entities as 'from' and 'to'  bud could do so as wild cards are assigning  both user inputs to the same entity...
Help

**Comment by keiffster** [comment]
You need to assign the match in each question to a variable

<category>
	<pattern>book my flight</pattern>
	<template> 
		<set name=“topic”>bookflightto</set>
		sure.. where you want to go?
	</template>
</category>

<topic name=“bookflightto>
<category>
	<pattern>*</pattern>
	<template>
		<set name=“topic”>bookflightfrom</set>
		<set name=“to"><star /></set>
		 where you want to travel?
	</template>
<category>
</topic

<topic name=“bookflightfrom>
<category>
	<pattern>*</pattern>
	<template>
		<set name=“from"><star /></set>
		Booking a flight from <get name=“from” /> to <get name=“to” />
	</template>
<category>
</topic

**Comment by keiffster** [comment]
Closed by mistake, oops. Have re opened

**Comment by Deep-09** [comment]
thanks Keith

**Comment by keiffster** [comment]
No problem, did that work for you ?

It’s a common pattern for performing a series of questions and answers and controlling flow

**Comment by Deep-09** [comment]
Yes it worked for me... I am new to AIML based chat bots and still exploring what more we can do with special tags.
