### ISSUE TITLE
postprocess after default response

### ISSUE THREAD

**Issue by ksenia1997** [keiffster/program-y#226]
Is it possible to start a postprocess if the answer is default response?

In your code I found that postprocesses would start only if the answer was matched. But may be smth exists, how to do it. 
I would like to do a syntax analysis for getting an answer if nothing was matched. So, after default answer was gotten, I would like to start another processes. 

Thanks

**Comment by keiffster** [comment]
I’ve had a look at the code and there is nothing functionally calling post process in default response

I would need to move the call to after checking if response is empty, then post process and the. Do a final check if the post process was empty and re-assign a default response.

However I think you question could be solved with a new feature that provides ability to call out to an optional extension to handle empty response.

Left me have a more detailed think about his this could work

**Comment by keiffster** [comment]
This is now in master and will be released in 3.10. I've added unit tests around the processing and storage code. Had to do a minor modification to the brain processing to handle null responses
