### ISSUE TITLE
3.9 is coming

### ISSUE THREAD

**Issue by keiffster** [keiffster/program-y#229]
It’s been a while in the planning but 3.9 has moved into final release prep. In this release

* Openchatbot support (client and server)
* Major NLP enhancements including direct support for stemming, lemmatisation, stopwords, ngrams, pos tagging and synsets. These are available as maps, sets and pre processors
* New question post processor that allows you to hand off retry of a question if the initial result is null.
* A number of bug fixes to rich media, pattern matching on _ and rest client

Should be out sometime next week

**Comment by ohoachuck** [comment]
👍

Envoyé de mon iPhone
