### ISSUE TITLE
3.9 Release

### ISSUE THREAD

**Issue by keiffster** [keiffster/program-y#230]
# 3.9 Has Been Release to Github and Pypi
Its been a while and lots of other things go in the way, but I am pleased to release 3.9 into the wild

## What's News?
* Openchatbot support (client and server)
* Major NLP enhancements including direct support for stemming, lemmatisation, stopwords, ngrams, pos tagging and synsets. These are available as maps, sets and pre processors
* New question post processor that allows you to hand off retry of a question if the initial result is null.
* A number of bug fixes to rich media, pattern matching on _ and rest client
* Support for latest version of Pip
* Updated dependencies support all latest versions

**Comment by ohoachuck** [comment]
Cool,
I'll play around with it this week-end.

O.

**Comment by ohoachuck** [comment]
Cool,
I'll play around with it this week-end.

O.
