### ISSUE TITLE
How to prioritize pattern which uses regex?

### ISSUE THREAD

**Issue by dilyararimovna** [keiffster/program-y#232]
Hello!

I have a necessity to prioritize some patterns like:
```
<pattern><regex pattern="(ALICE|BOB)" /> DO #</pattern>
```
I want the pattern above be have higher priority when matching than
```
<pattern># DO #</pattern>
```
How can I do this? In some AIML tutorials I found info about using `$` but in this case it didn't work.

**Comment by keiffster** [comment]
The $ directive only works with text strings, so you cannot apply it to other tags, however see my response to the you other issue #231. I would remove the regex pattern and replace it with 

```xml
<pattern>ALICE * DO *</pattern
```
and
```xml
<pattern>BOB * DO *</pattern
```

If you also have a catch all such as 
```xml
<pattern>* * DO *</pattern
```
Then this will come after BOB and ALICE patterns in precendence order
