### ISSUE TITLE
Ver 4.0 and Beyond

### ISSUE THREAD

**Issue by keiffster** [keiffster/program-y#237]
V4.0 of Program-y will see a major departure from previous releases. V4 is about prepping for the future and getting ready for a more commercially viable Chatbot framework but which is still 100% open source. In no particular order, V4.0 will see

- Rename from program-y to Chatilly. I’ve thought for a while that Program-y is a poor name and ties it too much to the AIML bots. Chatilly is growing and maturing and may deviate away from just being a 100% AIML chatbot
- Along with a rename, documentation and support will move to Chatilly.com. A new website that I am creating to host info, docs, news and blog
- The rename will also see the Github repo renamed
- v4.0 will see a number of code enhancements, but limited new features. The 3 major elements are
  - Unit tests to as close to 100% as possible ( this is need to support changes in 4.1 and 4.2
  - Zero Pylint errors and warnings 
  - Zero Pytype errors 

This creates a great stable foot print that will be used to drive further v4.x improvements

- v4.1 will then see the clients split into their own individual repos, this will significant reduce Chatilly footprint including massive reduction in requirements.txt for core
- v4.2 will then see individual services News, Weather, etc split into their own repos. Again reducing foot print, and also allowing a cleaner and well defined External Services ( based on sraix ) interface

**Comment by ohoachuck** [comment]
👍
