### ISSUE TITLE
Whitespace after wildcards

### ISSUE THREAD

**Issue by Thielak** [keiffster/program-y#24]
I noticed wildcards have a whitespace after them that isn't always removed.
For example this sample category
```
<category>
	<pattern>TESTSPACE *</pattern>
	<template><star />, there's a space there :(</template>
</category>
```
gives the output:

![](https://cloud.githubusercontent.com/assets/21128001/24279289/3b8c7c38-1049-11e7-8036-02a4ceb170bc.png)

Test made on a fresh clone of your master branch with the bots rosie, rosie_fixed and y-bot

**Comment by keiffster** [comment]
Its not the wildcard that is the problem, its handling of punctuation. It needs some work and is being worked on.

In terms of the pattern, everything in the sentence is a node, and all nodes are joined together with a space, I need to strip out unused spaces when they correspond with a punctionation mark such as , or .

The short term for this is to wrap it with a <implode> tag 

<template><implode><star />,</implode> there's a space there :(</template>

You won't need to remove this once I've fixed it, as it will have nothing to implode, but for now it will solve your problem

K

**Comment by keiffster** [comment]
Check out 0.6.0, fixed spaces before and after punctuation where appropriate

An added benefit of this is that I have also sorted out spacing between quotes

**Comment by Thielak** [comment]
>The short term for this is to wrap it with a tag
, there's a space there :(

Github eats tags, unless you either escape the \< and \> with a \\ or you put it in a \<code\> tag.
I won't need the advice as the issue was indeed fixed on the latest release, thank you again for your work!
