### ISSUE TITLE
Incompatibility between Program-Y and Sanic

### ISSUE THREAD

**Issue by gianfrasoft** [keiffster/program-y#242]
We installed the latest version of both Program-Y and Sanic (pip install).

The two software are no more compatible. For example:

in the source file "src/programy/clients/restful/sanic/client.py" the signature:

`    def create_response(self, response, status_code, version=1.0)
`

it calls:

```
    @APP.route('/api/rest/v1.0/ask', methods=['GET', 'POST'])
    async def ask(request):
        response, status = REST_CLIENT.process_request(request, version=1.0)
        return REST_CLIENT.create_response(response, status=status, version=1.0)

    @APP.route('/api/rest/v2.0/ask', methods=['GET', 'POST'])
    async def ask(request):
        response, status = REST_CLIENT.process_request(request, version=2.0)
        return REST_CLIENT.create_response(response, status=status, version=2.0)

```
using "status" parameter name instead of "status_code" parameter name.

But there could be other incompatibilities.

Have you plans for supporting the Sanic client for Program-Y in the future?

Thank you!

**Comment by keiffster** [comment]
Let me take a look at see what I did

I’ll get a fix onto master in the next 24 hours or so

**Comment by keiffster** [comment]
Just pushed a fix to master, and tested it working with Sanic

Apologies introduced a typo when refactoring the Flask and Sonic clients

K
