### ISSUE TITLE
Duplicated method in Weather Service

### ISSUE THREAD

**Issue by acriptis** [keiffster/program-y#247]
Hello @keiffster 
It seems code accidentally duplicated here:
https://github.com/keiffster/program-y/blob/master/src/programy/utils/weather/metoffice.py#L555-L559

**Comment by keiffster** [comment]
Thanks, I’ll remove one of then shortly 

Regards 

Keith
07771 597630

**Comment by keiffster** [comment]
Fixed and will be released in v4
