### ISSUE TITLE
<learnf> tag not working

### ISSUE THREAD

**Issue by newdev7** [keiffster/program-y#25]
I have tested both the `<learn>` and `<learnf>` tag in the latest version 0.6.0

The `<learn>` tag is working as expected but not the `<learnf>` tag. The given message is working for the particular conversation in both the tag.

While using the `<learnf>` tag, learnf.aiml file was created in the aiml folder. But the `<template>` looks like the same in the original template.

Check the following example. I added category like this.

```
<category><pattern>* PLAYED *</pattern>
	<template>Ok. I will remember this
		<learnf><category><pattern>WHAT DID <eval><star/> PLAY</eval></pattern>
			<template><eval><star/></eval> PLAYED <eval><star index="2"/></eval></template>
		</category></learnf>
	</template>
</category>
```

If I give `John played Cricket`, it returned `Ok. I will remember this`. In the next message I gave `What did John play`, it returned `John played Cricket`. I closed the conversation and ran again. Now I asked `What did John Play`, it returned `Played`.

I checked the learnf.aiml file. It has the following code.
```
<aiml>
<category><pattern>WHAT DID JOHN PLAY</pattern><topic>*</topic><that>*</that><template><eval><star /></eval> PLAYED <eval><star index="2" /></eval></template></category></aiml>
```

Can you please check this and fix this issue. Thanks.

**Comment by keiffster** [comment]
Thats now fixed in the master master.

Learnf was writing the raw aiml tag that is used to create the actual grammar, rather than writing the actual grammar to the file

New tests in test_learnf.py which now includes JOHN PLAYED CRICKET

**Comment by newdev7** [comment]
Thanks @keiffster the <learnf> tag is now working without any issues.
