### ISSUE TITLE
reload rdf fname - causes emptying of entire rdf collection instead of just file collection

### ISSUE THREAD

**Issue by lspy** [keiffster/program-y#252]
Hi
Trying reload of a single RDF file by calling YADMIN RELOAD RDF *filename*

Expect to empty just the collection specific to the *filename* with in the RDFstore, but see that the entire RDFstore is emptied.  I only find just the *filename* reloaded.

Suggestion for a possible Solution: 
In file ..program-y\src\programy\storage\stores\file\store\rdfs.py 
in the method reload() below

 def reload(self, collection, rdf_name):
        filename = collection.storename(rdf_name)
        collection.empty()  _### should be filename.empty()_
        return self._load_file_contents(collection, filename)

Thank you very much for Program-Y, it is an exciting project to play with!  Appreciate it very much!

**Comment by keiffster** [comment]
Yeap, spot on the call to empty at line 58 clears out the entire ref store, I’ll fix and release shortly

**Comment by lspy** [comment]
Great.  Look forward to the release. thanks

**Comment by lspy** [comment]
Hi @keiffster is there an ETA for the release?  Thanks in advance

**Comment by keiffster** [comment]
Just finished the fix, will likely release a point release tonight after 7pm GMT

**Comment by lspy** [comment]
Great. Will look out for it.

**Comment by keiffster** [comment]
Uploaded code to GitHub and release 4.1.1 to pypi
