### ISSUE TITLE
Embedding vs Template-y

### ISSUE THREAD

**Issue by impulsecorp** [keiffster/program-y#253]
What is the difference between embedding a bot (https://github.com/keiffster/program-y/wiki/Tutorial-Embedded-Bots) and using Template-y (https://github.com/keiffster/template-y) , for the purpose of creating my own custom AIML files for the bot? I am using y-bot-flask-rest.sh to serve my bot on an Ubuntu server.

I have not upgraded program-y in 2 years exactly for the reasons you talk about on your Template-y Github page. bAt this point though, I think I will start over and install your latest version from scratch and then customize my bot from there, instead of upgrading.

**Comment by keiffster** [comment]
Hey, great question, basically the embeddable bots were created to allow people to get started quickly, and who need to know the absolute minimum of AIML and Program-y configuration. This is ideal for people who are using non Flask frameworks ( e.g Django ) or platforms ( e.g Horuku ).

Template-y is for those who want to get the most out of Program-y and use as many of the features it provides such as the Schedule, NLP, Spelling and also SQL or Mongo storage. If you are using Template-y today and it's working for you, stick with it, I will keep embedded client and template-y up to date for as long as I continue to develop programy

K

**Comment by impulsecorp** [comment]
https://github.com/keiffster/program-y/wiki/Tutorial-Getting-Started

**Comment by impulsecorp** [comment]
I am unclear though why I would need Template-y if all I am doing is editing the AIML files to create my own bot. I only edit the AIML, not the set, map and rdf files. I downloaded the AIML files using  "python3 -m programy.admin.tool download y-bot" but each time I upgrade program-y I do this:
"sudo pip3 install programy --upgrade"
Doing that upgrade does not change the y-bot AIML files does it, so how would using Template-y help me?

**Comment by keiffster** [comment]
You are right if all you want to is is edit aiml files then you might be as well off with embedded clients

One of the ground rules of programy is to be as flexible as possible and that sometimes means having more than one way of doing something 

If ember works for you for for it. However there is nothing g lost and if you find you need some of the advanced features all of you files will work with template-y
