### ISSUE TITLE
Program-y version question

### ISSUE THREAD

**Issue by impulsecorp** [keiffster/program-y#254]
I did a fresh pip install today of program-y on my Ubuntu server and it works fine from the console using ./y-bot.sh but when it starts it says "Y-Bot, App: v3.9 Grammar v1.6.0, initiated March 14, 2017".

Shouldn't it be using v4.1.1 ?

**Comment by impulsecorp** [comment]
Never mind, I see now, that version display is a setting in my properties.txt file, so I need to update the text there.

**Comment by keiffster** [comment]
My bad, looks like my build script has broken which normally updates that property
