### ISSUE TITLE
Healthcheck Feature Suggestion

### ISSUE THREAD

**Issue by impulsecorp** [keiffster/program-y#256]
Similar to your Healthcheck feature (https://github.com/keiffster/program-y/wiki/Client-Healthcheck), it would be nice if program-y had a true/false type option in the config file (such as config.flask.rest.yaml) where it would automatically restart the chatbot if it detects it is down.  It would have a parameter to set how often it checks, like once an hour for example. 

I don't really care that much about current Healthcheck info, because I can already see that in the log files. I just want to make sure the chatbot is always running.

**Comment by keiffster** [comment]
Good idea, I’ll add it to the backlog

I am over hailing the entire health check section later this year to create a much richer rest based admin Interface

The plan is allow full control via a rest api if a running bot
