### ISSUE TITLE
Pip dependency issues still exist

### ISSUE THREAD

**Issue by MikeyBeez** [keiffster/program-y#259]
Thank you very much for sharing this very interesting code.  I've built the github repository, but I'm having trouble with pip install.  Here's what I entered:
from within a python 3.7 miniconda environment

conda create --name jbot --no-default-packages python=3.7
conda install webencodings
python3 -m pip install programy  

I get the following errors:

ERROR: kik 1.5.0 has requirement six==1.10.0, but you'll have six 1.14.0 which is incompatible.
ERROR: botframework-connector 4.8.0 has requirement cryptography==2.8.0, but you'll have cryptography 2.9.2 which is incompatible.
ERROR: botframework-connector 4.8.0 has requirement PyJWT==1.5.3, but you'll have pyjwt 1.7.1 which is incompatible.

also webencodings seems to be necessary but not in requirements file.
Miniconda environment
Ubuntu 18.04
programy 4.3

BTW, tried uninstalling the offending modules then rerunning the pip install.  That didn't work; so I assume your requirements file is messed up.  Maybe it will run anyway.  I'll give it a try.

**Comment by MikeyBeez** [comment]
BTW, it's most simple implementation is running:
❯ python3
Python 3.7.7 (default, Mar 26 2020, 15:48:22) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from programy.clients.embed.basic import EmbeddedBasicBot
>>> 
>>> my_bot = EmbeddedBasicBot()
>>> print("Response = %s" % my_bot.ask_question("Hello"))
Response = Good morning.
>>>

**Comment by keiffster** [comment]
I’m working through those pip issues

They don’t cause any problems, I’ve tested all clients after install and while the 2 libraries are incompatible in some respects, I have found any issues so in terms of program-y they are compatible

Next release or so will move all clients into their own got repos and own installs which fixes the problem once and for all

Interesting about webencodings, I don’t directly use it so need to look at what is pulling it in, but until then I’ll add it to requirements.txt for now

Regards 

Keith
07771 597630

**Comment by keiffster** [comment]
Great news, enjoy

Regards 

Keith
07771 597630

**Comment by MikeyBeez** [comment]
I suspect that kik is causing the trouble, and they need to fix it there.  I'll check for issues on their repository.

**Comment by MikeyBeez** [comment]
They aren't open source; so I can't check their issues.  That's a problem right there.  One can't look at their code.
