### ISSUE TITLE
File-based map is not working

### ISSUE THREAD

**Issue by sarbashis** [keiffster/program-y#260]
Issue Tracker can be used for report issues and new features. All requests will be accepted, reviewed and responded
to. However submitting a request for a new feature does not guarantee that it will be implemented, but we will
commit to responded with 7 working days if a new feature will be added to the backlog. 

You can see the full backlog in Trello at [Programy Backlog](https://trello.com/b/ksToL3tX/chatilly)

I was trying to run the file-based map function example mentioned here
https://github.com/keiffster/program-y/wiki/Tutorial-Maps
but could get the expected result

## Expected Behavior

>>> I live in the United Kingdom
Cool, have you been to the capital city London?
>>> 

## Current Behavior

What's living in the United Kingdom like living in the United Kingdom?

## Steps to Reproduce

 I copied this example in a new test.aiml file but could not get the output

```
<?xml version="1.0" encoding="UTF-8"?>
<aiml version="2.0">
    <category>
        <pattern>I AM FROM THE *</pattern>
        <template>
             Cool, have you been to the capital city <map name="nation2capitol" />?
        </template>
    <category>
</aiml>
```

## Context (Environment)

* Version of Program-y: 4.3
* Name and Version of Bot: y-bot App: v3.9 Grammar v1.6.0
* Version of Python: 3.7
* Operating System ( inc Version ): mac 10.15.2

**Comment by keiffster** [comment]
Error in the documentation, that has been updated. you nee do change the lin

```
Cool, have you been to the capital city <map name="nation2capitol"><star /></map?
```
to

```
Cool, have you been to the capital city <map name="nation2capitol" />?
```
