### ISSUE TITLE
When I create dialog for a bot, bot don't see more than one sentence

### ISSUE THREAD

**Issue by Sokolkk** [keiffster/program-y#261]
#aiml code
    < category>
        < pattern>Typical! You ^</ pattern>
        < template>
            Correct: "Typical! You are always leaving the lights on."
        </t emplate>
    </ category>

#i print 2 sentences, bot gives the answer, how 2 errors:
>>> Typical! You are always leaving the lights on."
Something is wrong. Something is wrong.

#it not aiml mistake - this restriction on recognizing only one input sentence ! How fix limit on input sentences?

**Comment by keiffster** [comment]
The character ! is a sentence splitter so the bit sees you input as to sentences and do it processes Typical and then it process you always leave the lights on
