### ISSUE TITLE
The bot removes parenthesis

### ISSUE THREAD

**Issue by EdvinJakobsson** [keiffster/program-y#263]
Hi.
I am trying to use the y-bot to catch specific patterns and return the matched wildcards unchanged, however the bot seems determined to alter the text before returning it, for example removing parenthesis.

## Expected Behavior
For example, if I use a pattern like this:
` 
<category>
        <pattern>REPEAT_THIS #</pattern>
        <template><star /></template>
    </category>
`
and when I say: 'REPEAT_THIS install (optional)'
I want the bot to return:
'install (optional)'

but instead I get:
''Install optional.'

I have tried commenting out all the postprocessors and preprocessors, but that didn't change anything. Is there a simple solution to this? I want to be sure that the bot always return the whole string exactly as it came in.

Kind regards,
Edvin

**Comment by SunilGudivada** [comment]
@EdvinJakobsson you can find all the denormalized list in the `~/storage/lookups/denormal.txt`
