### ISSUE TITLE
Do we have any way to load only specific aiml files ? After starting the client. 

### ISSUE THREAD

**Issue by SunilGudivada** [keiffster/program-y#267]
I want to load the specific AIML file instead of reloading all the AIML files.

**Comment by keiffster** [comment]
Yes change dirs config option to file and give a file path to the aiml instead of a directory

So change

categories:
    dirs: path/to/aiml-files

To

categories:
    file: path/to/single/aiml-file

**Comment by SunilGudivada** [comment]
What if the settings are SQL. 

Can you please tell me how it works in case of SQL. 

If dynamically feed the content in the SQL tables. Will it automatically take the content without restarting the client service?

**Comment by keiffster** [comment]
No that’s not possible at the moment, if you want to work with individual files use file mode

Or use sql for all but aiml and use file just for the aiml file


Regards 

Keith
07771 597630

**Comment by SunilGudivada** [comment]
Is there a way to reload the brain ?

I am creating the aiml files in the storage folder, and reloading the files in the database using 

`    Uploader.upload('categories', AIML_DATABASE_URI, None, 'storage/categories',  True, '.aiml', True, False, True)
`

Do we have any way to load the brain without restarting the client ?

**Comment by keiffster** [comment]
Yes, take a look at the admin aiml in y-bot there are aiml commands to reload all data elements
