### ISSUE TITLE
How to change webpage for Template Y-bot

### ISSUE THREAD

**Issue by rutu14** [keiffster/program-y#279]
I am currently making my own bot using the template one. I would like to modify the webchat.html but it does not show any changes when running on localhost.

**Comment by keiffster** [comment]
Is this still an issue for you ?

**Comment by rutu14** [comment]
Yes and I tried to modify the webpage through anaconda site-packages folder but not the template-y-master, so the issue remains unsolved.
And one more issue is after changing the templatey to nameofproject in scripts folder, it shows as follows:
![image](https://user-images.githubusercontent.com/51828157/110637954-fac18080-81d3-11eb-9fe3-338e6e0cb2bb.png)

**Comment by keiffster** [comment]
You will not be able to change the client in site-packages. You can install program-y via pip install, but template-y should be downloaded to you local folder and modified there

**Comment by rutu14** [comment]
i have installed program-y and made a template-y but no modifications are happening in downloaded template-y

**Comment by rutu14** [comment]
the above screenshot issue happens when in scripts folder, in the template-webchat.cmd file ,the name is changed from templatey to nameof proj
 
![image](https://user-images.githubusercontent.com/51828157/110778116-f5257280-8287-11eb-83a0-bc33938bccea.png)
So i suppose if this issue is solved the webpage can be modified too.
