### ISSUE TITLE
<response> tag not working

### ISSUE THREAD

**Issue by newdev7** [keiffster/program-y#28]
Look at this category,
```
<category><pattern>CAN YOU REPEAT THAT</pattern>
<template>I said, <response/>.</template>
</category>
```

In the conversation, I tested like this.
```
Hi, how can I help you today?
>>> hello
Hi! It's delightful to see you.
>>> can you repeat that
I said,.
>>> 
```

The `<response>` tag didn't return any text. It just returned the empty text. Can you please check this.

Thanks.

**Comment by newdev7** [comment]
Hey @keiffster I tried to debug the python code. You are trying to get the recent input in the conversation for `<response>` tag. But the recent input is not the response it is the request. So instead of bots answer it tried to get the response from user question. So it returned the empty string.

I have changed the value of the integer `nth_question` to `self.index+1`. Now it is returning the correct answer for the `<response>` tag.

**Comment by keiffster** [comment]
Do you want to submit a pull request and I'll add the fix, or just send me the code and I'll patch it manually ?

<respnse> is not a tag I regularly use, ( if at all ), so maybe not tested as well as it could be

K

**Comment by newdev7** [comment]
In the `response.py` file under `TemplateResponseNode` class, I've changed the code in `resolve` function. This is the original code.
```
    def resolve(self, bot, clientid):
        try:
            nth_question = self.index
            conversation = bot.get_conversation(clientid)
            question = conversation.nth_question(nth_question)
            responses = question.combine_answers()
            resolved = responses
        except Exception as excep:
            logging.exception(excep)
            resolved = ""
        logging.debug("[%s] resolved to [%s]", self.to_string(), resolved)
        return resolved
```

Here I have changed the value of `nth_question` to `self.index+1`

**Comment by keiffster** [comment]
Fix added and uploaded to master, I've also marked the fix with your username so that you get a credit

Have a look at how to create a pull request. If you are actively testing or developing the code, then pull requests are a great way to contribute. They won't get added to the code until I review and approve them so you'll never break anything, and you'll get the credit for your contributions

K
