### ISSUE TITLE
"." (dot) in the middle of a sentence trigger 2 requests. Any way the disable this ?

### ISSUE THREAD

**Issue by ohoachuck** [keiffster/program-y#280]
Hello,
quick question, when a request have a "." (dot) between 2 sentences, it's being considered as 2 requests.

For instance : 
```
[question]: Hello. What time is it ?
[answer]: The time is 07:42 PM.
```

Any idea how to prevent that ?
I had a look at processors, but I don't think this is the route ?

O.

**Comment by keiffster** [comment]
It’s the sentence splitter which does that. You would either remove the the dot before splitter or remove the splitter via the config setting

**Comment by ohoachuck** [comment]
Thanx, I’ll check this.

O.

Envoyé de mon iPhone

**Comment by ohoachuck** [comment]
Thank you Keith,
this is exactly what I needed ! 
Just pointing to your documentation references for others that might have the same question:
https://github.com/keiffster/program-y/wiki/Sentence-Splitting

O.
