### ISSUE TITLE
ImportError: No module named 'yaml'

### ISSUE THREAD

**Issue by UltimateHackers** [keiffster/program-y#29]
`Traceback (most recent call last):
  File "../../src/programy/clients/console.py", line 3, in <module>
    from programy.clients.clients import BotClient
  File "/root/y/src/programy/clients/clients.py", line 22, in <module>
    import yaml
ImportError: No module named 'yaml'`

I tried yaml to pyyaml but it didn't help. Moreover, after changing it to pyyaml it said "No module named pyyaml" but pyyaml is installed
Please fix this asap possible.

**Comment by keiffster** [comment]
Sounds like you do not have PyYaml installed in your environment

import yaml is the defined way of using PyYaml after installation

See http://pyyaml.org/wiki/PyYAMLDocumentation

Typically you download and install PyYaml or install it via Pip

K

**Comment by UltimateHackers** [comment]
pyyaml is already installed as I have mentioned earlier.

**Comment by jayhewitt** [comment]
@UltimateHackers did you install using pip?

If you do `pip freeze` does it list PyYaml? Looking at other articles, it looks like this module can cause issues and install with a success response, whilst not compiling properly.

e.g.
https://github.com/bokeh/bokeh/issues/4089

**Comment by keiffster** [comment]
Have the clients running both inside my ide ( pycharm ) and also command line ( OS X ) and not getting any problems

What os are you using and which exact version of python ?

How are you starting the client ?

**Comment by JustArchi** [comment]
Probably an issue on your end, I'm running program-y perfectly fine myself as well.

**Comment by UltimateHackers** [comment]
I am using Kali Linux.
And yes, pip freeze does shows the pyyaml module.
I tried running y-bot by executing the y-bot.sh file.

**Comment by Thielak** [comment]
The problem is definitely on your end.
You might not have installed pyyaml for your python3 environment as `pip` is probably defaulting to your python2 one. Check `pip3 freeze` to see if it's there, if not `pip3 install` it (you might want to install the other required modules as well).
If you don't have the command `pip3` available install the `python3-pip` package to use it.

**Comment by UltimateHackers** [comment]
So its not a fault of your script :+1:  But if it doesn't run on my Kali, it won't run on anyone's Kali.
I tried installing python3-pip package but it won't install because my system is up to date and python3-pip needs to downgrade some dependencies.
Thanks for the quick response and help.
