### ISSUE TITLE
<learn> and <star> don't work together 

### ISSUE THREAD

**Issue by LazyRacc00n** [keiffster/program-y#292]
I'm implementing a chatbot which should use the <learn> ( and also <learnf>) and <star> like in the following pattern:

><category>
	<pattern>* IS SYNONYM OF *</pattern>
	<template>
		<learnf>
			<category>
				<pattern><eval><star index="1" /></eval></pattern>
				<template>
					<srai><eval><star index="2" /></eval></srai>
				</template>
			</category>
		</learnf>
	</template>
</category>

So if I define this simple pattern 

> <category>

	<pattern>HI</pattern>
	<template> Nice to meet you! </template>
</category>

and the user types `hello is synonym of hi`, then the `hello` should trigger the response `Nice to meet you!`.
As matter of fact this doesn't work, even if it works properly on the online Pandorabot editor.
It seems that the <eval><star><eval> doesn't retrieve the related words. 

Are there alternative ways to implement a pattern that behaves like I want?

**Comment by keiffster** [comment]
The way to do it in program-y is with set and get, so the grammar needs to be

   <category>
        <pattern>* IS SYNONYM OF *</pattern>
        <template>
            <think>
                <set name="firstword">
                    <star/>
                </set>
                <set name="secondword">
                    <star index="2"/>
                </set>
            </think>
            <learnf>
                <category>
                    <pattern>
                        <eval><get name="firstword"/></eval>
                    </pattern>
                    <template>
                        <srai><eval><get name="secondword"/></eval></srai>
                    </template>
                </category>
            </learnf>
        </template>
    </category>


This is because the <star> evaluation is in scope of the learnf clause, but set and get are wider scope
