### ISSUE TITLE
Spacing after cleanup

### ISSUE THREAD

**Issue by Thielak** [keiffster/program-y#30]
I noticed that after the change in cleanup.py https://github.com/keiffster/program-y/commit/134eb73d8c53a71e6cd6f34b17a91266d69c88e1#diff-a9aa9e742ec99f1936ff8c8aa2c4b9d7 there's a weird issue with spacing that occurs at the cleanup stage before the output is sent to the user.
As you can see the phrase is still intact after the denormalization, but spaces are added at cleanup

![image](https://cloud.githubusercontent.com/assets/21128001/25059214/9c029f62-2182-11e7-9352-c633985ca43d.png)

**Comment by keiffster** [comment]
Ok I'll take a look over Easter and see what the problem is

**Comment by keiffster** [comment]
Back from vacation, I'm am currently taking a look at this along with refactoing the implications of upper and lower case text throughout the system

I'm thinking about a weeks time I'll have a solution which solves both

**Comment by keiffster** [comment]
Check out the latest release on master I've just pushed this afternoon. Updated the pre and post cleanup o[erators which now deal with punctuation and quotation much better

**Comment by Thielak** [comment]
Thank you for taking the time to look into it, now it works much better!
