### ISSUE TITLE
Cant find y-bot.sh

### ISSUE THREAD

**Issue by mishiki1002** [keiffster/program-y#31]
I have been following your tutorial on the wiki page and can't seem to find the y-bot.sh you talk about. Has this feature been removed, or do i need to make it. If i need to make what do i need to do. I have done some light searchin inside of your files and havnt found much to replicate the y-bot.sh (But i did not look hard). I will continue to look.

**Comment by Thielak** [comment]
It's in `program-y/bots/y-bot/y-bot.sh`

**Comment by mishiki1002** [comment]
Thank you

**Comment by keiffster** [comment]
Is this now working
