### ISSUE TITLE
Spaces in set members cause non-recognition

### ISSUE THREAD

**Issue by ideasean** [keiffster/program-y#35]
It seems a space in a set element mean its not recognised as a set member. Take these examples with Y-Bot. All these colors are in the color.txt file.

Me- my favorite color is blue
Bot- Blue is a nice color.
Me- my favorite color is air force blue
Bot- I didn't recognize AIR FORCE BLUE as a color.
Me- my favorite color is  alice blue
Bot- I didn't recognize ALICE BLUE as a color.
Me- my favorite color is ash grey
Bot- I didn't recognize ASH GREY as a color.
Me- my favorite color is Alizarin
Bot- I didn't recognize ALIZARIN as a color.
Me- my favorite color is auburn
Bot- Auburn is a nice color.

Thanks Keith (sorry about several edits - default output was causing issues with Markdown :-) )

**Comment by keiffster** [comment]
Its a bug, I can see where its happening and need to fix the code

**Comment by keithsterling-FD** [comment]
New branch has just been pushed MultiSpaceSet which should fix this issue. 
Sets are now loaded into a dict key'd on the first work, all sets phrases are then stored as arrays ordered by length in reverse order
Search is to find the first work of the set, then check for each set phrase, ultimately reducing down to the smallest possible phrase, typically a 1 word value
Pushed as a branch for now as number of people have asked for this. Will continue to check and add unit tests before merging to master in 0.9.0

**Comment by keiffster** [comment]
Branch merged and released to master
