### ISSUE TITLE
Case sensitivity in THAT tag

### ISSUE THREAD

**Issue by ideasean** [keiffster/program-y#36]
It seems THAT is case sensitive. Take the following code. If the first instance `ARE YOU A TESTCASE` is uppercase, THAT matches. If its lowercase, THAT doesn't match. 

<?xml version="1.0" encoding="UTF-8"?>
<aiml>

    <category>
        <pattern>TESTCASE *</pattern>
        <template>HELLO <star index="1"/> ARE YOU A TESTCASE</template>
    </category>
  
    <category>
        <pattern>YES #</pattern>
        <that>* ARE YOU A TESTCASE</that>
        <template>Got Yes</template>
    </category> 

    <category>
        <pattern>NO #</pattern>
        <that>* ARE YOU A TESTCASE</that>
        <template>Got No</template>
    </category>
   
</aiml>

**Comment by keiffster** [comment]
Yes, THAT is case sensetive as its based on exactly what you type in.

Case is an issue I am working on, and I need to

a) Preserve case on the input to support STAR
b) Ignore case when matching PATTERN and THAT

Work in progress at this time

**Comment by keiffster** [comment]
Now fixed in master, because pattern and star now preserve case, it also means that the original implementation of that as case sensitive now holds true
