### ISSUE TITLE
STAR tag output always converted to uppercase

### ISSUE THREAD

**Issue by ideasean** [keiffster/program-y#37]
It seems that STAR tags convert text to uppercase. Is this expected behavior? I understand its easier for matching, however for actual output can the original case be preserved?

Example from AIML 2:

```
Human: My favorite color is Paris in the spring
Robot: I didn't recognize Paris in the spring as a color.
```

**Comment by keiffster** [comment]
Yeap, a known issue and a fix is being worked on, linked to the other issue you raised about all matching in upper case. When I change that one, this one will fix itself

**Comment by keiffster** [comment]
Now fixed in master
