### ISSUE TITLE
Support pip3 installation?

### ISSUE THREAD

**Issue by hanfeisun** [keiffster/program-y#39]
Would it be possible to support pip3 installation for this repo?

**Comment by acondori** [comment]
I just was wondering the same, I pulled the repo but ,,,How a load this repo as executable python library? 

When  I try to test some file I received:

> Traceback (most recent call last):
>   File "./programy/clients/console.py", line 3, in <module>
>     from programy.clients.clients import BotClient
> ImportError: No module named 'programy'

Thanks a lot!

**Comment by keiffster** [comment]
In on the backlog, but program-y needs a certain amount of configuration and data files, so right now is not practical as just an installable python library

Check out the wiki, specifically Installation, Configuration and Running sections in the side bar to see how to download from github, install python dependencies, configure a bot and then run it

**Comment by ideasean** [comment]
I am not big on Linux but got it working just following what Keith wrote in the install and config notes, and making sure paths were correct. For Windows you need to write a CMD file to set the path before running the command line. Below is an example y-bot.cmd file:

```
SET PYTHONPATH=y:\program-y\src;y:\program-y\libs\MetOffer-1.3.2;Y:\program-y\bots\y-bot

py y:\program-y\src\programy\clients\console.py --bot_root y:\program-y\bots\y-bot --config y:\program-y\bots\y-bot\config.yaml --cformat yaml --logging y:\program-y\bots\y-bot\logging.yaml

```

Note I use SUBST to map Y: to where I cloned Program-Y in a C drive folder, just to make it easier to work with. You could also use %CD% to avoid hard coding a directory path.

**Comment by keiffster** [comment]
Check the documentation, I've updated the Installation and Running pages of the wiki to provide a bit more information on how to run the bot. 

Best way is to navigate to one of the bot folders Alice2 or Y-Bot and run one of the shell scripts which do everything for you

**Comment by acondori** [comment]
Thanks a lot! I was lose but now I can see more clear! cheers!

**Comment by keiffster** [comment]
Pip3 on the roadmap, as no outstanding issue, close for now

**Comment by TudosaOvidiu** [comment]
Hi i'm trying to install program-y but I'm getting this error:
Traceback (most recent call last):
  File "C:\Users\Ovidiu\Desktop\program-y\src\programy\clients\console.py", line 20, in <module>
    from programy.clients.client import BotClient
ModuleNotFoundError: No module named 'programy'

Any ideas what this is about?

**Comment by keiffster** [comment]
Going to need a bit more info to help

1) Which bot are you running
2) Which script are you running to run the bot 
3) What operating system are you running

First glance it looks like the PYTHON path is not set,
