### ISSUE TITLE
ImportError: No module named 'programy'

### ISSUE THREAD

**Issue by aiclown** [keiffster/program-y#40]
Hey,

This is what I get when I follow the instructions in the wiki to get it running. Everything seems to be in order, but still:

> python3 ./programy/clients/console.py
Traceback (most recent call last):
  File "./programy/clients/console.py", line 3, in <module>
    from programy.clients.clients import BotClient
ImportError: No module named 'programy'

**Comment by keiffster** [comment]
How are you running the client and which client are you running. Which OS /

Seems like PYTHONPATH is not set which would suggest you are not using the .sh script which sets the PYTHONPATH before running the client

K

**Comment by keiffster** [comment]
Looks like the documentation could be a lot clearer, I've changed the wiki page to direct you to using one of the scripts to run the console app

**Comment by aiclown** [comment]
Hey, keiffster
I'm on a Raspberry pi 2/Raspbian. Thanks for the wiki update. Got it working now, but I had to
 _pip3 install python-dateutil and _pip3 install wikipedia_. 
Let the fun begin! :)

**Comment by keiffster** [comment]
Just reminded me to add another section to the Running page about running pip3 -r requirements.txt

```
Make sure you have all of the required Python dependencies installed. This is done using python3-pip and the requirements.txt file

    python3-pip -r requirements.txt
```
