### ISSUE TITLE
<set var=”abc”/><srai><get var=”abc”/></srai> does not redirect to <pattern>#</pattern> or <pattern>^</pattern>

### ISSUE THREAD

**Issue by keithsterling-FD** [keiffster/program-y#42]
<set var=”abc”/><srai><get var=”abc”/></srai> does not redirect to <pattern>#</pattern> or <pattern>^</pattern>

Reported by Denis Kamotsky

**Comment by keiffster** [comment]
Now fixed in current master, tests showing working example available in

./src/test/aiml_tests/srai_set_tests/
