### ISSUE TITLE
Even if I have ? as a sentence separator character, input HELLO? will not match to <pattern>HELLO</pattern>

### ISSUE THREAD

**Issue by keithsterling-FD** [keiffster/program-y#43]
Even if I have ? as a sentence separator character, input HELLO? will not match to <pattern>HELLO</pattern>

Reported by Denis Kamotsky

**Comment by keithsterling-FD** [comment]
Fixed in latest master.

Preprocessor called RemovePunctionaPreProcessor added to the code base, and all bot preprocessors.conf

**Comment by keiffster** [comment]
Released on master
