### ISSUE TITLE
Issues with UDC pattern

### ISSUE THREAD

**Issue by keithsterling-FD** [keiffster/program-y#44]
UDC <pattern>*</pattern> does not seem to be triggered for single-word input not matched by any other pattern. I was forced to change UDC to <pattern>^</pattern>, only then it triggered for single-word input unmatched by any other pattern

**Comment by keiffster** [comment]
Ok, I can reproduce this using the test grammar

<aiml>

	<category>
		<pattern>*</pattern>
		<template>
		    UDC Star Response
		</template>
	</category>

	<category>
		<pattern>* THIS</pattern>
		<template>
		    This Response
		</template>
	</category>

	<category>
		<pattern>THAT *</pattern>
		<template>
		    UDC That Response
		</template>
	</category>

	<category>
		<pattern>THE * OTHER</pattern>
		<template>
		    UDC THE OTHER Response
		</template>
	</category>

</aiml>

I'll work through it and see why its not working

**Comment by keiffster** [comment]
Now fixed in master

**Comment by keiffster** [comment]
Now released in master
