### ISSUE TITLE
Authorisation framework for bot...

### ISSUE THREAD

**Issue by ideasean** [keiffster/program-y#53]
As mentioned in #51 , Program Y assumes that if you can reach it, you can use it. In a Skype For Business enterprise context, I need to check if the user connecting -

- Is a known user and is allowed to use the bot
- Is permitted to use all or only some services
- Is a super-user who can ask questions like who is connected to the bot right now, service online/offline commands, send a message to all connected users, or even tell the bot to quit gracefully.

For now I have only implemented point 1. Here's my approach:

Created an authorisation pre-proccessor along these lines - 

```
if ServiceFactory.get_service("authservice").checkUserAuth(bot,clientid):
  question  = string
else:
  question = "CheckUserAuthFailed " + clientid
```
CheckUserAuthFailed then points to a grammar along these lines:

```
   <category>
        <pattern>CHECKUSERAUTHFAILED #</pattern>
        <template>Your user-id  '<star/>' failed authorisation 
                           - sorry I can't help you yet!</template>
    </category>

```

The authservice is just another service defined along normal Program-Y guidelines. The idea is future authorisation checks can be done via service calls or grammar. 

In the authservice, I then maintain a list of currently authorised users. 
```
self.authorisedUsers = {} 
self.authorisedUsers['CONSOLE'] = "basic"

```
(This assumes that someone using the CONSOLE app must have general access)

Then, when checkUserAuth is called - 

```
if clientid.upper() not in self.authorisedUsers:
  if self._api.AuthUser(bot,clientid):
    self.authorisedUsers[clientid] = "authenticated"
    result = True

```
The AuthUser API does the back-end service call to actually check the user is known, for example against the ticket system or in an Active Directory. This way the user is not re-authenticated against the master every time they ask a question. 

Next steps are to flesh out the role / service-level authorisation model. 

If there are any thoughts / comments / ideas / problems with the above approach, please do comment :-)

**Comment by keiffster** [comment]
Looks like a good approach, and further thinking I agree that an auth framework would be a good approach.

Previous Bots have relied on different approaches. The last one I built provided Web, SMS, XMPP and Twitter. it required you to register SMS, XMPP and Twitter info and we would then use the credentials embedded in the sent data to see if you should be allowed and for Web, you first had to log onto the website customer account section which left a cookie with your credentials that we could use. 

All of these options allowed non authenticated comms for general questions, but if you asked account specific and failed auth you were told to either log into the web client or register your credentials

**Comment by keiffster** [comment]
I've now started on the authentication framework, new branch authserv contains the code for now until we agree and merge

**Comment by keiffster** [comment]
So I moved forward with this and now have authentication and authorisation frameworks in place

Authentication is as above following your pattern for using the pre-processor which once I'd implemented it seems the logical place. as authentication should be for every request

Authorisation, however, is likely to be on a per command or group of commands and as such I've implemented a User, Roles and Groups capability and introduced a new tag <authorise>

Basically, Users have Roles, Groups have Roles, User can belong to Groups and Groups can contain Groups. This gives a flexible approach to applying authorization rules to different collections of people.

There is also a new tag <authorise> which you wrap a template in which first checks if the user is authorised to execute the template using the above Users, Roles and Groups, e.g

<template>
   <authorise role="sysadmin">
           <srai>LIST ACTIVE USERS</srai>
   </authorise>
<template>

So when the parser gets to this template, it checks that the user defined by clientid, has the role of "sysadmin" either directly or through associated with a group. Only then does it execute the srai. 
If user does not have authorisation, then it returns FAIL_AUTHORISATION token

Still work in progress on the authframework branch but its coming together nicely

k

**Comment by keiffster** [comment]
Hi Sean/ #ideasean , 
Well this email thread has generated a big piece of work, specifically adding authorisation and authentication into the core code base.
I have moved authentication in the core brain loop rather than use a pre-processor. This makes it more solid as a solution 
Authentication is now a tag as described above, and there is an implementation of Users, Groups and Roles with an associated way of loading them from a file for now
All code still on the authframework branch but looking good I think
K

**Comment by keiffster** [comment]
Documentation now moving onto the wiki under security, closing this issue to allow individual issues to be raised if needed
