### ISSUE TITLE
Survey bug

### ISSUE THREAD

**Issue by narnikgamarnikus** [keiffster/program-y#55]
After answer for two questions, y-bot сontinues to answer "Thanks, thats the end of the survey"

Need some kind of team to exit from survey, for example "end survey"

P.S.
After studying the project in general, and getting acquainted with all available opportunities, I will try every day to make a bugs fixing.

Same, As far as possible, as I promised, I will improve the WebChat c and the REST clients

**Comment by ideasean** [comment]
I had this issue when trying things out. After this sentence - `Thanks, thats the end of the survey` - add:

`<think><set name="topic"></set></think>`

This should reset the topic, and all back to normal.

**Comment by narnikgamarnikus** [comment]
Thank you.
Should I push, after fixing such small bugs?
I found another ten, and they are all easily eliminated.

**Comment by keiffster** [comment]
Fixed in master this morning and change pushed
As Sean said the survey did not reset the topic after the survey had completed
