### ISSUE TITLE
Example of y-bot license.keys file

### ISSUE THREAD

**Issue by narnikgamarnikus** [keiffster/program-y#56]
Give me an example of bots`/y-bot/config/license.keys` file.

I want to get an API key from a [metoffice](http://www.metoffice.gov.uk/), but I do not understand how to write it to this file, because It does not exist in `/y-bot//config/`

**Comment by narnikgamarnikus** [comment]
Found out in the logs that it was necessary to call him `METOFFICE_API_KEY`

**Comment by keiffster** [comment]
You can always check the Wiki

https://github.com/keiffster/program-y/wiki/Met-Officer-Weather-API

**Comment by keiffster** [comment]
License Key File is just a text file of key value pairs

key = value

Call it anything you like, such as licenses.keys and in the config file reference as part of the bot settings. e.g

bot:
   license_keys: $BOT_ROOT/config/license.keys

**Comment by narnikgamarnikus** [comment]
Despite this, I get an error.

in keys.py:

```
    def has_key(self, name):
        print(name)
        print(self._keys)
        return bool(name in self._keys)
```

output:

```
GOOGLE_LATLONG
{}
GOOGLE_MAPS_DISTANCE
{}
GOOGLE_MAPS_DIRECTIONS
{}
METOFFICE_API_KEY
{}
```

license.keys:
`METOFFICE_API_KEY = 33332342-zxcas-dasdzxc-324234-4808a970995c`

**Comment by keiffster** [comment]
Ok, just be sure, can you remove the spaces around the '=', 
My license key file is exactly like that 
METOFFICE_API_KEY=XXXXXXXXXX
And is references from config.yaml as
bot:
    license_keys: $BOT_ROOT/config/license.keys
The other check is therefore to check its in the right location
You can check the log file to see if its reporting an error

**Comment by narnikgamarnikus** [comment]
@keiffster I checked with spaces and without. And I am sure that this is not the case.

If I understand the problem correctly, load_license_key_file is called only after if __name__ == '__main__' :, and since this file is not executable in this situation, the function can not be called.

Or am I mistaken in how it works if __name__ == '__main__':?

**Comment by narnikgamarnikus** [comment]
In the `/y-bot/` I run `python3 ../../src/programy/clients/console.py --config ./config.yaml --cformat yaml --logging ./logging.yaml`

**Comment by keiffster** [comment]
Hi is this still an issue ?
