### ISSUE TITLE
Contribute joke extension

### ISSUE THREAD

**Issue by narnikgamarnikus** [keiffster/program-y#60]
I make tiny changes in y-bot and extensions.
I created a folder `jokes` in the `bots/y-bot/extensinons` and in the `src/programy/extensions` with 2 files in each.
Thus, I can gradually develop the jokes  extension  increasing the functionality.
I'm sending requests to two free API services, and return random jokes to the user. I do not accept any arguments from the user.

I also plan to add a funny quote or an interesting observation.

If for you it is interesting and has value, you can accept.

**Comment by keiffster** [comment]
Sounds a great idea, extensions were designed exactly for this type of solution. A simple grammar with a call out to an external service to retrieve data is more efficient that coding every joke as aiml files
