### ISSUE TITLE
Default setting for allow_system_aiml in config

### ISSUE THREAD

**Issue by ideasean** [keiffster/program-y#61]
Can I suggest the default for 

`allow_system_aiml: true`

should be

`allow_system_aiml: false`

I haven't looked into whether its fully implemented... probably good to avoid potential future issues if someone doesn't check what that does before leaving a bot running somewhere :-)

**Comment by keiffster** [comment]
It Is used to enable the <system> tag, so unless you have that tag active the setting has no impact

It is on by default as it's just another thing people leaning aiml need to remember.

I have an idea to write something On the wiki on how to harden a production version of your bot

K

**Comment by ideasean** [comment]
Fair enough. If one was to leave it enabled, its probably worth mentioning in the Wiki to doublecheck any open source AIML libraries they use. Also, its not possible for the bot to "learn" one if learnf is enabled?

**Comment by keiffster** [comment]
You will only learnf a new question if the resulting learn contains system, so yes there is a bit of a catch 22, but by default y bot that does ship with system learnf, so a bot developer would be consciously adding it.

Agree that I’ll add something to the wiki to highlight the potential risk

Responses are slow at the moment, I’m in the south east coast of Spain enjoying 35’C

K

Keith Sterling
E: keith@keithsterling.com
M: +44 (0) 7771 597 630

**Comment by ideasean** [comment]
Fair enough!
