### ISSUE TITLE
Error: No node [xml] registered in Template Node Factory

### ISSUE THREAD

**Issue by stairway-to** [keiffster/program-y#62]
Hi,

I'm getting the error when trying to use [Blackjack.aiml](http://www.square-bear.co.uk/aiml/blackjack.aiml).

```No node [xml] registered in Template Node Factory in [./aiml/blackjack.aiml]```

Thank you for the amazing library!

**Comment by keiffster** [comment]
Which bot are you running ?

**Comment by stairway-to** [comment]
I'm using the Rosie bot that was in the sample. But I removed most of the other aiml files.

**Comment by keiffster** [comment]
My mistake, easy to correct

Copy the file named template_nodes from either confirm folder of alice2 or ybot and overwrite the same file in the conf folder of Alice. That should fix it and I'll correct in ext release

K

Keith Sterling
E: keith@keithsterling.com
M: +44 (0) 7771 597 630

**Comment by stairway-to** [comment]
Thanks! That worked.

**Comment by stairway-to** [comment]
Hi,

Please can you reply. Its pretty urgent.

Thanks and regards.
