### ISSUE TITLE
Triggering OOB

### ISSUE THREAD

**Issue by ideasean** [keiffster/program-y#66]
Just wondering if I am missing something with OOB. I tried adding this to ybot scratch.aiml

```
    <category>
        <pattern>
           OOBDIAL
        </pattern>
        <template>
          Dialing
          <oob><dial>07777777777</dial></oob>
        </template>
    </category>

```
It responds with Dialing but I can see in the log that the OOB dial processor is not being triggered? 
Thanks!

**Comment by keiffster** [comment]
See private email, works now in latest code in master

K

**Comment by ideasean** [comment]
Fixed within ~10 hrs of opening... 

`Commit: Showing  89 changed files  with 1,344 additions and 460 deletions.`

 Y-bot might be the bot but Keith is the coding machine!
