### ISSUE TITLE
Spellcheck - does SRAI get spellchecked again? 

### ISSUE THREAD

**Issue by ideasean** [keiffster/program-y#67]
I've been trying out spellcheck... seems to work well except in a case that might be a bit specific to us. 

We are passing back a reasonable amount of data (list of open tickets) back to the bot from a service, which is then run through SRAI to set some variables and format the responses. When spellcheck is on, it takes a very long time . I suspect it is trying to spellcheck all that data coming back from the service. 

I think when we move that data to OOB it might clear this issue up, but it might be an issue for others if text is passing through SRAI several times or if managing a larger response through SRAI.

Is it an option to move spellcheck further up the dialog "stack" closer to the client?

**Comment by keiffster** [comment]
I'm still struggling with the spellchecker, it's very cpu intensive and can consume a lot of memory when the corpus gets big. It's a default implementation of a comp sci standard algorithm 

It was added by another contributor, personally I think its interesting but not optimal

K

**Comment by ideasean** [comment]
For limited domain applications like us I think its useful and we can take the CPU hit. We're just adding the main keywords to help users get commands right. Perhaps put a notice on it re use at own risk / test appropriately for the time being :-)

It may help though if SRAI didnt process spelling again, and if OOB avoids using it if not already avoiding (since outbound misspellings are our fault!)

**Comment by keiffster** [comment]
Ok, simplest option is a switch to avoid spelling on straight defaulted to true

K

Keith Sterling
E: keith@keithsterling.com
M: +44 (0) 7771 597 630

**Comment by keiffster** [comment]
bot.py updated so as not to spellcheck if in srai
