### ISSUE TITLE
OOB minor items - xml tag left in default output, THAT oob processing...

### ISSUE THREAD

**Issue by ideasean** [keiffster/program-y#68]
The default OOB (ie if no processor is present) is leaving an xml declaration in the output...

```
imelda> tickets incident search CPU and Memory
Say LIST SET 1 to 10 - <br/>
 <?xml version='1.0' encoding='utf8'?> <datapad><contenttype>text64</contenttype> 
```
Which the THAT processor is then getting hung up on:

```
2017-08-11 01:40:06,553  root       INFO    Topic pattern = [*]
2017-08-11 01:40:06,553  root       INFO    That pattern = [0 encoding= utf8 > <datapad><contenttype>text64</contenttype>

```
I got around it by writing an oob processor to just rebuild and output the xml as a string.

Then it seems THAT is still storing the output from the OOB processor as the last response

```
2017-08-10 23:52:48,568  root       INFO    Topic pattern = [*]
2017-08-10 23:52:48,568  root       INFO    That pattern = [<oob><datapad><contenttype>text64</contenttype><contentdata>...

```
The good thing is that it doesn't try to interpret it, but it might be better if THAT ignored the OOB completely and retained the last valid AIML response?

Lastly, the output of the OOB processor loses its place in the response string - it ends up at the end. 

There might be some unforeseen complexities in the above :-)

**Comment by ideasean** [comment]
Just a bit more background... I am thinking to use OOB datapad to pass base64 image data from a service to the client. The oob tagset could get quite large. Thats's why I am thinking we avoid any part of it ending up in the conversation history.

**Comment by ideasean** [comment]
> Lastly, the output of the OOB processor loses its place in the response string - it ends up at the end.
This part resolved - my issue :-)

**Comment by keiffster** [comment]
Ok, let me take a look, just finished addiing RDF Support which brings support to 100% of AIML 2 spec as defined by Pandora bots. Not easy when there are an additional 10 aiml tags not documented anywhere!!!

**Comment by keiffster** [comment]
Rewritten DefaultOOBProcessor to consume XML and not return it. Which probably makes sense rather than squirting out XML anyway

**Comment by keiffster** [comment]
Hi Sean

Did this work for you ?

**Comment by ideasean** [comment]
I'm behind on merging from your repo at the moment - have had some high priority functional requirements the past few weeks. I have allocated next week for clearing some tech debt inc catching up. Happy if you want to close these for now and we can reopen or create new if they come up again.
