### ISSUE TITLE
install fail clone from github, zips are different no record of them when add in github software, new repository for zips wanted when added to github software

### ISSUE THREAD

**Issue by sprinteroz** [keiffster/program-y#69]
Hi keiffster and other members,

I have tried to clone the program from github and it will not install.
I'm using github on windows 10 system latest version. 

Also I have tried the zip file, it installs with a different name, same as the one on your website download, also the clone copy on github has a different name when the file is installing to the zips?

**clone** form github installs as **program-y**
**zip** from github installs as **program-y-master**
one on your **website  program-y zip download link** can be added into github as **keiffster-program-y-0f95610**

When I add the github zip I download or the zip form your website it says **no repository found on github** would I like to make one on github, I say No to the question and try the clone again after I wipe the old files but still no luck

Can you help me with this problem at all please,

Thank you for your time.

**Comment by keiffster** [comment]
Can you provide a little more info, what do you mean by "it will not install"

There is not installation process for Programy. Once you download the source, you need to use one of the .sh or .cmd scripts in the bots folders to run a bot

Clone and zip download do create differently named folders, thats just how github works

* Clone - always creates 'program-y' folder which is a clone of master. Github just does not add the -master tag to the end
* Zip - names the file ( and folder ) 'program-y-master' because it is a zip file of the master branch. Again just how Github works

However, you will find both folders and their contents are identical, just their names different

Once you have a folder installed on your machine, you need to run pip install -r requirements.txt to install all of the python dependencies

Then go to /bots/alice2 and use the alice2.cmd to run the bot as a console app

**Comment by sprinteroz** [comment]
Hello Thankyou for your reply,

I was going to do a screen record and upload to youtube what was happening so you could see, but just so happens today when I tried the clone link again it took me to the new downloadpage for github desktop 0.8.0 for windows 64 bit https://desktop.github.com/release-notes/ the old version of github for windows was Chocolate-Covered Yaks (3.3.4.0) 50415df all the same but both FAIL to clone the program.

The new beta has a new feature that logs the clone install. Here is the log:

Cloning into 'C:\Users\win64\Documents\GitHub\program-y'...
remote: Counting objects: 6828, done.        
remote: Compressing objects:   1% (1/73)
remote: Compressing objects:   2% (2/73)
remote: Compressing objects:   4% (3/73)
remote: Compressing objects:   5% (4/73) 
remote: Compressing objects:   6% (5/73)           
remote: Compressing objects:   8% (6/73)           
remote: Compressing objects:   9% (7/73)           
remote: Compressing objects:  10% (8/73)           
remote: Compressing objects:  12% (9/73)           
remote: Compressing objects:  13% (10/73)           
remote: Compressing objects:  15% (11/73)           
remote: Compressing objects:  16% (12/73)           
remote: Compressing objects:  17% (13/73)           
remote: Compressing objects:  19% (14/73)           
remote: Compressing objects:  20% (15/73)           
remote: Compressing objects:  21% (16/73)           
remote: Compressing objects:  23% (17/73)           
remote: Compressing objects:  24% (18/73)           
remote: Compressing objects:  26% (19/73)           
remote: Compressing objects:  27% (20/73)           
remote: Compressing objects:  28% (21/73)           
remote: Compressing objects:  30% (22/73)           
remote: Compressing objects:  31% (23/73)           
remote: Compressing objects:  32% (24/73)           
remote: Compressing objects:  34% (25/73)           
remote: Compressing objects:  35% (26/73)           
remote: Compressing objects:  36% (27/73)           
remote: Compressing objects:  38% (28/73)           
remote: Compressing objects:  39% (29/73)           
remote: Compressing objects:  41% (30/73)           
remote: Compressing objects:  42% (31/73)           
remote: Compressing objects:  43% (32/73)           
remote: Compressing objects:  45% (33/73)           
remote: Compressing objects:  46% (34/73)           
remote: Compressing objects:  47% (35/73)           
remote: Compressing objects:  49% (36/73)           
remote: Compressing objects:  50% (37/73)           
remote: Compressing objects:  52% (38/73)           
remote: Compressing objects:  53% (39/73)           
remote: Compressing objects:  54% (40/73)           
remote: Compressing objects:  56% (41/73)           
remote: Compressing objects:  57% (42/73)           
remote: Compressing objects:  58% (43/73)           
remote: Compressing objects:  60% (44/73)           
remote: Compressing objects:  61% (45/73)           
remote: Compressing objects:  63% (46/73)           
remote: Compressing objects:  64% (47/73)           
remote: Compressing objects:  65% (48/73)           
remote: Compressing objects:  67% (49/73)           
remote: Compressing objects:  68% (50/73)           
remote: Compressing objects:  69% (51/73)           
remote: Compressing objects:  71% (52/73)           
remote: Compressing objects:  72% (53/73)           
remote: Compressing objects:  73% (54/73)           
remote: Compressing objects:  75% (55/73)           
remote: Compressing objects:  76% (56/73)           
remote: Compressing objects:  78% (57/73)           
remote: Compressing objects:  79% (58/73)           
remote: Compressing objects:  80% (59/73)           
remote: Compressing objects:  82% (60/73)           
remote: Compressing objects:  83% (61/73)           
remote: Compressing objects:  84% (62/73)           
remote: Compressing objects:  86% (63/73)           
remote: Compressing objects:  87% (64/73)           
remote: Compressing objects:  89% (65/73)           
remote: Compressing objects:  90% (66/73)           
remote: Compressing objects:  91% (67/73)           
remote: Compressing objects:  93% (68/73)           
remote: Compressing objects:  94% (69/73)           
remote: Compressing objects:  95% (70/73)           
remote: Compressing objects:  97% (71/73)           
remote: Compressing objects:  98% (72/73)           
remote: Compressing objects: 100% (73/73)           
remote: Compressing objects: 100% (73/73), done.        
Receiving objects:   0% (1/6828)   
Receiving objects:   1% (69/6828)   
Receiving objects:   2% (137/6828)   
Receiving objects:   3% (205/6828)   
Receiving objects:   4% (274/6828), 212.01 KiB | 396.00 KiB/s   
Receiving objects:   4% (308/6828), 332.01 KiB | 314.00 KiB/s   
Receiving objects:   5% (342/6828), 332.01 KiB | 314.00 KiB/s   
Receiving objects:   6% (410/6828), 604.01 KiB | 388.00 KiB/s   
Receiving objects:   6% (438/6828), 908.01 KiB | 440.00 KiB/s   
Receiving objects:   6% (473/6828), 1.59 MiB | 530.00 KiB/s   
Receiving objects:   7% (478/6828), 1.59 MiB | 530.00 KiB/s   
Receiving objects:   7% (480/6828), 2.49 MiB | 624.00 KiB/s   
Receiving objects:   7% (484/6828), 3.61 MiB | 765.00 KiB/s   
Receiving objects:   7% (489/6828), 4.08 MiB | 848.00 KiB/s   
Receiving objects:   7% (501/6828), 5.63 MiB | 1.04 MiB/s   
Receiving objects:   7% (510/6828), 8.07 MiB | 1.26 MiB/s   
Receiving objects:   7% (526/6828), 9.00 MiB | 1.35 MiB/s   
Receiving objects:   7% (536/6828), 9.92 MiB | 1.29 MiB/s   
Receiving objects:   8% (547/6828), 10.51 MiB | 1.32 MiB/s   
Receiving objects:   8% (549/6828), 11.20 MiB | 1.31 MiB/s   
Receiving objects:   8% (561/6828), 12.13 MiB | 1.12 MiB/s   
Receiving objects:   8% (574/6828), 13.29 MiB | 1.14 MiB/s   
Receiving objects:   8% (587/6828), 14.30 MiB | 1.07 MiB/s   
Receiving objects:   8% (605/6828), 15.46 MiB | 1.09 MiB/s   
Receiving objects:   9% (615/6828), 16.05 MiB | 1.07 MiB/s   
Receiving objects:   9% (623/6828), 16.60 MiB | 1.07 MiB/s   
Receiving objects:   9% (634/6828), 17.74 MiB | 1.10 MiB/s   
Receiving objects:  10% (683/6828), 17.74 MiB | 1.10 MiB/s   
Receiving objects:  11% (752/6828), 17.74 MiB | 1.10 MiB/s   
Receiving objects:  12% (820/6828), 18.32 MiB | 1.09 MiB/s   
Receiving objects:  13% (888/6828), 18.32 MiB | 1.09 MiB/s   
Receiving objects:  14% (956/6828), 18.32 MiB | 1.09 MiB/s   
Receiving objects:  15% (1025/6828), 18.32 MiB | 1.09 MiB/s   
Receiving objects:  16% (1093/6828), 18.32 MiB | 1.09 MiB/s   
Receiving objects:  17% (1161/6828), 18.32 MiB | 1.09 MiB/s   
Receiving objects:  18% (1230/6828), 18.32 MiB | 1.09 MiB/s   
Receiving objects:  19% (1298/6828), 18.32 MiB | 1.09 MiB/s   
Receiving objects:  20% (1366/6828), 18.32 MiB | 1.09 MiB/s   
Receiving objects:  21% (1434/6828), 18.32 MiB | 1.09 MiB/s   
Receiving objects:  22% (1503/6828), 18.32 MiB | 1.09 MiB/s   
Receiving objects:  23% (1571/6828), 18.32 MiB | 1.09 MiB/s   
Receiving objects:  24% (1639/6828), 18.32 MiB | 1.09 MiB/s   
Receiving objects:  25% (1707/6828), 18.32 MiB | 1.09 MiB/s   
Receiving objects:  26% (1776/6828), 18.32 MiB | 1.09 MiB/s   
Receiving objects:  27% (1844/6828), 18.32 MiB | 1.09 MiB/s   
Receiving objects:  28% (1912/6828), 18.32 MiB | 1.09 MiB/s   
Receiving objects:  29% (1981/6828), 18.32 MiB | 1.09 MiB/s   
Receiving objects:  30% (2049/6828), 18.32 MiB | 1.09 MiB/s   
Receiving objects:  31% (2117/6828), 18.32 MiB | 1.09 MiB/s   
Receiving objects:  32% (2185/6828), 18.32 MiB | 1.09 MiB/s   
Receiving objects:  32% (2230/6828), 18.32 MiB | 1.09 MiB/s   
Receiving objects:  33% (2254/6828), 18.32 MiB | 1.09 MiB/s   
Receiving objects:  34% (2322/6828), 18.32 MiB | 1.09 MiB/s   
Receiving objects:  35% (2390/6828), 18.32 MiB | 1.09 MiB/s   
Receiving objects:  36% (2459/6828), 18.32 MiB | 1.09 MiB/s   
Receiving objects:  37% (2527/6828), 18.93 MiB | 1.14 MiB/s   
Receiving objects:  38% (2595/6828), 18.93 MiB | 1.14 MiB/s   
Receiving objects:  39% (2663/6828), 18.93 MiB | 1.14 MiB/s   
Receiving objects:  40% (2732/6828), 18.93 MiB | 1.14 MiB/s   
Receiving objects:  41% (2800/6828), 18.93 MiB | 1.14 MiB/s   
Receiving objects:  42% (2868/6828), 18.93 MiB | 1.14 MiB/s   
Receiving objects:  43% (2937/6828), 18.93 MiB | 1.14 MiB/s   
Receiving objects:  44% (3005/6828), 18.93 MiB | 1.14 MiB/s   
Receiving objects:  45% (3073/6828), 18.93 MiB | 1.14 MiB/s   
Receiving objects:  46% (3141/6828), 18.93 MiB | 1.14 MiB/s   
Receiving objects:  47% (3210/6828), 18.93 MiB | 1.14 MiB/s   
Receiving objects:  48% (3278/6828), 18.93 MiB | 1.14 MiB/s   
Receiving objects:  49% (3346/6828), 18.93 MiB | 1.14 MiB/s   
Receiving objects:  50% (3414/6828), 18.93 MiB | 1.14 MiB/s   
Receiving objects:  51% (3483/6828), 18.93 MiB | 1.14 MiB/s   
Receiving objects:  52% (3551/6828), 18.93 MiB | 1.14 MiB/s   
Receiving objects:  53% (3619/6828), 18.93 MiB | 1.14 MiB/s   
Receiving objects:  54% (3688/6828), 18.93 MiB | 1.14 MiB/s   
Receiving objects:  55% (3756/6828), 18.93 MiB | 1.14 MiB/s   
Receiving objects:  56% (3824/6828), 18.93 MiB | 1.14 MiB/s   
Receiving objects:  57% (3892/6828), 18.93 MiB | 1.14 MiB/s   
Receiving objects:  58% (3961/6828), 18.93 MiB | 1.14 MiB/s   
Receiving objects:  59% (4029/6828), 18.93 MiB | 1.14 MiB/s   
Receiving objects:  60% (4097/6828), 18.93 MiB | 1.14 MiB/s   
Receiving objects:  61% (4166/6828), 18.93 MiB | 1.14 MiB/s   
Receiving objects:  62% (4234/6828), 18.93 MiB | 1.14 MiB/s   
Receiving objects:  63% (4302/6828), 18.93 MiB | 1.14 MiB/s   
Receiving objects:  64% (4370/6828), 18.93 MiB | 1.14 MiB/s   
Receiving objects:  65% (4439/6828), 18.93 MiB | 1.14 MiB/s   
Receiving objects:  66% (4507/6828), 18.93 MiB | 1.14 MiB/s   
Receiving objects:  67% (4575/6828), 18.93 MiB | 1.14 MiB/s   
Receiving objects:  68% (4644/6828), 18.93 MiB | 1.14 MiB/s   
Receiving objects:  69% (4712/6828), 18.93 MiB | 1.14 MiB/s   
Receiving objects:  70% (4780/6828), 18.93 MiB | 1.14 MiB/s   
Receiving objects:  71% (4848/6828), 18.93 MiB | 1.14 MiB/s   
Receiving objects:  72% (4917/6828), 18.93 MiB | 1.14 MiB/s   
Receiving objects:  73% (4985/6828), 18.93 MiB | 1.14 MiB/s   
Receiving objects:  74% (5053/6828), 18.93 MiB | 1.14 MiB/s   
Receiving objects:  75% (5121/6828), 18.93 MiB | 1.14 MiB/s   
Receiving objects:  76% (5190/6828), 18.93 MiB | 1.14 MiB/s   
Receiving objects:  77% (5258/6828), 18.93 MiB | 1.14 MiB/s   
Receiving objects:  78% (5326/6828), 18.93 MiB | 1.14 MiB/s   
Receiving objects:  79% (5395/6828), 18.93 MiB | 1.14 MiB/s   
Receiving objects:  80% (5463/6828), 18.93 MiB | 1.14 MiB/s   
Receiving objects:  81% (5531/6828), 18.93 MiB | 1.14 MiB/s   
Receiving objects:  82% (5599/6828), 18.93 MiB | 1.14 MiB/s   
Receiving objects:  83% (5668/6828), 18.93 MiB | 1.14 MiB/s   
Receiving objects:  84% (5736/6828), 19.52 MiB | 1.13 MiB/s   
Receiving objects:  85% (5804/6828), 19.52 MiB | 1.13 MiB/s   
Receiving objects:  86% (5873/6828), 19.52 MiB | 1.13 MiB/s   
Receiving objects:  87% (5941/6828), 19.52 MiB | 1.13 MiB/s   
Receiving objects:  88% (6009/6828), 19.52 MiB | 1.13 MiB/s   
Receiving objects:  89% (6077/6828), 19.52 MiB | 1.13 MiB/s   
Receiving objects:  90% (6146/6828), 19.52 MiB | 1.13 MiB/s   
Receiving objects:  90% (6189/6828), 19.52 MiB | 1.13 MiB/s   
Receiving objects:  91% (6214/6828), 20.14 MiB | 1.15 MiB/s   
Receiving objects:  92% (6282/6828), 20.14 MiB | 1.15 MiB/s   
Receiving objects:  93% (6351/6828), 20.14 MiB | 1.15 MiB/s   
Receiving objects:  94% (6419/6828), 20.14 MiB | 1.15 MiB/s   
Receiving objects:  95% (6487/6828), 20.78 MiB | 1.15 MiB/s   
Receiving objects:  96% (6555/6828), 20.78 MiB | 1.15 MiB/s   
Receiving objects:  97% (6624/6828), 20.78 MiB | 1.15 MiB/s   
Receiving objects:  98% (6692/6828), 20.78 MiB | 1.15 MiB/s   
Receiving objects:  99% (6760/6828), 20.78 MiB | 1.15 MiB/s   
remote: Total 6828 (delta 47), reused 61 (delta 29), pack-reused 6724        
Receiving objects: 100% (6828/6828), 20.78 MiB | 1.15 MiB/s   
Receiving objects: 100% (6828/6828), 21.08 MiB | 1.06 MiB/s, done.
Resolving deltas:   0% (0/4794)   
Resolving deltas:   1% (51/4794)   
Resolving deltas:   2% (100/4794)   
Resolving deltas:   3% (151/4794)   
Resolving deltas:   4% (192/4794)   
Resolving deltas:   5% (240/4794)   
Resolving deltas:   6% (288/4794)   
Resolving deltas:   7% (354/4794)   
Resolving deltas:   8% (391/4794)   
Resolving deltas:   9% (433/4794)   
Resolving deltas:  10% (501/4794)   
Resolving deltas:  11% (548/4794)   
Resolving deltas:  12% (582/4794)   
Resolving deltas:  13% (640/4794)   
Resolving deltas:  14% (681/4794)   
Resolving deltas:  15% (741/4794)   
Resolving deltas:  16% (771/4794)   
Resolving deltas:  17% (815/4794)   
Resolving deltas:  18% (866/4794)   
Resolving deltas:  19% (915/4794)   
Resolving deltas:  20% (962/4794)   
Resolving deltas:  21% (1036/4794)   
Resolving deltas:  22% (1067/4794)   
Resolving deltas:  23% (1125/4794)   
Resolving deltas:  24% (1161/4794)   
Resolving deltas:  25% (1205/4794)   
Resolving deltas:  26% (1259/4794)   
Resolving deltas:  27% (1297/4794)   
Resolving deltas:  28% (1352/4794)   
Resolving deltas:  29% (1413/4794)   
Resolving deltas:  30% (1439/4794)   
Resolving deltas:  31% (1495/4794)   
Resolving deltas:  32% (1548/4794)   
Resolving deltas:  33% (1583/4794)   
Resolving deltas:  34% (1658/4794)   
Resolving deltas:  35% (1678/4794)   
Resolving deltas:  36% (1745/4794)   
Resolving deltas:  37% (1788/4794)   
Resolving deltas:  38% (1822/4794)   
Resolving deltas:  39% (1871/4794)   
Resolving deltas:  40% (1927/4794)   
Resolving deltas:  41% (1969/4794)   
Resolving deltas:  42% (2017/4794)   
Resolving deltas:  44% (2122/4794)   
Resolving deltas:  45% (2167/4794)   
Resolving deltas:  46% (2209/4794)   
Resolving deltas:  47% (2259/4794)   
Resolving deltas:  48% (2320/4794)   
Resolving deltas:  49% (2352/4794)   
Resolving deltas:  50% (2402/4794)   
Resolving deltas:  51% (2445/4794)   
Resolving deltas:  52% (2494/4794)   
Resolving deltas:  53% (2544/4794)   
Resolving deltas:  54% (2599/4794)   
Resolving deltas:  55% (2637/4794)   
Resolving deltas:  56% (2689/4794)   
Resolving deltas:  57% (2748/4794)   
Resolving deltas:  58% (2789/4794)   
Resolving deltas:  59% (2846/4794)   
Resolving deltas:  60% (2879/4794)   
Resolving deltas:  61% (2961/4794)   
Resolving deltas:  62% (2989/4794)   
Resolving deltas:  63% (3031/4794)   
Resolving deltas:  64% (3084/4794)   
Resolving deltas:  65% (3121/4794)   
Resolving deltas:  66% (3168/4794)   
Resolving deltas:  67% (3212/4794)   
Resolving deltas:  68% (3266/4794)   
Resolving deltas:  69% (3312/4794)   
Resolving deltas:  70% (3374/4794)   
Resolving deltas:  71% (3405/4794)   
Resolving deltas:  72% (3454/4794)   
Resolving deltas:  73% (3500/4794)   
Resolving deltas:  74% (3549/4794)   
Resolving deltas:  75% (3597/4794)   
Resolving deltas:  76% (3661/4794)   
Resolving deltas:  77% (3695/4794)   
Resolving deltas:  78% (3748/4794)   
Resolving deltas:  79% (3790/4794)   
Resolving deltas:  80% (3843/4794)   
Resolving deltas:  81% (3884/4794)   
Resolving deltas:  82% (3941/4794)   
Resolving deltas:  83% (3986/4794)   
Resolving deltas:  84% (4030/4794)   
Resolving deltas:  85% (4076/4794)   
Resolving deltas:  86% (4128/4794)   
Resolving deltas:  87% (4173/4794)   
Resolving deltas:  88% (4225/4794)   
Resolving deltas:  89% (4268/4794)   
Resolving deltas:  90% (4317/4794)   
Resolving deltas:  91% (4375/4794)   
Resolving deltas:  92% (4411/4794)   
Resolving deltas:  93% (4460/4794)   
Resolving deltas:  94% (4518/4794)   
Resolving deltas:  95% (4562/4794)   
Resolving deltas:  95% (4568/4794)   
Resolving deltas:  96% (4609/4794)   
Resolving deltas:  97% (4651/4794)   
Resolving deltas:  98% (4699/4794)   
Resolving deltas:  99% (4748/4794)   
Resolving deltas: 100% (4794/4794)   
Resolving deltas: 100% (4794/4794), done.
error: unable to create file 	mp\leanf.aiml: Invalid argument
Checking out files:   0% (16/1670)   
Checking out files:   1% (17/1670)   
Checking out files:   1% (27/1670)   
Checking out files:   2% (34/1670)   
Checking out files:   2% (45/1670)   
Checking out files:   3% (51/1670)   
Checking out files:   4% (67/1670)   
Checking out files:   4% (72/1670)   
Checking out files:   5% (84/1670)   
Checking out files:   5% (94/1670)   
Checking out files:   6% (101/1670)   
Checking out files:   6% (102/1670)   
Checking out files:   6% (106/1670)   
Checking out files:   6% (111/1670)   
Checking out files:   7% (117/1670)   
Checking out files:   7% (124/1670)   
Checking out files:   7% (130/1670)   
Checking out files:   8% (134/1670)   
Checking out files:   8% (141/1670)   
Checking out files:   8% (146/1670)   
Checking out files:   9% (151/1670)   
Checking out files:   9% (155/1670)   
Checking out files:  10% (167/1670)   
Checking out files:  10% (181/1670)   
Checking out files:  11% (184/1670)   
Checking out files:  11% (185/1670)   
Checking out files:  11% (189/1670)   
Checking out files:  11% (193/1670)   
Checking out files:  11% (197/1670)   
Checking out files:  12% (201/1670)   
Checking out files:  12% (202/1670)   
Checking out files:  12% (208/1670)   
Checking out files:  12% (213/1670)   
Checking out files:  13% (218/1670)   
Checking out files:  13% (219/1670)   
Checking out files:  13% (228/1670)   
Checking out files:  13% (230/1670)   
Checking out files:  14% (234/1670)   
Checking out files:  14% (235/1670)   
Checking out files:  14% (241/1670)   
Checking out files:  14% (245/1670)   
Checking out files:  15% (251/1670)   
Checking out files:  15% (259/1670)   
Checking out files:  15% (265/1670)   
Checking out files:  16% (268/1670)   
Checking out files:  16% (273/1670)   
Checking out files:  16% (280/1670)   
Checking out files:  17% (284/1670)   
Checking out files:  17% (286/1670)   
Checking out files:  17% (294/1670)   
Checking out files:  18% (301/1670)   
Checking out files:  18% (308/1670)   
Checking out files:  18% (316/1670)   
Checking out files:  19% (318/1670)   
Checking out files:  19% (323/1670)   
Checking out files:  19% (326/1670)   
Checking out files:  19% (331/1670)   
Checking out files:  20% (334/1670)   
Checking out files:  20% (337/1670)   
Checking out files:  20% (341/1670)   
Checking out files:  20% (345/1670)   
Checking out files:  21% (351/1670)   
Checking out files:  21% (357/1670)   
Checking out files:  22% (368/1670)   
Checking out files:  22% (380/1670)   
Checking out files:  23% (385/1670)   
Checking out files:  23% (394/1670)   
Checking out files:  24% (401/1670)   
Checking out files:  24% (406/1670)   
Checking out files:  25% (418/1670)   
Checking out files:  25% (428/1670)   
Checking out files:  26% (435/1670)   
Checking out files:  27% (451/1670)   
Checking out files:  27% (465/1670)   
Checking out files:  28% (468/1670)   
Checking out files:  29% (485/1670)   
Checking out files:  29% (487/1670)   
Checking out files:  30% (501/1670)   
Checking out files:  30% (512/1670)   
Checking out files:  31% (518/1670)   
Checking out files:  32% (535/1670)   
Checking out files:  32% (543/1670)   
Checking out files:  33% (552/1670)   
Checking out files:  34% (568/1670)   
Checking out files:  34% (569/1670)   
Checking out files:  34% (577/1670)   
Checking out files:  35% (585/1670)   
Checking out files:  35% (590/1670)   
Checking out files:  36% (602/1670)   
Checking out files:  36% (603/1670)   
Checking out files:  37% (618/1670)   
Checking out files:  37% (620/1670)   
Checking out files:  38% (635/1670)   
Checking out files:  38% (640/1670)   
Checking out files:  39% (652/1670)   
Checking out files:  40% (668/1670)   
Checking out files:  41% (685/1670)   
Checking out files:  41% (693/1670)   
Checking out files:  42% (702/1670)   
Checking out files:  43% (719/1670)   
Checking out files:  43% (726/1670)   
Checking out files:  44% (735/1670)   
Checking out files:  44% (748/1670)   
Checking out files:  45% (752/1670)   
Checking out files:  46% (769/1670)   
Checking out files:  46% (773/1670)   
Checking out files:  47% (785/1670)   
Checking out files:  47% (794/1670)   
Checking out files:  48% (802/1670)   
Checking out files:  48% (812/1670)   
Checking out files:  49% (819/1670)   
Checking out files:  49% (825/1670)   
Checking out files:  50% (835/1670)   
Checking out files:  50% (845/1670)   
Checking out files:  51% (852/1670)   
Checking out files:  51% (862/1670)   
Checking out files:  52% (869/1670)   
Checking out files:  52% (882/1670)   
Checking out files:  53% (886/1670)   
Checking out files:  54% (902/1670)   
Checking out files:  54% (907/1670)   
Checking out files:  55% (919/1670)   
Checking out files:  55% (922/1670)   
Checking out files:  56% (936/1670)   
Checking out files:  56% (946/1670)   
Checking out files:  57% (952/1670)   
Checking out files:  57% (959/1670)   
Checking out files:  58% (969/1670)   
Checking out files:  58% (979/1670)   
Checking out files:  59% (986/1670)   
Checking out files:  60% (1002/1670)   
Checking out files:  61% (1019/1670)   
Checking out files:  61% (1020/1670)   
error: unable to create file src/test/	mp\leanf.aiml: Invalid argument
Checking out files:  62% (1036/1670)   
Checking out files:  62% (1043/1670)   
Checking out files:  63% (1053/1670)   
Checking out files:  63% (1066/1670)   
Checking out files:  64% (1069/1670)   
Checking out files:  65% (1086/1670)   
Checking out files:  65% (1088/1670)   
Checking out files:  66% (1103/1670)   
Checking out files:  66% (1116/1670)   
Checking out files:  67% (1119/1670)   
Checking out files:  68% (1136/1670)   
Checking out files:  68% (1142/1670)   
Checking out files:  69% (1153/1670)   
Checking out files:  69% (1167/1670)   
Checking out files:  70% (1169/1670)   
Checking out files:  71% (1186/1670)   
Checking out files:  71% (1188/1670)   
Checking out files:  72% (1203/1670)   
Checking out files:  72% (1213/1670)   
Checking out files:  73% (1220/1670)   
Checking out files:  74% (1236/1670)   
Checking out files:  74% (1244/1670)   
Checking out files:  75% (1253/1670)   
Checking out files:  76% (1270/1670)   
Checking out files:  76% (1271/1670)   
Checking out files:  77% (1286/1670)   
Checking out files:  77% (1289/1670)   
Checking out files:  78% (1303/1670)   
Checking out files:  78% (1314/1670)   
Checking out files:  79% (1320/1670)   
Checking out files:  80% (1336/1670)   
Checking out files:  80% (1340/1670)   
Checking out files:  81% (1353/1670)   
Checking out files:  81% (1365/1670)   
Checking out files:  82% (1370/1670)   
Checking out files:  83% (1387/1670)   
Checking out files:  83% (1390/1670)   
Checking out files:  84% (1403/1670)   
Checking out files:  84% (1412/1670)   
Checking out files:  85% (1420/1670)   
Checking out files:  85% (1429/1670)   
Checking out files:  86% (1437/1670)   
Checking out files:  86% (1449/1670)   
Checking out files:  87% (1453/1670)   
Checking out files:  87% (1466/1670)   
Checking out files:  88% (1470/1670)   
Checking out files:  89% (1487/1670)   
Checking out files:  89% (1491/1670)   
Checking out files:  90% (1503/1670)   
Checking out files:  90% (1511/1670)   
Checking out files:  91% (1520/1670)   
Checking out files:  91% (1531/1670)   
Checking out files:  92% (1537/1670)   
Checking out files:  92% (1549/1670)   
Checking out files:  93% (1554/1670)   
Checking out files:  93% (1568/1670)   
Checking out files:  94% (1570/1670)   
Checking out files:  94% (1585/1670)   
Checking out files:  95% (1587/1670)   
Checking out files:  96% (1604/1670)   
Checking out files:  96% (1615/1670)   
Checking out files:  97% (1620/1670)   
Checking out files:  97% (1634/1670)   
Checking out files:  98% (1637/1670)   
Checking out files:  99% (1654/1670)   
Checking out files:  99% (1661/1670)   
Checking out files: 100% (1670/1670)   
Checking out files: 100% (1670/1670), done.
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

Thanks for your time hope to chat again soon.

**Comment by keiffster** [comment]
Ok, I see the problem, looks like a file " tmp/learnf.aiml" found its way into the code base when I was doing windows support.

I've removed this from master, should work now

K

**Comment by sprinteroz** [comment]
Hi again Thanks for taking the time to look into this it installed with no problems this time.

keep up the great work Keiffer, I'm new to AI but hope to contribute in some way, as I wish to build a basic bot of my own someday.

Thanks for your time
