### ISSUE TITLE
Can not publish file to contribute to the project

### ISSUE THREAD

**Issue by sprinteroz** [keiffster/program-y#70]
Hi @keiffster and readers, I wanted to contribute to the project but it give me a error:

_Authentication failed. You may not have permission to access the repository. Open options and verify that you're signed in with an account that has permission to access this repository._

Am I able to get permission or is it best to just share the files here as a attachment.

**Edit:** I have made a branch and have linked it to online https://github.com/sprinteroz/program-y

Thanks for you time

**Comment by keiffster** [comment]
If you to submit a change you must do it via a pull request

Only people with admin privs can commit to master

Create a branch and use GitHub pull request option to submit

We will then review and if all ok accept request which will add it to master

K

Keith Sterling
E: keith@keithsterling.com
M: +44 (0) 7771 597 630
