### ISSUE TITLE
Path to v1.0.0 - PLEASE READ

### ISSUE THREAD

**Issue by keiffster** [keiffster/program-y#77]
Programy-Y has come along way since I started it last year, to the point now that is being used in a few initial projects and gaining support. This, unfortunately, leads to a number of issues specifically around the development and release workflow. 

So it's time to start planning a route to v1.0.0 release and a change in how Github is used. There have been 19 formal releases and who knows how many minor and adhoc releases. Over the coming weeks there are a few final tweaks I want to add, and then to get unit test coverage upwards of 90%. This will then form the basis of V1.0.0, release which will for me will be a major milestone achievement. 

More fundamentally, the code branching strategy will change. Master will remain as a master branch but will not see the frequency of releases. This is mainly due to the amount of testing required for a release, ( Mac, Linux and Windows are the 3 primary versions ). Instead, a long live Dev branch will be created. This will be the most active branch for which I can continue daily and weekly releases. On a regular basis, Dev will be merged to Master and master put through a full suite of integration tests and then release following the version number pattern X.Y.Z

X - being a major release
Y - being a minor release
Z - being a defect release

Nearly all defects will be first fixed in Dev, released and if OK, Merged with master individually. Critical defects affecting a live project can be fixed in Master if required and immediately released, then back ported to dev and put through the normal process again.

All new features will be created in a branch of Dev, completed, merged to Dev, released again and if all ok, then merged to Master and released as  X.Y.Z point release increment.

Let me know your thoughts.

K

**Comment by keiffster** [comment]
Initial proposed changes would be

1) Move OOB from programy.utils.oob up one level to programy.oob to reflect core component
2) Move security from programy.utils.security up one level to programy.security to reflect core components
3) Move services from programy.utils.services up one level to programy.services to reflect core components
4) Move spelling from programy.utils.spelling up one level to programy.spelling  to reflect core components
5) Move geo, newsapi and weather from programy.utils, into new package programy.extensions  to reflect core components

**Comment by ideasean** [comment]
All good. Already Program-Y is a big achievement!

Re branches, another option might be keeping master and creating a "stable" branch. I based ours on https://gist.github.com/digitaljhelms/4287848 but dev/master is also fine. 

Re directory moves, it will create some corresponding directory moves in our structures and class reference updates across several services/extensions, but I prefer a flatter structure vs deeper. Also fine. 

It would be good to have a guideline on managing several "client" bots sharing varying degrees of code between core source, y-bot (as reference), client source/s and client bots. Also, how to maintain all that and also support merges from / pull requests back to your public project.

Some other thoughts - 

- Perhaps move "y-bot" to "basebot" and make basebot the master/generic bot we should diff back to when merging your updates, and on which the test cases are built. 
- Perhaps the other sample bots (particularly professor given size) could also be separate repos to help keep the base repo relatively small. SourceTree scans the full repo every time it gets focus, so larger repos seem to take longer to gather the updated files.

Bring on 1.0.0

**Comment by keiffster** [comment]
Check out a new TL repo [talk-y](https://github.com/keiffster/talk-y) this is a new bot I have been working that adds a speech enabled bot, but it has quite a few dependencies that are only required for this client and kind of pollutes the pip space too much, so moved it out into its own repo. 

I'll be following this up with a full doc set of how to run this in parallel to Program-Y which I think will give you most of what you are looking for in terms of guidelines you mentioned

This is the makings of an Alexa/Cortana/Google clone, which I'm hoping when publicised correctly will bring in more people to Program-Y when they see they have a speech enabled client that they can host themselves and can fully extend in the way only Program-Y and Python can provide.

**Comment by keiffster** [comment]
All proposed changes to the core code are now in, a few defect fixes and refactoring to improve unit tests have been added over the past week.

The focus now moves to ensuring the documentation matches the system and is as complete as it can be to support a V1.0.0 release

Another step forward..........
