### ISSUE TITLE
Path to Loebner

### ISSUE THREAD

**Issue by keiffster** [keiffster/program-y#78]
I started this project years ago, after seeing an article about the Leobner prize about 2010 or 2011. The first view years were spent exploring what was possible, then I found AIML and a Python 2 version and in 2014 ported it to Python 3 and had it up and running in a production environment in about 2 months. The resultant bot, still running today saved the company about £5m in the first year in customer service costs and was short listed for 2015 V3 Technology Award.

Since then I have always wanted to enter the Loebner competition and with Program-Y think I have the foundations making a good challenge. This Issue will track the progress to an entry in either 2018 or 2019

I'll cover what it takes to get there, what the architecture for getting there is, and what problems are needed to be overcome to not only create a great chatbot, but to also create a chatbot that no one thinks is chatbot!

**Comment by AnderPander** [comment]
Nice work. The is the most complete project of this type I've come across.  I have it running with talky but wondered if you thought of talkey for the tts - more engines out the gate.  But it is nice to have the stt - tts in same package and in house.  Again nice work.  You'll be ready when the robot's come.

**Comment by keiffster** [comment]
Glad you like it, its been a passion of mine for a while and great fun to be involved with

I'll take a look at talkey, and see how it can be potentially added. The model has been designed to take multiple tts and stt engines so should work

**Comment by keiffster** [comment]
Project now created to track all work [Path to Loebner](https://github.com/keiffster/program-y/projects/2)
