### ISSUE TITLE
Project Structure

### ISSUE THREAD

**Issue by keiffster** [keiffster/program-y#79]
As part of the Path to v1.0.0 I have been thinking about the structure of the code base. Program-Y is getting quite large and there is now the chance that extensions and services start to overlap. For example the Energy, Finance and Telecom extensions all have the question "How much credit to I ave?", which for each is a very different answer, Energy tells you how much credit you have on you prepay meter, Finance could tell you how much overdraft or credit limit you have left and Telecom could tell you how much data or call credit you have. 

As such I am planning on moving a number of none core components out of the main Program-Y code base and create their own projects in github. This will come with a full description on how to use core + extensions of choice to build the bot of you choosing.

In addition no further bots will be added to the core code base; Alice2, Rosie, Professor and Y-Bot will be the 4 it ships with. All further bots will be built as standard along projects. Again along with documentation of how to do this.

**Comment by ideasean** [comment]
Agree re services/extensions... clarifying when to use a service vs extension vs oob (and even pre/post processors) would help.

I've been loosely using the principle that extensions extend/support AIML and services call to outside the bot environment. But then I am also calling extensions from services and vice versa.

I have one case where a service calls gets data via ODBC, uses an extension to format a text graph, takes the resulting unicode and dumps it into a predicate as a base64 string, which is later picked up and decoded by an oob tag processor, wrapped in html formatting by the UCWA client, before being pushed to the Lync server via the UCWA API in a json post. It all seems to work (!), but I might be breaking some implicit assumptions you've made about public/private interfaces etc :-)

Also see #77 re Professor and Y-bot thoughts...  having one "base bot" might also help if later using pip or similar, and people seem to expect to have a running bot out of the box. Trying to explain "its a platform" might be an easier discussion after they are impressed by the ease of setup and running. Still, I am not sure it really is meant to be a "module" :-)

**Comment by keiffster** [comment]
Step 1 in refactoring the project space is to move the unit tests up a level and consolidate into a single /test folder. This would give a TL structure along the lines of

```
/src
    /programy
    /utils
/tests
    /programytest
    /performance
    /integration
```
Part of this work is required to support a new client talk-y which support text to speech and speech to text capabilities

Changes have been made and currently going through full suite of tests before push to master

**Comment by keiffster** [comment]
This is now complete, all tests pass and all clients working
