### ISSUE TITLE
Star matching and multi question sentence. 

### ISSUE THREAD

**Issue by ideasean** [keiffster/program-y#81]
Am trying to string two questions together in one sentence. 

`TICKET SET 0039471220. TICKET ANALYSE`

Individually these work when done sequentially, however when together I get

` Star node has no matched context for clientid...`

Looking at the code above this, 

```
            conversation = bot.get_conversation(clientid)
            current_question = conversation.current_question()
            current_sentence = current_question.current_sentence()
            matched_context = current_sentence.matched_context
            if matched_context is None:
                logging.error("Star node has no matched context for clientid %s" % (clientid))
                resolved = ""
  
```

I am wondering if the matched_context should be against the current_question instead of the sentence? Tried changing directly here but got a general error.

I haven't had a chance to do a repro case yet, but if you feel the above is all correct, I'll dig in more and see if its something I've done and/or a repro case on base y-bot.

**Comment by ideasean** [comment]
The failed match appears to be on AIML 

TICKET SET *

For which the template then calls an srai tag. That forces another conversation retrieval, after which the above error occurs. :-)

**Comment by keiffster** [comment]
I'll take a look this evening and see what the problem. I think the unit tests around multi sentence is low, so a good reason to go into that and make sure it's all covered

K

**Comment by ideasean** [comment]
No problems. For now I can just split the questions (calling from another script via REST API). 

Here's the AIML:
```
        <pattern>TICKET SET *</pattern>
        <template>
            <srai>
                TICKET_ITEM_RESPONSE 
                <sraix service="TicketService">SET <star index="1"/></sraix>
            </srai>
        </template>
```
It seems the error is thrown on the <star index="1">. The service is still called but just with SET.

**Comment by keiffster** [comment]
Fixed pushed to master, pulling the last sentence of the multi sentence question rather than the actual question being processed. All  my tests did not include <star /> so never picked it up

**Comment by keiffster** [comment]
Hey Sean, did you get round to seeing if this works for you ?

Just some house keeping, making sure no outstanding issues ahead of 1.0.0
