### ISSUE TITLE
Could Reverse AIML be coded into the bots? Also found a AIML Encyclopaedia.

### ISSUE THREAD

**Issue by sprinteroz** [keiffster/program-y#83]
Hi @keiffster and All,
I have been learning python and AIML 2.0 very slowly as I'm not much of a coder at the moment, but I can gather info and along the way maybe help out doing some little stuff to help the project in some way.

I found the open source for Reverse AIML for Pandora bots before it went privet I was wondering if we could add this in for the learning of the bot maybe.

[reversedaiml-0.4.zip](https://github.com/keiffster/program-y/files/1305983/reversedaiml-0.4.zip)
[ReversedAiml4Pandorabot.zip](https://github.com/keiffster/program-y/files/1305984/ReversedAiml4Pandorabot.zip)

Also found a AIML Wordnet Encyclopaedia 
[AIML Wordnet 3.0.zip](https://github.com/keiffster/program-y/files/1305982/AIML.Wordnet.3.0.zip)

Both set of files need to be changed to AIML 2.0 I was going to attempt it but did not want to mess up the file making more work for people.

Also I found this webpage with AIML sets like Jokes and Games, warnings templates,
http://www.square-bear.co.uk/aiml/

**Comment by keiffster** [comment]
I'll take a look, any valid aiml files can be added, and as the aiml files you include have GNU Copyright that should not cause an issue either

I can down load reversedaiml-0.4.zip and ReversedAiml4Pandorabot.zip but AIML Wordnet 3.0.zip is corrupt, if you can send me another copy I'll see how it can be added

k

**Comment by sprinteroz** [comment]
I just repacked it into a new zip
[AIML Wordnet 3.0.zip](https://github.com/keiffster/program-y/files/1306029/AIML.Wordnet.3.0.zip)

**Comment by keiffster** [comment]
Hey, just had a quick look at it looks like this is already included in Program-Y as the Professor Bot

The file was cut into many AIM files and then converted to support AIML 2 by user gimisa@yahoo.fr

K

**Comment by sprinteroz** [comment]
Oh Ok cool did not know that.

Would it be possible to add a interface like this python J.A.R.V.I.S interface?
https://github.com/nihal111/J.A.R.V.I.S

**Comment by keiffster** [comment]
Already there ;-) , but a seperate top level repo at https://github.com/keiffster/talk-y

Work in progress, but has access to a range of Text To Speech and Speech to Talk engines and I'm looking to integrate talkey https://pypi.python.org/pypi/talkey/0.1.0 which has more stt options

**Comment by sprinteroz** [comment]
Sweet did not realise that was the final aim for talk-y, can not wait till I can work out how to use it .   :simple_smile:
