### ISSUE TITLE
Sent a update for some files and added links to readme file, also have interesting info that might help with program-y

### ISSUE THREAD

**Issue by sprinteroz** [keiffster/program-y#87]
Hi @keiffster and All,
I have been searching around and found a few gems along the way, and hope some might be handy at some point.

I have add these links and sent it to the master ReadMe.md file "if you accept them changers" placed next to AIML 2.0 link
* [What Is AIML 2.0](https://sites.google.com/a/techmaru.com/techmaruhome/technology/what-is-aiml-2-0)
* [AIML 2.0 Draft Standards](https://sites.google.com/a/techmaru.com/techmaruhome/technology/aiml-2-1)

A low key hardly known syntax that could be useful
* [Poly-bot](https://github.com/Scarygami/poly-bot)

You define your <poly-bot> with a series of <poly-bot-rule>'s.
Each rule has several patterns and responses. If one of the patterns matches the input, the output will be chosen randomly from the available responses.

AIML syntax:
```
<category>
  <pattern>MY NAME IS *</pattern>
  <template>Nice to meet you <star/></template>
</category>

```
poly-bot syntax:
```
<poly-bot-rule>
  <span pattern>my name is (.+)</span>
  <span response>Nice to meet you $1</span>
</poly-but-rule>

```
Input: `My name is Gerwin`
Output: `Nice to meet you Gerwin`

Or there is DualLink for AIML code and opencog
* [DualLink](http://wiki.opencog.org/w/DualLink)
* [Pattern-matcher Recognizer](https://github.com/opencog/atomspace/blob/master/examples/pattern-matcher/recognizer.scm)

AI Based Chatbot Added New GUI compatible with all browsers, mobiles with autoscroll but its in python 2.7 
* [ChatBot](https://github.com/sohelamin/chatbot)

Do not know if you know about this github project, but he tests out python dependences to see what is better
* [Awesome-python](https://github.com/vinta/awesome-python)
Might be handy to know.
* [Awesome-python good info in pull request](https://github.com/vinta/awesome-python/pull/938)

**Just Interesting finds:**
Found the patents for AIML too just for reference  
* [Patents for AIML](https://www.google.com/patents/US20110078105)

Just thinking Maybe one-day you might like to take this to a Robot level.
* [PyRobotLab](https://github.com/MyRobotLab/pyrobotlab) 

If you like the info or found it useful let me know by a :+1:

**Comment by keiffster** [comment]
Thanks, there is quite a lot to explore in this email, in terms of some of the links you sent through

What is AIML 2 - Actually points to a document entitled "What is AIML 1.0.1". Which is the older original version of AIML which is out of date.

AIML 2.0 Draft Standards - This is interesting, as it actually points to a document referring to proposed new additions to the 2.0 spec. I've not seen this version of the doc but some of the major topics have already been added to Program-Y. 

Poly-bot - Its very basic spec, and only really covers single word wild card matching. This looks a lot like a very cut down version of ChatScript syntax. AIML can be a little verbose, but its well known and well understood and I would not want to introduce different ways to do the same thing.

**Comment by sprinteroz** [comment]
> What is AIML 2 - Actually points to a document entitled "What is AIML 1.0.1". Which is the older original version of AIML which is out of date.

Ok Np Just thought it might be handy as they explain the difference from 1.0.1 to 2.0 stranded for new comers to aiml. 

> AIML 2.0 Draft Standards - This is interesting, as it actually points to a document referring to proposed new additions to the 2.0 spec. I've not seen this version of the doc but some of the major topics have already been added to Program-Y.

Yeah its the only Information on AIML 2.0 I could find that I seen as useful info.

> Poly-bot - Its very basic spec, and only really covers single word wild card matching. This looks a lot like a very cut down version of ChatScript syntax. AIML can be a little verbose, but its well known and well understood and I would not want to introduce different ways to do the same thing.

Yeah I thought that would be the case as it would not be universal unless the others adopted it as well and I guess it would go throw stringent testing too

**Comment by sprinteroz** [comment]
I have changed the links from
 From
 [What Is AIML 2.0](https://sites.google.com/a/techmaru.com/techmaruhome/technology/what-is-aiml-2-0)
To
 [AIML 2.0 Elements Reference](http://callmom.pandorabots.com/static/reference/#elements/-lt-aiml-gt-)

Please review the new link

**Comment by keiffster** [comment]
Cool, I’m right in the middle of finishing the documentation ahead of 1.0.0, so I’ll work out the best places to add in your links

K

Keith Sterling
E: keith@keithsterling.com
M: +44 (0) 7771 597 630

**Comment by keiffster** [comment]
The 2 links have now been added to the following page of the wiki https://github.com/keiffster/program-y/wiki/AIML

**Comment by sprinteroz** [comment]
Cool, I got this one link here as well if you want to add it [What's new in AIML 2.0](https://www.botlibre.com/forum-post?id=1156738)
