### ISSUE TITLE
I have been making .aiml.csv files so Program AB, myRobotLab can use the AIML 2.0 library, also nice basic tool AIML_Assistant

### ISSUE THREAD

**Issue by sprinteroz** [keiffster/program-y#88]
Hi @keiffster and All,
I have been changing the **.aiml** files into **.aiml.csv** so programs like **ProgramAb Java** and **myRobotLab** can use the AIML 2.0 Library. . While doing all this and trying many converters I found one that works fine with **AIML 2.0**, and while I have been testing and reading on problems that can occur, I pondered there has to be a different way to do it and I believe I might have found the answer.

There are 2 **.bat** files **aiml2csv** and **csv2aiml**, in **ProgramAb** now if they where added to **program-y** it would be able to change **aiml2csv** and **csv2aiml** leaving the code nice and clean all the time, also added bonus is it can do this on the fly when changers need to be made.

The 2 **.bat** files I found are **aiml2csv** and **csv2aiml** they call a **.jar Java** program called **Ab.jar** and I believe this calls on **AIML_Assistant.jar** to do the final editing of the converted files **(_Nice tool on its own can edit and create **AIML** files_)**.

The **aiml2csv** and also **csv2aiml** **.bat** command files calls  `Ab.jar`  and `bot=name` they will need to be changed, also I think some paths need to be changed in the   **Ab.jar** so it can call files where to find and save after converting them files.

Here is some code that could be used in the  **.bat** files **aiml2csv** and **csv2aiml**.
```
java -cp lib/Ab.jar Main bot=y-bot action=aiml2csv trace=true morph=false
cp ./bots/y-bot/aimlif/*.aiml.csv ../Users/xxx/workspace/xxx/program-y/bots/y-bot/aimlif/ -f
```

So now after changing three quarters of **program-y** conversion I have stopped, and I will not be changing any more of the **AIML** to **CSV** at this stage, as it can be done better on the fly also added advantage is that  response templates will be faster for normal use , also mobile use a little quicker too.

I looked everywhere for something that would do this in python but all there is, is **pyAIML** and that's python 2.6 **not** python 3 compatible  

Review the **APPS.zip** files here: [MyRobotLab pyrobotlab](https://github.com/MyRobotLab/pyrobotlab/tree/master/home/hairygael/AIML/APPS)

 **AIML_Assistant** is in the zip file attached [Download Here: APPS.zip](https://github.com/keiffster/program-y/files/1327301/APPS.zip)

**Comment by keiffster** [comment]
There is nothing stopping you using this project, but I would prefer not to add other projects to Program-Y, for a few reasons

1) Its Java, and that would pollute the pure Python approach to Program-Y

2) It would add a dependency to the release cycle that is outside of Program-Y control

3) ( and probably the biggest ) I'm not a big fan of the csv format. The reference implementation Program-AB is not a true XML parser, instead it carries out textual parsing and only really treats XML as a loose definition. Implementing Program-Y I found a number of issues with Program-AB and its use of XML, that is one of the reasons Program-Y using a full XML parser and is incredibly strict when loading AIML files, this is to encourage the proper use of XML and the proper use of AIML as a standard.

**Comment by sprinteroz** [comment]
> There is nothing stopping you using this project, but I would prefer not to add other projects to Program-Y, for a few reasons
> 
> Its Java, and that would pollute the pure Python approach to Program-Y

Yeah thought you would want it all python.

> It would add a dependency to the release cycle that is outside of Program-Y control

Ok yeah I guess that could course problems for future builds  

> ( and probably the biggest ) I'm not a big fan of the csv format. The reference implementation Program-AB is not a true XML parser, instead it carries out textual parsing and only really treats XML as a loose definition. Implementing Program-Y I found a number of issues with Program-AB and its use of XML, that is one of the reasons Program-Y using a full XML parser and is incredibly strict when loading AIML files, this is to encourage the proper use of XML and the proper use of AIML as a standard.

Yeah I read that csv if not done right can kill your bot as xml formating can do funny things at times and also noticed that ProgramAb has a magic string in there program for AIMl as well.

**Comment by keiffster** [comment]
Next question we have to ask ourselves is which version of AIML 2 does it support. There is no definition only a draft spec and Pandora ( who Richard Wallace formed for commercial reasons ) adds tags that it does not document

Alice2 would not work with AIML 2 on Pandora, it includes tags such as first and rest for list processing and select, uniq, tuple, addtriple and deletetruple for RDF knowledge processing.

I have also found references to resetlearn and resetlearnf in other grammars

And then I have added/updated a number of grammars in Program-Y including dynamic vars, sets and maps, log, iset, imap and extension

So unfortunately unless you were working only with the AIML spec imposed by Pandora the AIML to CSV conversion either way would be problematic

However if you do use it and find any problems with Program-Y grammars, let me know and I can take a look

**Comment by ideasean** [comment]
I also support the pure Python approach :-)

Re XML/CSV - I am not sure how you would express this in CSV, for example...

```
    <category>
        <pattern>
            SERVER_SETTER * * * * 
        </pattern>
        <template>
          <think><set name="SERVER_SETTER_RSP"><star index="1"/></set></think>
          <condition name="SERVER_SETTER_RSP">
            <li value="OK">
              <think><set name="svrname"><star index="2"/></set></think>
              <think><set name="svrip"><star index="3"/></set></think>
                I am now focusing on Server <star index = "2"/> ||
                <star index="4"/> ||
                Commands: SERVER <srai>SERVER HELP COMMANDS</srai>
            </li>
            <li value="NOTFOUND"> Unable to find that server name. </li>             
            <li> Error occurred: <star index="4"/> </li>
          </condition>
        </template>
    </category>
```
This is called via srai after a service call to a backend API.

**Comment by keiffster** [comment]
Nice !, must show me it action one day !

K

**Comment by sprinteroz** [comment]
Found this info if it helps taken from: [Hanson Robotics Tiered pyAIML Chat System](http://wiki.hansonrobotics.com/w/Tiered_pyAIML_Chat_System)

> Authoring Support Utilities
>  Several utilities exist to translate AIML to a convenient spreadsheet form.   
> 
> aiml2tsv.py   is now preffered to aiml2csv,  so that commas can be imbedded in responses (templates) without using #Comma
> 
> The code currently strips set commands in templates, but preserves all contents of think commands.  We may revisit this, as existing ALICE aiml expects predicates to be set and gives bad answers.
>    
> csvUtils.py has functions to translate .csv files to AIML,  for either a three column short form or the long form that attempts to preserve more AIML structure 
>   
> csvScoring.py looks at the Rate column in a transcript saved by the chat logger and accumulates various statistics, appending to a .csv file.
