### ISSUE TITLE
Don't write to system folder

### ISSUE THREAD

**Issue by Dobatymo** [keiffster/program-y#89]
The windows bot yaml files (like rosie/config.windows.yaml) contain paths to the system folder (like `C:\Windows\Temp\rosie.brain`)

Please don't write to the system folder, that's very bad practice on windows (on every OS I guess). Rather write to the user specific temp folder.
You could change the path to `%TEMP%\rosie.brain` and use `os.path.expandvars()` or use the output of `tempfile.gettempdir()` to determine the output location.

On my system (windows 10) both methods default to `C:\Users\<username>\AppData\Local\Temp`, but this could be different on other systems.

**Comment by keiffster** [comment]
Thanks for that, not a window user, so glad of the call

I'll change the .cmd scripts and push to master this morning

**Comment by Dobatymo** [comment]
Thanks for your quick response. `C:\Temp` is not ideal also, but I can live with that. However this directory might not exist on most windows platforms, so you have to take care to create it, otherwise creating the files might fail.

**Comment by keiffster** [comment]
fixed and pushed to master
