### ISSUE TITLE
How to call external API's

### ISSUE THREAD

**Issue by newdev7** [keiffster/program-y#9]
Hi,

I'm new to python. I'm trying to create a chat bot. I want to call external API's to get the answer for some of the user's questions. I don't know how to call the external API's inside the .aiml file. In the [read me](https://keiffster.github.io/program-y/) file, I read we can use <extension> to call the native python classes. Can you provide some examples on how to call the external API's and this <extension> tag.

Thanks.

**Comment by JustArchi** [comment]
```curl 'http://127.0.0.1:5000/api/v1.0/ask?sessionid=123&question=hello'```

```
{
  "response": {
    "answer": "Hi nice to see you!",
    "question": "hello",
    "sessionid": "123"
  }
}
```

For example how to launch REST client, check ```alice2_rest.sh``` in bots/alice2.

**Comment by JustArchi** [comment]
Ah wait, you mean external APIs via ```<sraix>```, sorry, I'm not sure about this, hopefully keiff will answer.

**Comment by keiffster** [comment]
SRIAX in AIML 2 are a bit rubbish, added by the Pandora guys to allow them to call their own services, but they are not well documented and not extensible enough for what I wanted

Instead use the <extension> tag which is used for calling Python classes directly, which can then call other APIs via whichever mechanism you prefer as normal python code

Check out src/test/parser/template/graph/test_extension.py which shows examples of how to call an extension from within an AIML Tag.

<template>
	<extension path="test.parser.template.graph.test_extension.TestExtension">1 2 3
	</extension>
</template>

In this example, TestExtension conforms to a basic class of 

class TestExtension(object):

    def execute(self, data):
        print(data)
        return "executed"

When the template is evaluated, your extension class is dynamically loaded, and execute called with all the other data passed as a string into the variable data.

Parse this, do whatever operation you want to do and then return a string of values which will then be returned as part of normal AIML parsing.

If you want to parse the returned values, you can wrap this in an <srai> tag

WARNING, make sure your extension class is on the python path or it will not be picked up

Keiff

**Comment by newdev7** [comment]
@JustArchi @keiffster Thanks for your answer. Now I'm able to call the external API's using the tag which is used for calling Python classes as mentioned by you. Now I'm trying to call the program-y from external interface, I'll raise a question if I need any help.

**Comment by newdev7** [comment]
@JustArchi I tried to use the curl command in the terminal. But it returns `Failed to connect to 127.0.0.1 port 5000: Connection refused`. The configuration says localhost & port 5000 only, Can you help me with the information for the same.

**Comment by JustArchi** [comment]
And did you start Program-Y REST server first?

```
root@archi:~# netstat -tulpn | grep 5000
tcp        0      0 127.0.0.1:5000          0.0.0.0:*               LISTEN      2941/python3
```

You need firstly to start REST server, for example with ```alice2_rest.sh``` scripts in bots/alice2, then once it's up and listening you can communicate with it.

**Comment by newdev7** [comment]
@JustArchi Thanks. After running the alice2_rest.sh script, I am able to communicate with it.
