### ISSUE TITLE
Sanic install  packet uvloop-0.8.1  RuntimeError('uvloop does not support Windows at the moment')

### ISSUE THREAD

**Issue by sprinteroz** [keiffster/program-y#90]
Just read over the update on dependencies need and noticed Sanic is need so i went to install 1 out of the five failed on my windows 10 machine. Is this packet uvloop need?

```
Microsoft Windows [Version 10.0.15063]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\XXX>pip install sanic
Collecting sanic
  Downloading sanic-0.6.0-py3-none-any.whl (46kB)
    100% |████████████████████████████████| 51kB 164kB/s
Collecting httptools>=0.0.9 (from sanic)
  Downloading httptools-0.0.9.tar.gz (86kB)
    100% |████████████████████████████████| 92kB 849kB/s
Collecting ujson>=1.35 (from sanic)
  Downloading ujson-1.35.tar.gz (192kB)
    100% |████████████████████████████████| 194kB 822kB/s
Collecting websockets>=3.2 (from sanic)
  Downloading websockets-3.4-cp36-cp36m-win32.whl (50kB)
    100% |████████████████████████████████| 51kB 1.3MB/s
Collecting uvloop>=0.5.3 (from sanic)
  Downloading uvloop-0.8.1.tar.gz (1.7MB)
    100% |████████████████████████████████| 1.7MB 355kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\XXX\AppData\Local\Temp\pip-build-cdlca4n1\uvloop\setup.py", line 10, in <module>
        raise RuntimeError('uvloop does not support Windows at the moment')
    RuntimeError: uvloop does not support Windows at the moment
```

**Comment by keiffster** [comment]
Sanic on windows is poorly supported. When I have time I will look for better set of instructions. Until now it’s only really for Mac and Linux 

If you managed to get it installed before me then feel free to forward the instructions and I’ll add them to then wiki

**Comment by sprinteroz** [comment]
Hi @keiffster and All,
I have been trying everything I can think of and find on the net, but I'm afraid uvloop is Not meant to work on Windows and I do not see it being changed for windows anytime soon.

I installed it 500 different ways even got ubuntu 16.04 running on WSL not on a VM but it would give the same error. Image below of ubuntu program-y running on WSL

![ubuntu 16 04 running windows 10 wsl no vm uvloop will not install](https://user-images.githubusercontent.com/3536573/31316460-b184047a-ac79-11e7-8110-665d3503950f.png)

Here is the Windows uvloop tree but it is very unsopported and it should ber made into its own project or a fork of this one
https://github.com/MagicStack/uvloop/tree/win

There are ways around using uvloop but it has to be coded into the scripts, here are the 2 easiest ways to do it that I could find:
[Reception of some uv signals is emulated on Windows](http://docs.libuv.org/en/v1.x/signal.html)

 [uvloop windows code  On Windows try to use IOCP event loop.](https://github.com/MagicStack/uvloop/commit/3c741b4c27fec94569ff8c65222e4f314cf44079)

**Comment by keiffster** [comment]
I’ve read some blogs about starting sanic with certain config options to switch off uvloop but that starts to defeat the object of the async nature of sanic and means it’s no better than flask. However I am working on this and will push the scripts needed to make it work on windows

The standard way to improve flask performance is to front it with apache or nginx and then either of those take the load. I’ve added this to be todo list to document on the wiki as a howto

In a previous bot I built we also implemented redis cache and if your grammar is relatively small and has lots of common questions and answers you can see a 50-200% speed increase. I’ll be adding this to a 1.x release

K

Keith Sterling
E: keith@keithsterling.com
M: +44 (0) 7771 597 630

**Comment by keiffster** [comment]
So as yo may have found out and I have worked through all the other options, sanic is not supported on Windows and the dev team don't seem to have any plans to support it.

I have updated the documentation and wiki with this, and the created a .cmd file which informs people it doesn't work

I'll keep an eye on sanic and if they support windows eventually I'll update the scripts and mark it as supported

For now you should continue to use Flask on windows
