### ISSUE TITLE
Bot is not working whenever i type "sh y-bot.sh"

### ISSUE THREAD

**Issue by Sengkrak** [keiffster/program-y#92]
When ever i type "sh y-bot.sh" in terminal it apears

Traceback (most recent call last):
  File "../../src/programy/clients/console.py", line 20, in <module>
    from programy.clients.client import BotClient
  File "/data/data/com.termux/files/home/program-y-master/src/programy/clients/client.py", line 21, in <module>
    import yaml 
ModuleNotFoundError: No module named 'yaml'

please fixed thus problem.
Im using python 3.6 in termux.

**Comment by ohoachuck** [comment]
Hello Sengkrak,
did you install all [Python dependencies](https://github.com/keiffster/program-y/wiki/Python_Dependencies) ?
Something like : `pip3 install -r requirements.txt` from where this requirements.txt file is ...

O.

**Comment by sprinteroz** [comment]
To start the shell-script 'file.sh':
```
sh file.sh

bash file.sh
```
Another option is set executable permission using chmod command:
`chmod +x file.sh`

Now run .sh file as follows:
`./file.sh`

But you must be in the bot folder you want for `./` to work

**Comment by keiffster** [comment]
“pip3 list” should tell you if yaml is installed sounds like it’s not

Check the wiki and make sure you have followed all the steps especially installing the requirements.txt file as others have pointed out

To run use “./y-boy.sh”. I use bash personally and only test with this shell

K

**Comment by keiffster** [comment]
Hi, have you resolved this issue ?

**Comment by keiffster** [comment]
No response, so assuming its fixed
