### ISSUE TITLE
`unknown response` doesn't work.

### ISSUE THREAD

**Issue by papower1** [keiffster/program-y#93]
Below code block is in ask function from 'chatsrv.py'.

At the first line of the codes, It isn't `None` when the question is not known.
Because default response is already filled that.

Two options.

1. modify ask_question to keep None when there is no knowledge about it. (rather default_response)
2. modify the second line, 'response is None' to 'response is in default_response'.

Or, any suggestions?
Did I misunderstand something, maybe?

```
response = WEBCHAT_CLIENT.bot.ask_question(sessionid, question)
if response is None:
	answer = WEBCHAT_CLIENT.bot.default_response
	WEBCHAT_CLIENT.log_unknown_response(question)
else:
	answer = response
	WEBCHAT_CLIENT.log_response(question, response)

response = {"question": question,
			"answer": answer,
			"sessionid": sessionid
		   }

return jsonify({'response': response})
```

**Comment by keiffster** [comment]
Looks like log_unknown_response ( and also log_response ) need to be lifted up into the bot and have the logging done there rather than in the client. 
Looking at the history of the code, I've refactored the code, but left behind these functions
I'll work on a fix and push to development

**Comment by keiffster** [comment]
log_response and log_unknown_response moved into an interface and then passed around as needed. Up to clients to implement how they want, default methods do nothing. Just running final testing and I'll push to dev branch later today

**Comment by keiffster** [comment]
Will now ship in 1.2

**Comment by papower1** [comment]
Wonderful.
