### ISSUE TITLE
Running programy with limited rights...

### ISSUE THREAD

**Issue by ideasean** [keiffster/program-y#95]
We're progressively locking down our runtime environment. We'd like to run ProgramY as a "user" (not admin) account with read access to only to bot source code, and only give read/write where really needed (ie least priviledge). 

It seems though there are several cases where files are being opened with read/write but probably not needed, eg the config.yaml and logging.yaml files. However, after resolving these issues, there is an error loading brain without giving reference to a file. 

Not an urgent issue - just getting into the pipeline (if agreed).

**Comment by keiffster** [comment]
over zealous use of 'r+' are open mode, should be an easy fix

**Comment by keiffster** [comment]
Fix done and tested, works on unix and windows, will come in 1.2

**Comment by keiffster** [comment]
issue now updated in the development branch and will be pushed to master over the next couple days. All files opened in read only mode unless actually required for writing to

**Comment by keiffster** [comment]
Released in v1.2.0 and onwards

**Comment by ideasean** [comment]
Thanks!
