### ISSUE TITLE
Authorisation denied_srai does not fire srai, but thats probably ok...

### ISSUE THREAD

**Issue by ideasean** [keiffster/program-y#96]
For this config - 

```
        authentication:
            classname: programy.security.authenticate.passthrough.BasicPassThroughAuthenticationService
            denied_srai: AUTHENTICATION_FAILED

```
This doesn't actually fire the SRAI. But thats probably ok, since to fire the SRAI would require ask_question, which will then check authorisation, which will fail, which will then trigger SRAI...

Instead I just changed AUTHENTICATION_FAILED to the message to give to the user if failed. It might be good to update this config item to denied_message?

One other item on authorisation while in this code area, I think if self_.authorisation is none (eg a bug in auth causes it not to load), but there seems to be some config items there, the default should be to deny access? Maybe its just a safety mechanism :-)

Sean

**Comment by keiffster** [comment]
I’ve been working on the issue you reported regarding ‘denied_srai’ conflict when access is denied. A definite issue in certain circumstances and I have now added a new version of the authentication handle, which will go into 1.2.2. I’ve added ‘denied_txt’ which you can specify

a) Either as an alternative to denied_srai in which the text is used as is, with no further processing
b) In addition to denied_srai, so if that processing fails, if then falls back to the text item

1.2.2 just going through final testing

K
