### ISSUE TITLE
No such file or directory: './conversations'

### ISSUE THREAD

**Issue by martinjoubert** [keiffster/program-y#97]
I get the following error whenever I run the latest zip locally on my Mac OS 10.13 with Python 3.6:

  File "/Users/bob/program-y-master/src/programy/dialog.py", line 243, in empty
    convo_files = [f for f in listdir(self._config._dir) if isfile(join(self._config._dir, f))]
FileNotFoundError: [Errno 2] No such file or directory: './conversations'

This is the current content of y-bot.sh that I run:
#! /bin/sh
clear
export PYTHONPATH=../../src:../../libs/MetOffer-1.3.2:.
python3 ../../src/programy/clients/rest.py --config ./config.yaml --cformat yaml --logging ./logging.yaml

I have tried to create a directory called conversations where dialog.py is located without success.

**Comment by keiffster** [comment]
Create a directory in the root of the bot, I.e in the folder that holds the script y-bot.sh. That should get you going

I’ll update the code to auto create if missing

K

**Comment by keiffster** [comment]
This is now fixed on master and in release v1.2.1 which I have just released
