### ISSUE TITLE
I am testing <iset> tag. Example is not working.

### ISSUE THREAD

**Issue by abcortes** [keiffster/program-y#98]
# Detailed Description
I am testing pattern \<iset\> tag. It is not working as expected. I am sure I entered example AIML correctly.

Expected behaviour is to display what is in the template.

Text in template is not showing and it gives "ERROR   No word [Wales] found in iset" in logs.

# Possible Solution
Function must be a bit similar to pattern \<set\>, but this one is a shorthand.

# Steps to Reproduce
Type the \<iset\> tag example.

# Environment
* Version of Y-Bot: program-y 1.1.0
* Version of Python: Python 3.5.2 
* Operating System ( inc Version ): Ubuntu 16

**Comment by abcortes** [comment]
I tested it again on program-y 1.2.0, Fedora 26, Python 3.6.2 and using y-bot CLI. I got same negative result.

**Comment by keiffster** [comment]
I've just had a look and all the unit tests use upper case, changing the sentence to lower case causes issues. Have a fix for it shortly

**Comment by keiffster** [comment]
Fixed and ready for release later this evening

**Comment by keiffster** [comment]
Pushed to master

**Comment by abcortes** [comment]
Great! Both <set> and <iset> pattern tags are now working from my test. Thanks!.
