### ISSUE TITLE
repetitive response from chatbot

### ISSUE THREAD

**Issue by pankajdata4u** [keiffster/program-y#99]
When I ask bot some question, it reply back multiple times

for example if i ask " can you send email to my friend"

it reply back with "Yes i can, what is the email address?" but multiple time.

I checked the codes but did not found any valid answer.
And it happen only with some conversation.

Please help me out

**Comment by keiffster** [comment]
Probably just a recursive loop in the reduction grammars

They are taken from Alice 2 and are a bit of a mess. In the middle of cleaning them up so will find the loop and fix shortly

**Comment by keiffster** [comment]
Which grammar and bot are you using, looks like you are running Alice2? is that the case ?

**Comment by pankajdata4u** [comment]
i am using y-bot, it's good but sometime give wiage answers.
I have used your inbuilt grammar mechanism.

**Comment by keiffster** [comment]
The grammar is still work in progress, its  copy of Alice 2 and is about 50-60% fixed ( Alice 2 being very broken )

I have a tentative plan to have a fully working copy of Alice 2 plus s my own amendment by end of this month

However, y-bot is really a development platform and I would encourage you to create your own grammar, especially for commercial purposes as Alice 2 is under copyright of Pandora

K

**Comment by pankajdata4u** [comment]
Don't worry, I am not using it for commercial purpose. I am comparing some of the chatbots which can be used for day to day usage. And i understand we should have our own grammar.

**Comment by keiffster** [comment]
Try new release, has some major grammar updates

**Comment by keiffster** [comment]
I've double checked and there is not actually a grammar to support the question. 

So closing this issue,
